### ISSUE TITLE
will you release a gradle?

### ISSUE THREAD

**Issue by LiuDeng** [roughike/BottomBar#1]
will you release a gradle?
and is this library have been finished for stable use? do you still have some import feature to add or modify?

Thank you for your great job~
Best Wishes~

**Comment by roughike** [comment]
@LiuDeng 
I just put it to jCenter, shouldn't take too long for the Gradle dependency.

I'm most likely to add features / improvements during this week. The library should be working just fine, although I haven't tested it thoroughly.

**Comment by LiuDeng** [comment]
Thank you for your reply  and i will keep watching on this ~

**Comment by hamen** [comment]
You could consider Jitpack to publish SNAPSHOT releases in the meantime.

**Comment by roughike** [comment]
@hamen 
Just did that, thank you very many!

**Comment by roughike** [comment]
[It's now approved.](https://github.com/roughike/BottomBar/blob/master/README.md#gimme-that-gradle-sweetness-pls)
