### ISSUE TITLE
Does not follow Material design specs

### ISSUE THREAD

**Issue by vikramkakkar** [roughike/BottomBar#10]
Hi, this was a fast release! I was just reading about this a couple of days ago.

I noticed that the second gif you posted does not follow the material design specs. The active & inactive items don't shrink or expand.

**Comment by roughike** [comment]
I'm aware. That has something to do with this being a fast release ;)

I'll implement this as fast as I can though.

**Comment by roughike** [comment]
FINALLY it's done!

Enabled by default from version _1.2.6._ and up.

**Comment by vikramkakkar** [comment]
Looks sweet. Thanks @roughike
