### ISSUE TITLE
dark theme can't lasting

### ISSUE THREAD

**Issue by bingningO** [roughike/BottomBar#100]
HI，

thanks a lot for the excellent work.

I set dark theme mode when initializing the Bottom Bar. It works.
![image](https://cloud.githubusercontent.com/assets/15116945/14074722/294ffba0-f50e-11e5-89eb-6a9b9e4b0905.png)

But when I choose other items, the mode come back to the default mode. as the following shows.
![image](https://cloud.githubusercontent.com/assets/15116945/14074763/6cec4af8-f50e-11e5-9ee5-03d0e0aebcdf.png)

could you help solve this ?

Best Regards.

**Comment by roughike** [comment]
Could you provide a Java code example on what you're doing with the BottomBar?

**Comment by alvarlagerlof** [comment]
Looks like you're setting colors for the other the tabs, maybe try to not do that?

**Comment by bingningO** [comment]
@alvarlagerlof  thanks for your answering.

my fault not seeing the author's comment:"// Use the dark theme. Ignored on mobile when there are more than three tabs."

but hope it can be set dark theme/ colored no matter it is 3 or 4 or 5 items. and easily return to the default mode. @roughike

**Comment by roughike** [comment]
Currently you can map colors for each tabs, so if you want to have a dark background on all tabs when there's more than 3 items, you can use ```mapColorForTabAt()``` for all tabs you have.

**Comment by roughike** [comment]
Now it works everywhere starting from version _1.2.7._

```java
mBottomBar.useDarkTheme();
```
