### ISSUE TITLE
How to access BottomBarTab array?

### ISSUE THREAD

**Issue by Jengking** [roughike/BottomBar#103]
I need a way to access the BottomBarTab array to change the title according to language selection for my app. Currently the bottombartab title only change when I restart the app.
Thanks

**Comment by roughike** [comment]
So your app has a custom language selection possibility that overrides the current system language?

**Comment by Jengking** [comment]
Yes. All others strings in the app can change language without restarting the app. I use the same languages string files on the bottombartab titles but it seems not working. I was thinking if i have access to the bottombartab array, I might be able to reload the tabs at runtime.

**Comment by Jengking** [comment]
Nevermind got it to work although it would be more direct to access the array. 

Solution:
ViewGroup outerContainer = (ViewGroup) mBottomBar.getBar();
ViewGroup itemContainer = (ViewGroup) outerContainer.getChildAt(0);

TextView button1Text = (TextView) itemContainer.getChildAt(0).findViewById(R.id.bb_bottom_bar_title);

from here on can manipulate the textview or Imageview.

Anyway thank you for the library
