### ISSUE TITLE
Set selected item programmatically

### ISSUE THREAD

**Issue by javiersantos** [roughike/BottomBar#104]
I'm checking the methods of this library but don't see nothing about selecting the active item programmatically. Is there any way to achieve this?

Thanks and keep up the good work!

**Comment by roughike** [comment]
```java
// The "0" in this case is the first tab, and "false" indicates if there should be animation or not.
mBottomBar.selectTabAtPosition(0, false);
```

**Comment by OkySabeni** [comment]
Would love to see this on the home page docs :)

**Comment by befitdonate** [comment]
Yeah this should definitely be on the home page.

**Comment by yombunker** [comment]
@OkySabeni @befitdonate thanks for the feedback

**Comment by bertrandmartel** [comment]
It seems it can be done using : 
```
mBottombar.selectTabWithId(R.id.tab_outbox);
```
As `selectTabAtPosition` has now private scope
