### ISSUE TITLE
Space below the bottom bar

### ISSUE THREAD

**Issue by yashwanthsandeep** [roughike/BottomBar#106]
Hi,

Any suggestion to remove the space below bottom bar(attached) in Marshmallow.

Regards,
Sandeep.

![sc](https://cloud.githubusercontent.com/assets/2968875/14135815/31644ca8-f692-11e5-9b94-20001a82ab24.png)

**Comment by alvarlagerlof** [comment]
Maybe it's thinking that you have a transparent navbar. This should work:
`mBottomBar.noNavBarGoodness();`

But if you want a transparent navbar then go to your styles.xml and add:
` <item name="android:windowTranslucentNavigation">true</item>`

**Comment by roughike** [comment]
What device/emulator are you testing on?

**Comment by yashwanthsandeep** [comment]
@roughike: it's nexus 6 device

**Comment by yashwanthsandeep** [comment]
mBottomBar = BottomBar.attach(findViewById(R.id.fragmentContainer), savedInstanceState);

**Comment by roughike** [comment]
The BottomBar can't extend behind the Navigation Bar, because it's contained by the fragment container.

Try this:

```mBottomBar = BottomBar.attach(this, savedInstanceState);```

**Comment by yashwanthsandeep** [comment]
@roughike 
After adding this line `mBottomBar = BottomBar.attach(this, savedInstanceState);` observed a white patch above BottomBar. 

Its fine in S4 device
![s4](https://cloud.githubusercontent.com/assets/2968875/14162671/ab0c52ba-f720-11e5-8145-e9f00fe1b615.png)

In Nexus 6 device
![nexus 6](https://cloud.githubusercontent.com/assets/2968875/14162706/0b2b5df8-f721-11e5-9718-f6981d6d633a.png)

Please help

**Comment by roughike** [comment]
You're using MaterialDrawer, aren't you?

**Comment by yashwanthsandeep** [comment]
Its an Android Studio template like below:

<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:openDrawer="start">

    <include
        layout="@layout/app_bar_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:fitsSystemWindows="true"
        app:headerLayout="@layout/nav_header_main"
        app:menu="@menu/activity_main_drawer" />

</android.support.v4.widget.DrawerLayout>

**Comment by roughike** [comment]
Could you provide the app_bar_main layout for me?

**Comment by yashwanthsandeep** [comment]
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="com.km.apps.seed.MainActivity">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay"
        app:elevation="0dp">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:popupTheme="@style/AppTheme.PopupOverlay" />

    </android.support.design.widget.AppBarLayout>

    <include layout="@layout/content_main" />

</android.support.design.widget.CoordinatorLayout>

**Comment by yashwanthsandeep** [comment]
content_main.xml

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.km.apps.seed.MainActivity"
    tools:showIn="@layout/app_bar_main">

    <FrameLayout
        android:id="@+id/fragmentContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</RelativeLayout>

**Comment by roughike** [comment]
Here you go:

**activity_main.xml**

Just remove ```fitsSystemWindows="true"``` from both _DrawerLayout_ and _NavigationView_:

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:openDrawer="start">

    <include
        layout="@layout/app_bar_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:headerLayout="@layout/nav_header_main"
        app:menu="@menu/activity_main_drawer" />

</android.support.v4.widget.DrawerLayout>
```

**app_bar_main.xml**

```xml
...
<android.support.design.widget.CoordinatorLayout 
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:id="@+id/myCoordinator"
...
```

**MainActivity.java**

```java
BottomBar bottomBar = BottomBar.attach(findViewById(R.id.myCoordinator), savedInstanceState);
bottomBar.noTopOffset();
// Set items and everything else.
```

**Comment by vinaybisht** [comment]
Same thing happening with me. I am using your code. Its really awesome. But i am also facing the same problem. How to Remove the white space above bottom bar ? Plz suggest me . Thanks in advance

**Comment by nareshravva** [comment]
https://stackoverflow.com/questions/44566019/empty-space-below-the-bottom-bar-in-android

**Comment by nareshravva** [comment]
Its works for me

just Remove app:bb_behavior="underNavbar" from your xml

https://stackoverflow.com/questions/44566019/empty-space-below-the-bottom-bar-in-android/44566307#44566307
