### ISSUE TITLE
new Fragment question

### ISSUE THREAD

**Issue by roger5089** [roughike/BottomBar#107]
Hi all 

i have create one new BlankFragment into this sample , but it does not work on this code , may be am i miss something in this part?

    `  protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
       ** Fragment fg = null;**

        mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar.setItemsFromMenu(R.menu.bottombar_menu, new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId) {
                if (menuItemId == R.id.bb_menu_nearby) {
                    // The user selected item number one.
                  **  new BlankFragment();**
                }

            }

            @Override
            public void onMenuTabReSelected(@IdRes int menuItemId) {
                if (menuItemId == R.id.bb_menu_nearby) {
                    // The user reselected item number one, scroll your content to top.
                    new BlankFragment();
                }
            }
        });

        // Setting colors for different tabs when there's more than three of them.
        // You can set colors for tabs in three different ways as shown below.
        mBottomBar.mapColorForTab(0, ContextCompat.getColor(this, R.color.colorAccent));
        mBottomBar.mapColorForTab(1, 0xFF5D4037);
        mBottomBar.mapColorForTab(2, "#7B1FA2");
        mBottomBar.mapColorForTab(3, "#FF5252");
        mBottomBar.mapColorForTab(4, "#FF9800");
    }`

**Comment by roger5089** [comment]
`public class BlankFragment extends Fragment{

    private static final String ARG_TEXT = "ARG_TEXT";

    public BlankFragment() {
    }


    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        TextView textView = new TextView(getActivity());
        textView.setText(getArguments().getString(ARG_TEXT));

        return textView;
    }
}
`

**Comment by roughike** [comment]
You're just creating a new Fragment, but you're not adding it anywhere in your layout.

[See here for instructions how to work with Fragments.](http://developer.android.com/training/basics/fragments/fragment-ui.html)

**Comment by roger5089** [comment]
Yes i had edit one Fragment and new onMenuTabSelected , when i selected bb_menu_nearby 
it not active this Fragment
![1](https://cloud.githubusercontent.com/assets/4618768/14163997/deb34f44-f72d-11e5-8096-b0fa144e19a7.JPG)
