### ISSUE TITLE
Is it possible to add badge title in String type

### ISSUE THREAD

**Issue by youngnot** [roughike/BottomBar#109]
Dear friends,
  Thanks for your good job.
  Is it possible to add badge title in String type? Currently it seems that it can only use integer type as count.

**Comment by alvarlagerlof** [comment]
Maybe you can do something like this

` String foo = "2";
int bar = Integer.valueOf(foo);`

**Comment by alvarlagerlof** [comment]
Maybe you can do something like this

`String foo = "2";`
` int bar = Integer.valueOf(foo);`

**Comment by roughike** [comment]
Do as @alvarlagerlof suggested.
