### ISSUE TITLE
Android Iconics

### ISSUE THREAD

**Issue by AlexLionne** [roughike/BottomBar#11]
I'm using your BottomBar with another good lib to generate icons : Android Iconics. Its implementation is so easy, you can maybe refer a link into the readme for people who want ? Or don't knoa about that lib ?
[https://github.com/mikepenz/Android-Iconics](link)
quick showcase : 
```java 
bottomBar = BottomBar.attach(view, savedInstanceState);
        bottomBar.setFragmentItems(getActivity().getSupportFragmentManager(), R.id.container,
                        new BottomBarFragment(new LatestKitFragment(), new IconicsDrawable(getActivity(), CommunityMaterial.Icon.cmd_trending_up).sizeDp(18), "Trending"),
                        new BottomBarFragment(new LatestKitFragment(), new IconicsDrawable(getActivity(), CommunityMaterial.Icon.cmd_newspaper).sizeDp(18), "Latest"),
                        new BottomBarFragment(new LatestKitFragment(), new IconicsDrawable(getActivity(), CommunityMaterial.Icon.cmd_tag_faces).sizeDp(18), "All")
        );

```

**Comment by AlexLionne** [comment]
I would be happy to open this as a question and not an issue but I don't know how since I'm new to github sorry

**Comment by PareshMayani** [comment]
Reference URL is pasted wrong for the given link https://github.com/mikepenz/Android-Iconics

**Comment by roughike** [comment]
Iconics is awesome, but it is not related to this library itself. I think most Iconics users already know how to use them properly. 

The Readme is already cluttered as is (and there's more content to come!), so I'm not adding a link to Iconics right now.

Thanks for the suggestion though.
