### ISSUE TITLE
Transparent navbar doesn't work when colors are not set (attachShy)

### ISSUE THREAD

**Issue by alvarlagerlof** [roughike/BottomBar#110]
I have three items in my bottombar, and i have a transparent navbar. The problem is that the bottombar needs to be moved up above the navbar. I want the scrolling to be the same as if it where colored.

Sorry for my terrible English.

Opened:
![screenshot mar 30 2016 11_43_38](https://cloud.githubusercontent.com/assets/14835120/14138302/ddabd6e6-f66c-11e5-9a06-194dcaef3551.png)

Closed:
![screenshot mar 30 2016 11_42_08](https://cloud.githubusercontent.com/assets/14835120/14138289/c1327e2a-f66c-11e5-9322-f9809190f995.png)

**Comment by dotWee** [comment]
Sorry for the off-topic question; what do you use for the search bar? Own implementation or a library?

**Comment by alvarlagerlof** [comment]
@dotWee Haha, it's just a cardview with some text. And then when you click on it it opens a transparent activity with a cardview in the same location. Current published version: https://play.google.com/store/apps/details?id=com.alvarlagerlof.temadagarapp

**Comment by dotWee** [comment]
Well thats actually a pretty cool solution. Thanks for the tip!

**Comment by NikolaDespotoski** [comment]
@alvarlagerlof  Off topic. You should chase some girls first, before you start programming. Programming can wait, girls cant. :D

**Comment by roughike** [comment]
@alvarlagerlof 
@NikolaDespotoski 

Completely disagree. Girls can wait, make sure you're the best Java / Android / whatever developer in your city / state / country before you turn 24, and girls will come.

Or maybe not, but money will come. And against the common misconception, with money, you actually _can_ buy love.

**Comment by NikolaDespotoski** [comment]
@roughike @alvarlagerlof  Well thats kinda contrary yet sustainable argument to mine. Haha. I can't object any further. :D

**Comment by alvarlagerlof** [comment]
@roughike @NikolaDespotoski Haha, this has gone so off-topic, anybody still remembering my question?

**Comment by roughike** [comment]
The BottomBar doesn't currently support transparent Navigation Bars for the ```attachShy()``` method when there are less than 4 items.

I'm fixing this asap.

**Comment by alvarlagerlof** [comment]
Thank you som much! @roughike

**Comment by alvarlagerlof** [comment]
Anybody please? @roughike @NikolaDespotoski

**Comment by TurKurT656** [comment]
not fixed yet?

**Comment by alvarlagerlof** [comment]
@TurKur656 Currently have 1.3.5 just noticed the update. Will try 1.3.7 tomorrow

**Comment by roughike** [comment]
This is fixed in the newest versions (and a little bug in the upcoming 2.0.2 version).
