### ISSUE TITLE
Active icon is moved up when all tabs show text

### ISSUE THREAD

**Issue by TWellington** [roughike/BottomBar#114]
The active view shouldn't have the icon moved up 2dp when the other icons also have text. 

![components_bottomnavigation_spec_fixed5](https://cloud.githubusercontent.com/assets/7970209/14152949/45769776-f67b-11e5-9dc0-68f0ecb63b8f.png)

![screenshot_20160330-132314](https://cloud.githubusercontent.com/assets/7970209/14152932/33afde94-f67b-11e5-9541-f922a7586ac6.png)

**Comment by roughike** [comment]
I'm pretty sure it should.

See here:

![https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HcV9maGFKNVN1STQ/components_bottomnavigation_spec_fixed1.png](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HcV9maGFKNVN1STQ/components_bottomnavigation_spec_fixed1.png)
