### ISSUE TITLE
what about fragment

### ISSUE THREAD

**Issue by focus2846** [roughike/BottomBar#116]
how to add fragment 
i call 
getSupportFragmentManager().beginTransaction().replace(R.id.container, new TabHomeFm()).commit()
that is error

**Comment by alvarlagerlof** [comment]
Maybe your fragment doesn't use android.support.v4.app.Fragment?

**Comment by bingningO** [comment]
I can add fragment, please check my codes:

.java document:
FragmentTransaction transaction = mFragmentManager.beginTransaction();
android.app.Fragment fragment =  new BnHomeFragment();
transaction.replace(R.id.content_bb, fragment).commit();

.xml document:
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/myCoordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">
    <FrameLayout
        android:id="@+id/content_bb"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"></FrameLayout>
</android.support.design.widget.CoordinatorLayout>

**Comment by jml90** [comment]
It looks like you are using normal fragments and trying to use supportFragmentManger with them.
I think you must replace this:
 getSupportFragmentManager().beginTransaction().replace(R.id.container, new TabHomeFm()).commit();

for this: 
 getFragmentManager().beginTransaction().replace(R.id.container, new TabHomeFm()).commit();

**Comment by roughike** [comment]
@jml90 is right.

As this issue is not related to this library, I'm closing this one.
