### ISSUE TITLE
Is it possible to set a different icon on Tab selected?

### ISSUE THREAD

**Issue by chrjsorg** [roughike/BottomBar#118]
I need to set a different colored icon when a Tab is selected. Is this possible?

**Comment by roughike** [comment]
How many tabs are you using?

**Comment by chrjsorg** [comment]
I'm using 5 Tabs.

**Comment by roughike** [comment]
It's not currently possible. I'll look into this and see if I'll implement this in the future.

**Comment by chrjsorg** [comment]
Thank you. And thanks for your great library.

**Comment by chrjsorg** [comment]
Another question, is it possible to set the color of the text of the active tab differently with 5 tabs? :/

**Comment by roughike** [comment]
Btw, why do you want to change the icon when the user selects a tab? Wouldn't that be confusing UI?

**Comment by chrjsorg** [comment]
Sorry, I wasn't clear.
I just want the exact behavior as seen in the gif. (Different icon color/text color on selected item)

**Comment by chrjsorg** [comment]
Summarized i'd suggest you remove this restriction.

> // Set the color for the active tab. Ignored on mobile when there are more than three tabs.
`mBottomBar.setActiveTabColor("#009688");`

**Comment by roughike** [comment]
Now possible in version _1.3.2._

```java
// Show all titles all the time.
mBottomBar.useFixedMode();
```
