### ISSUE TITLE
TabSelectedListener should have onTabUnselected

### ISSUE THREAD

**Issue by GitskariosTest** [roughike/BottomBar#119]
Example:

```
mBottomBar.setOnTabClickListener(new OnTabClickListener() {
      @Override
      public void onTabSelected(int position) {
        selectItem(position);
      }
      @Override
      public void onTabReSelected(int position) {
        selectItem(position);
      }

      @Override
      public void onTabUnSelected(int position) {
        freeMemory(position);
      }

    });
```

**Comment by alvarlagerlof** [comment]
I don't think it's necessary, maybe you could do something like this:

```

int latestTab;
Boolean firstRun = false;

mBottomBar.setOnTabClickListener(new OnTabClickListener() {
      @Override
      public void onTabSelected(int position) {
        selectItem(position);
        if (!firstRun) {
           freeMemory(latestTab);
        }
        latestTab = position;
      }
      @Override
      public void onTabReSelected(int position) {
        selectItem(position);
      }

    });
```

I think this works, haven't tested yet. firstRun is for making sure that the memory is not freed before it's first set.

I hope that you get the idea 😀

**Comment by alorma** [comment]
yes i know, but if the library handles that, it will be easy.

TabLayout supports that

**Comment by alvarlagerlof** [comment]
I updated it, it's more simple now

**Comment by yombunker** [comment]
@alorma @GitskariosTest @alvarlagerlof on the next update we are including another listener called OverrideTabSelectionListener which pretty much tells you which one is the current one and what is going to be selected after, if that doesn't work for you re-open the issue.
