### ISSUE TITLE
Using defaultTabPosition results in wrong aligned other icons

### ISSUE THREAD

**Issue by Nolanus** [roughike/BottomBar#120]
I'm using `mBottomBar.setDefaultTabPosition(2);` to start the bottomBar with the third tab selected, resulting in misaligned icons:

![device-2016-04-01-135522](https://cloud.githubusercontent.com/assets/3458616/14206203/cc048540-f811-11e5-86eb-39d1b1e5b73d.png)

When I select another item except for the first one, the other icons keep being misaligned, the last one even leaving the screen.
![device-2016-04-01-135536](https://cloud.githubusercontent.com/assets/3458616/14206222/015e8394-f812-11e5-9651-aeb442735ded.png)

The selecting the fifth item (notice the larger space between item 1 and 2):
![device-2016-04-01-135550](https://cloud.githubusercontent.com/assets/3458616/14206226/095794f0-f812-11e5-825b-df4206f1afac.png)

Only when selecting the first item the aligned starts becoming correct:
![device-2016-04-01-135601](https://cloud.githubusercontent.com/assets/3458616/14206236/19efac08-f812-11e5-9fdb-021ad57643ea.png)

**Comment by roughike** [comment]
Will fix this ASAP.

Thanks for reporting.

**Comment by roughike** [comment]
Now it works. Set the default tab right after calling ```attach()```:

```java
mBottomBar = BottomBar.attach(this, savedInstanceState);
mBottomBar.setDefaultTabPosition(2);
```
