### ISSUE TITLE
setDefaultTabPosition(int) problem

### ISSUE THREAD

**Issue by jonasborggren** [roughike/BottomBar#121]
When using `setDefaultTabPosition(2)` after adding items via `setItemsFromMenu(int, OnMenuTabClickListener)` then the page 0 will be shown and then switch to your preferred default position, causing the page 0 to load while the page you wanted as default loads.

**Comment by roughike** [comment]
Now it works. Set the default tab right after calling ```attach()```:

```java
mBottomBar = BottomBar.attach(this, savedInstanceState);
mBottomBar.setDefaultTabPosition(2);
```
