### ISSUE TITLE
support icon font?

### ISSUE THREAD

**Issue by mojizo** [roughike/BottomBar#123]

**Comment by roughike** [comment]
What do you mean? Could you elaborate?

**Comment by mojizo** [comment]
I mean i want to use icon fonts,but this project seems can only use drawable icons.

**Comment by roughike** [comment]
How would you usually use icon fonts in an Android app? Is there a well-known library for that?

**Comment by mojizo** [comment]
I don't know this kind of library so far.It is very simple to use icon font in Android,just like a TextView.

**Comment by xiongwei-git** [comment]
@mojizo  I have tried this. Support  icon fonts.  I used https://github.com/mikepenz/Android-Iconics like this:
`    mBottomBar.setItems(new BottomBarTab(
        new IconicsDrawable(this).icon(FontAwesome.Icon.faw_video_camera).sizeDp(30),
        "视频"), new BottomBarTab(
        new IconicsDrawable(this).icon(FontAwesome.Icon.faw_microphone).sizeDp(30),
        "主播"), new BottomBarTab(
        new IconicsDrawable(this).icon(FontAwesome.Icon.faw_film).sizeDp(30),
        "电影"), new BottomBarTab(
        new IconicsDrawable(this).icon(FontAwesome.Icon.faw_user).sizeDp(30),
        "会员"));`

**Comment by mojizo** [comment]
@xiongwei-git Nice.Thank you.

**Comment by roughike** [comment]
I think that solves it, so I'm closing this one.
