### ISSUE TITLE
App using

### ISSUE THREAD

**Issue by alorma** [roughike/BottomBar#124]
Hi.

I'm the developer of Gitskarios: https://play.google.com/store/apps/details?id=com.alorma.github

I implemented this library in the app (on pull request screen), it will be released soon.

Will you add into the README?

**Comment by roughike** [comment]
Yes I will.

And good work, I love that app and use it daily!

**Comment by alorma** [comment]
:$ Thanks! I will send you an APK to test the BottomBar
