### ISSUE TITLE
display icon and fonts

### ISSUE THREAD

**Issue by roger5089** [roughike/BottomBar#125]
Dear all 

from you API where is setting if i want to display icon and fonts in same time , not just use TabSelected.

i have try adjustment xml setting file item name="android:textSize from 14 to10 , 

`  <style name="BB_BottomBarItem_Fixed.Title" parent="TextAppearance.AppCompat.Body1">
        <item name="android:textSize">10sp</item> 
        <item name="android:singleLine">true</item>
        <item name="android:gravity">center_horizontal</item>
    </style>`

**Comment by Nolanus** [comment]
As far as I understand your question, you want to display the label text below the icon for every tab, not just the one currently selected.
As BottomBar implements the [Bottom navigation according to the material design specifications](https://www.google.com/design/spec/components/bottom-navigation.html#), the label below the icons should be hidden for unselected ones if there are 4 or 5 tabs in total. Thus it is not possible at the moment to force display of the labels for all tabs at the same time.

**Comment by roughike** [comment]
@Nolanus is right.

When all of the titles are shown and there's more than 3 items, on small devices the titles won't probably fit the screen and they would overlap.
