### ISSUE TITLE
Fragment doesn't instantiate in first run

### ISSUE THREAD

**Issue by krialix** [roughike/BottomBar#131]
I have an activity and a bottombar attached to it. It has 5 fragments but when I open the app it doesn't instantiate the first fragment. I have to click 2nd tab to instantiate it.

**Comment by roughike** [comment]
How does your Java code loo like and which version are you using?

**Comment by krialix** [comment]
I am using the version 1.3.1.

<pre>   @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);
        ButterKnife.bind(this);
        setSupportActionBar(mToolbar);

        mBottomBar = BottomBar.attachShy(mCoordinatorLayout, mFragmentContainer, savedInstanceState);

        mBottomBar.noNavBarGoodness();

        mBottomBar.setFragmentItems(getSupportFragmentManager(), R.id.container,
                new BottomBarFragment(TimeLineFragment.newInstance(), R.drawable.ic_home_black_24dp, "Home"),
                new BottomBarFragment(TimeLineFragment.newInstance(), R.drawable.ic_explore_black_24dp, "Explore"),
                new BottomBarFragment(TimeLineFragment.newInstance(), R.drawable.ic_menu_share, "Share"),
                new BottomBarFragment(TimeLineFragment.newInstance(), R.drawable.ic_people_black_24dp, "Friends"),
                new BottomBarFragment(TimeLineFragment.newInstance(), R.drawable.ic_person_black_24dp, "Profile"));
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mBottomBar.onSaveInstanceState(outState);
    }
</pre>

**Comment by roughike** [comment]
The ```setFragmentItems()``` method has been deprecated for a while. You should handle the Fragments by yourself now.

**Comment by TheJetlag** [comment]
Sorry, could you please explain how to handle fragments on my own?
Thanks

**Comment by EdvinM** [comment]
@zirkler if you have not fixed your issue by know, just add this code in onCreate method:
`bottomBar.setOnMenuTabClickListener(new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId)
            {
             }
@Override
            public void onMenuTabReSelected(@IdRes int menuItemId) {

            }
        });`
And in onMenuTabSelected you hande the fragments with fragmentmanager.
