### ISSUE TITLE
Images tint color

### ISSUE THREAD

**Issue by victordigio** [roughike/BottomBar#132]
Hi, I don't know how to achieve the same style than the first example of the library. I want all my icons dark grey, and the selected tab with another icon color. But the library doesn't keep my drawable original colors, and applies a soft grey tint for all of them. How can I set the images color for selected and unselected tabs?

**Comment by roughike** [comment]
How many tabs do you have?

**Comment by victordigio** [comment]
4 tabs. I don't want to change background color of the tabs, I only want my original images color, or to be able to set the images color programatically.

**Comment by chrjsorg** [comment]
I think thats a limitation in the Library itself. @roughike?

**Comment by roughike** [comment]
It's possible with the newest versions.

```java
mBottomBar.useFixedMode();
mBottomBar.setActiveTabColor("#FF0000");
```
