### ISSUE TITLE
Snackbar too high when transparent navigationbar and attachShy()

### ISSUE THREAD

**Issue by Nolanus** [roughike/BottomBar#140]
![device-2016-04-08-093042](https://cloud.githubusercontent.com/assets/3458616/14376884/9f7d461e-fd6c-11e5-9a03-3e205cdbbd24.png)

```
        <android.support.design.widget.FloatingActionButton
            android:id="@+id/activity_main_fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            android:layout_marginBottom="64dp"
            android:layout_marginRight="16dp"
            android:clickable="true"
            android:src="@drawable/my_drawable"
            app:fabSize="normal"
            app:layout_behavior="com.example.ui.component.BottomNavigationFloatingActionButtonBehavior"
            />
```

When the bottomBar is visible, the snackbar looks good.

**Comment by NikolaDespotoski** [comment]
@Nolanus @roughike Since it is not precised in the guidelines how bottom nav should behave when snackbar is shown, rather than snackbars being above bottom nav, I have deliberately made the snackbar not go above. Also there is another behavior which shows both snackbar and bb and hides bb when snackbar is dismissed if previously bb was hidden.

**Comment by Nolanus** [comment]
The "default" behavior of the SnackBar with translucent statusBar (inside a CoordinatorLayout) is to be shown above the navigation buttons. That doesn't look nice from my point of view, but it's this libraries task to fix that.
Therefore I suggest the additional height that is given to the SnackBar in _BottomNavigationWithSnackbar_ layout behavior should be reset while the BottomBar is hidden to restore the "default" behavior.

If a scrolling happens while the SnackBar is shown, it would be awesome if the height could be added again "on the fly", otherwise overlaying the SnackBar with the re-appearing BottomBar would be ok.

**Comment by roughike** [comment]
The BottomBar is now a regular View and should behave properly starting from 2.0 and up.

[See here for instructions for shy behavior](https://github.com/roughike/BottomBar#how-do-i-hide-it-automatically-on-scroll)

**Comment by vipulasri** [comment]
@roughike still same issue even after 2.0, I am using latest version i.e `2.0.2`
