### ISSUE TITLE
Fourth button behaving differently

### ISSUE THREAD

**Issue by ollie72** [roughike/BottomBar#142]
Screenshot shows some possible issues, I am posting together as not sure how related they are:

1. The badge doesn't fit and the top is cut off.
2. The fourth button behaves differently to the others (eg once highlighted it stays highlighted)
3. When buttons 1-3 are selected the other two move left/right under some circumstances
4. I can't see how to configure the bar so the labels are always visible (not a bug I think, is it possible?)

I'm adding the bottom bar using a menu resource:
```
bar = BottomBar.attachShy(coordinatorLayout, containerView, savedInstanceState);
bar.setItemsFromMenu(R.menu.menu_bottom_bar, ...)
bar.setTextAppearance(R.style.AppTextAppearanceLight);

```
![image](https://cloud.githubusercontent.com/assets/823913/14382148/8d9fff6a-fd83-11e5-971a-962b09f6c82f.png)

**Comment by roughike** [comment]
Fixed in the newest versions.
