### ISSUE TITLE
Badge rendering

### ISSUE THREAD

**Issue by ollie72** [roughike/BottomBar#143]
During testing as my badge count dropped to smaller numbers I started to see this rendering anomaly:

![image](https://cloud.githubusercontent.com/assets/823913/14384941/bc9fed7c-fd95-11e5-9736-ecc83a34f616.png)

**Comment by bpappin** [comment]
these appear to all be related: #178 #143 #139

**Comment by AbhishekM473** [comment]
For now you can do this...
mBottomBar.refreshDrawableState();
after you use the mBadge.setCount() method :)

**Comment by TostF** [comment]
@AbhishekM473 your fix is not working :C
My badges are eliptical like 90% of time.
