### ISSUE TITLE
Menu Item Text not centered

### ISSUE THREAD

**Issue by ngoa** [roughike/BottomBar#144]
If the test of the menu item wraps to second line, it is left aligned. The android:gravity tag should be set to center. 
Also I would love if there is a setter to set the maximum number of lines for the menu item. 
Below is the screenshot of the issue.
![Example Image](https://cloud.githubusercontent.com/assets/1719982/14394572/8570d92c-fd92-11e5-8262-d3e520d9f52c.png)

**Comment by roughike** [comment]
Yep, they should be relatively short to avoid that from happening. I'll fix the gravity in the next version, meanwhile you can use ```setTextAppearance()``` method to control the gravity yourself.

**Comment by ngoa** [comment]
Thanks.

**Comment by chrjsorg** [comment]
I have the same issue. I tried to set ellipsize/singleLine/maxLine to prevent the "new line" does not work.

**Comment by chrjsorg** [comment]
Ugly/hacky workaround:

```
private void fixBottomBarTextViews() {
        try {

            for (int i = 0; i < ((LinearLayout) ((FrameLayout) bottomBar.getBar()).getChildAt(0)).getChildCount(); i++) {
                LinearLayout linearLayout = ((LinearLayout) ((LinearLayout) ((FrameLayout) bottomBar.getBar()).getChildAt(0)).getChildAt(i));
                for (int j = 0; j < linearLayout.getChildCount(); j++) {
                    if (linearLayout.getChildAt(j) instanceof TextView) {
                        TextView textView = ((TextView) linearLayout.getChildAt(j));
                        textView.setEllipsize(TextUtils.TruncateAt.END);
                        textView.setMaxLines(1);
                    }
                }
            }
        }
        catch (ClassCastException | NullPointerException e) {
            Timber.e("FixBottomBarTextViews throw exception %s", e);
        }
    }

**Comment by SjoerdvGestel** [comment]
same issue :+1:

**Comment by ngoa** [comment]
@SjoerdvGestel  To your issue... I had the same and using the above code, I just change the gravity of the textView.

`textView.setGravity(Gravity.CENTER);`

**Comment by yombunker** [comment]
I'll be closing this issue because in the latest version the text it is properly center and according to the guidelines the text should NOT exceed to second line. If i have learn something from the time working on my last applications is that there is always a word in that language that will fit, is very very rarely that you can't find a replacement.
