### ISSUE TITLE
Newest version no longer supports fragments?

### ISSUE THREAD

**Issue by furfire1** [roughike/BottomBar#145]
The example app doesn't appear to use it's fragment class anymore.  When using the recently deprecated methods like setFragmentItems with the latest code, the initial page content is blank, and there's no way to set it.  Clicking on tabs afterwards still works.

Is this no longer going to support adding fragments to the bottom bar?

**Comment by roughike** [comment]
You'll have to manage Fragments by yourself. The ```setFragmentItems()``` has been deprecated for quite a while.
