### ISSUE TITLE
BottomBar hides when there is nothing to scroll

### ISSUE THREAD

**Issue by Nolanus** [roughike/BottomBar#147]
I've got a recyclerView which has no items yet. When performing the "scroll" gesture the bottombar hides, although nothing has been scrolled. This leaves the user with a confusing screen, where there is no element that can obviously be scrolled and no navigation (of course the user should still be able to remember that he tried to scroll a few moments ago).

I've found [this implementation](https://github.com/ianhanniballake/cheesesquare/blob/92bcf7c8b57459051424cd512a032c12d24a41b3/app/src/main/java/com/support/android/designlibdemo/ScrollAwareFABBehavior.java) of a layout_behavior for a floating action button. They take [_dyConsumed_ into account](https://github.com/ianhanniballake/cheesesquare/blob/92bcf7c8b57459051424cd512a032c12d24a41b3/app/src/main/java/com/support/android/designlibdemo/ScrollAwareFABBehavior.java#L43) for determining whether the content area has been scrolled to decide about hiding/showing the FAB.

I think a similar approach should be taken by the BottomBar.

**Comment by NikolaDespotoski** [comment]
@Nolanus Behavior you've mentioned is hiding the fab as soon as total consumed scrolled pixels is larger than FAB height. Therefore this does not corresponds with MD guidelines, where it states that bottombar should hide/show **_AS SOON AS_** content is scrolled.

**Comment by roughike** [comment]
Mr. Coordinator said it best. I think the same behavior happens with FABs too when there's no content.

It's your responsibility to disable nested scrolling when your scrolling view has no content.
