### ISSUE TITLE
Show/Hide BottomBar programmatically

### ISSUE THREAD

**Issue by Nolanus** [roughike/BottomBar#148]
Although it is possible to show/hide the bottomBar by applying the offset animation on my own, it would be nice to trigger that programmatically via the BottomBar class functions.

Possible use case: Another activity was opened which gets closed now. The activity with the BottomBar becomes active again and now shows different content (e.g. previously a list, but now less items as they have been "completed" in the other activity). The BottomBar is still outside the screen, as the user scrolled. Now it would be good to show the BottomBar again programmatically.

**Comment by NikolaDespotoski** [comment]
@roughike I'll fix this.

**Comment by roughike** [comment]
Now it's possible using the ```show()``` and ```hide()``` methods. A nice animation by @NikolaDespotoski appears when using with ```attachShy()``` inside a CoordinatorLayout.

**Comment by Nolanus** [comment]
Is it possible that something got interchanged? I need to call `mBottomBar.hide();` to get the bottomBar moved back into the view.
I guess that https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L1012 should be `!visible`.

**Comment by Sundin** [comment]
Have the show() and hide() methods been removed?
