### ISSUE TITLE
does it support vector

### ISSUE THREAD

**Issue by jjhesk** [roughike/BottomBar#149]
as mentioned

**Comment by IamTechknow** [comment]
Yes it does, at least on API 21+ and up. Not sure about support vector drawables, but you don't have to do anything special to make them work, just provide the correct resource ID

**Comment by Nolanus** [comment]
Support vector drawables worked with support library 23.2, however with the latest release 23.3 they [removed the support for vector drawables from resources](https://plus.google.com/+AndroidDevelopers/posts/iTDmFiGrVne) (like a menu resource).
However, you can use VectorDrawables in pre-lollipop devices using the latest support library as follows:

```
mBottomBar.setItems(new BottomBarTab(VectorDrawableCompat.create(getResources(), R.drawable.your_vector_drawable, getTheme()), R.string.myTitle), ... );
```

**Comment by roughike** [comment]
I think @IamTechknow and @Nolanus just solved this, so I'm closing this one. However, if you encounter problems with vector drawables, feel free to comment here.

**Comment by bestsoft-github** [comment]
I am having a problem with Vector resources.

I'm adding items to the BottomBar by doing:

BottomBarTab one = new BottomBarTab(VectorDrawableCompat.create(getResources(), R.drawable.myVector, getActivity().getTheme()), R.string.myTitle);
// same for two, three and four
mBottomBar.setItems(one, two, three, four);

On my Nexus 5X 6.0.1 everything's fine: http://imgur.com/d9ABlLc

But on my Nexus 7 2012 4.4.4 I'm getting this: http://imgur.com/XvUKwd0

Using appcompat-v7:23.4.0, the code above resides on the onCreateView() of a support Fragment.

Any idea what might be going on?

**Comment by sudansh** [comment]
This works but then how can I listen to menu click as we aren't providing any ID to it (as in xml)?

**Comment by Nolanus** [comment]
`OnTabClickListener#onTabSelected(int position)`provides the position of the tab that just got selected. You may set one using `mBottomBar.setOnTabClickListener()`.

See the Readme: https://github.com/roughike/BottomBar#i-dont-want-to-set-items-from-a-menu-resource
