### ISSUE TITLE
how does it support additional drawabled on the top of each tab

### ISSUE THREAD

**Issue by jjhesk** [roughike/BottomBar#150]
lets say i have some information need to populate on top the one tab that will able to show the number on it. are there any call backs or support that ican define it into the tab so that it can support whenever there is an update of the drawcall?

**Comment by roughike** [comment]
Do you mean [Badges](https://github.com/roughike/BottomBar#badges)?

**Comment by yombunker** [comment]
closing this because it sounds like the request is "badges" which are already implemented
