### ISSUE TITLE
setTypeface NPE

### ISSUE THREAD

**Issue by renegade037** [roughike/BottomBar#152]
Hello,

Got a NPE on 1.2.7 while trying to set a typeface, it works usually, probably was some race condition:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTypeface(android.graphics.Typeface)' on a null object reference
com.roughike.bottombar.BottomBar.setTypeFace (BottomBar.java:663)
```

Regards,
Milos

**Comment by roughike** [comment]
Probably fixed before, but at least in the 2.0 versions this shouldn't happen since the typefaces are set differently.
