### ISSUE TITLE
How can I set different image for a tab when it's selected & unselected?

### ISSUE THREAD

**Issue by zhou-jian** [roughike/BottomBar#153]
I want a normal image if a tab is selected & make it a different image (a gray one, and it's not the same as the normal one, so i can't just make it gray) if it is unselected, would this feature be considered supporting?

**Comment by NickM-27** [comment]
I am pretty sure in the guidelines that it says icons are supposed to be static and not changing so it is not confusing to the user.

**Comment by roughike** [comment]
I'm with @NickM-27 on this one. Changing the icon is could be confusing to the user, and it's not endorsed in the Guidelines.

I'm closing this one.

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
