### ISSUE TITLE
Images tint cannot be changed (Not on Fixed Mode)

### ISSUE THREAD

**Issue by ngoa** [roughike/BottomBar#155]
The images tint is currently set to white and there is no possibility for me to change the tint to any other color. If we wanted to use white background for one of the tabs then it would cause a problem since the text and tint are also white hence we cannot see them.

Would be nice to have this.

**Comment by roughike** [comment]
[With the latest version you can customize the tint color, alphas, whatever. ](https://github.com/roughike/BottomBar#all-customization-options)
