### ISSUE TITLE
Tabs not aligned vertically

### ISSUE THREAD

**Issue by victordigio** [roughike/BottomBar#156]
I'm not sure why, but I get a bottom padding inside bottom bar. Tabs are not centered vertically:

![sin titulo](https://cloud.githubusercontent.com/assets/15648001/14453368/ad9d437c-0094-11e6-86a9-25a77e8c3d50.png)

**Comment by NickM-27** [comment]
The selected tab is meant to be higher than all the others, this is part of the material design guidelines.

**Comment by victordigio** [comment]
I know... I'm not talking about the selected tab, I'm talking about the bottom padding inside the bottom bar.

**Comment by jonasdehovre** [comment]
I'd love to see this get fixed too..  👼

**Comment by roughike** [comment]
The tabs are centered properly in the newest versions starting from 2.0.

**Comment by Odaym** [comment]
Not if you remove the text on the tabs, the icons stay near the top and the place of the text is still taken up

**Comment by Odaym** [comment]
You can do this ugly line: `bottomBar.findViewById(R.id.bb_bottom_bar_item_container).setPadding(0, 0, 0, -40);`

until you find that the icons are now centered
