### ISSUE TITLE
Manually selecting tab: "old tab" is incorrectly sized

### ISSUE THREAD

**Issue by chrjsorg** [roughike/BottomBar#158]
I'm using `setDefaultTabPosition` before I add any items, which is fine.

I need to override the onBackPressed behavior a bit. (Switch the tabs until you reach the "end") So I have to manually select tabs on demand.

After calling `selectTabAtPosition` the previous tab is incorrectly sized.
http://i.imgur.com/qTx87nw.png

**Comment by NickM-27** [comment]
This happens to me whenever I call selectTabAtPosition regardless of default tab or not.

**Comment by chrjsorg** [comment]
@NickM-27 Workaround: `.noResizeGoodness()` which sets the tab width fixed

**Comment by Nolanus** [comment]
Similar to #120, so I guess some internal "magic" needs to be applied when using _setDefaultTabPosition_

**Comment by rocketspacer** [comment]
i'm having this problem too

**Comment by roughike** [comment]
No problems with the latest version.
