### ISSUE TITLE
Frist tab "selected" despite setDefaultTabPosition

### ISSUE THREAD

**Issue by Nolanus** [roughike/BottomBar#159]
BottomBar by default selects the first tab and calls the listener for that tab. When a default position is specified using _setDefaultTabPosition_, it first selects the first tab and then the specified default tab position.

One may work around this by first setting the items, then defining the default position and afterwards registering the listener:
```
mBottomBar.setItems(new BottomBarTab([...]), [...]);
mBottomBar.setDefaultTabPosition(2);
mBottomBar.setOnTabClickListener(new OnTabClickListener() { [...] });
```

However, this does not work when you're using the functionality to use a R.menu.* to inflate your bottom bar.

**Comment by chrjsorg** [comment]
You can call `.setDefaultTabPosition` right after attaching. Maybe this helps?

**Comment by Nolanus** [comment]
Looking at [the implementation](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L392) this will give me an error, as no items are specified at that time.

**Comment by chrjsorg** [comment]
Works for me like this:

```bottomBar = BottomBar.attachShy(coordinatorLayout, null, savedInstanceState);
    bottomBar.setDefaultTabPosition(2);
    bottomBar.setItemsFromMenu(R.menu.activity_main_bottombar, new OnMenuTabClickListener()..```

Maybe it's an issue with `.setItems`

**Comment by Nolanus** [comment]
Ok, no library issue. It's just the problem when calling "setDefaultTabPosition" after a listener has been attached. Then the listener will be called for the first tab once and then your "default tab". 
Should be fine when this gets pointed out in the documentation, because the other way round it works (as long as the first fragment doesn't throw an exception which was the case for me) but requires unnecessary creation of that first fragment. and may lead to undesired behavior depending on what the listeners does.
