### ISSUE TITLE
Item title aligment

### ISSUE THREAD

**Issue by SjoerdvGestel** [roughike/BottomBar#160]
I'm experiencing some issues with the alignment of item titles that are a bit to long,
they align at the top left, and setting a text appearance with center gravity wont change that.
any idea

**Comment by SjoerdvGestel** [comment]
![image](https://cloud.githubusercontent.com/assets/1597644/14496489/92ed4338-0193-11e6-9309-f48d880bd9f2.png)
nexus 4 on android 4.1.1

**Comment by chrjsorg** [comment]
Duplicate: https://github.com/roughike/BottomBar/issues/144

**Comment by yombunker** [comment]
this is working on the latest version
