### ISSUE TITLE
BottomBar with the Conductor library.

### ISSUE THREAD

**Issue by TheNattyDread** [roughike/BottomBar#162]
This is my Main Activity.

```
        setContentView(R.layout.activity_main);
        //mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar = BottomBar.attachShy((CoordinatorLayout) findViewById(R.id.coord_layout),
                findViewById(R.id.controller_container), savedInstanceState);
        //mBottomBar.noNavBarGoodness();
        mBottomBar.noTopOffset();
        mBottomBar.setItemsFromMenu(R.menu.bottombar_menu, this);
        mBottomBar.mapColorForTab(0, ContextCompat.getColor(this, R.color.colorAccent));
        mBottomBar.mapColorForTab(1, 0xFF5D4037);
        mBottomBar.mapColorForTab(2, "#7B1FA2");
        mBottomBar.mapColorForTab(3, "#FF5252");
        mBottomBar.mapColorForTab(4, "#FF9800");
        ButterKnife.bind(this);
        setSupportActionBar(mToolbar);

        mRouter = Conductor.attachRouter(this, mContainer, savedInstanceState);
        if (!mRouter.hasRootController()) {
            mRouter.setRoot(new HomeController());
        }
```

This is my layout file.

```
<android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/coord_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        tools:context="com.example.demo.MainActivity">

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/AppTheme.AppBarOverlay">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary"
                app:popupTheme="@style/AppTheme.PopupOverlay" />

        </android.support.design.widget.AppBarLayout>

        <com.bluelinelabs.conductor.ChangeHandlerFrameLayout
            android:id="@+id/controller_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            />

    </android.support.design.widget.CoordinatorLayout>
```

Whenever I attachShy, I get this.

![screenshot_20160416-111806](https://cloud.githubusercontent.com/assets/4837250/14581929/057f342a-03c8-11e6-854c-5237ad92b91b.png)

Whenever I attach(this, savedInstance), I get this.

![screenshot_20160416-111929](https://cloud.githubusercontent.com/assets/4837250/14581939/6c2cc61a-03c8-11e6-8d94-3263fabfe10d.png)

And attach(this, savedinstance) with no navbargoodness() :(, it works.
![screenshot_20160416-112036](https://cloud.githubusercontent.com/assets/4837250/14581950/acff089c-03c8-11e6-8f92-5263e3242d87.png)

All the above screenshots are from my Nexus 6. When I try is on by lollipop Blu phone,  attach(this, savedinstance) with no navbargoodness()....I get this space on the bottom for some options. This is normal.....

![screenshot_2016-04-16-11-23-22](https://cloud.githubusercontent.com/assets/4837250/14582064/f9834d36-03c8-11e6-99d9-ef741920dcb6.png)

This is not....
![screenshot_2016-04-16-11-23-00](https://cloud.githubusercontent.com/assets/4837250/14582081/202d48ce-03c9-11e6-992a-208140449974.png)

**Comment by TheNattyDread** [comment]
Here is the link to the [Conductor Library](https://github.com/bluelinelabs/Conductor). Cool library.

**Comment by yombunker** [comment]
Have you tried the latest version to see if the problem still persist? I'll be closing it for now, but, feel free to re-open if this is not working and we can evaluate if this is something that should be address by the library.
