### ISSUE TITLE
NavigationBar problem

### ISSUE THREAD

**Issue by FabianShallari** [roughike/BottomBar#163]
Im compiling the sample app on master and the transparent navigation bar tinting seems not to be working for me 😞 . 
When I set `<item name="android:windowTranslucentNavigation">true</item>` on my theme the bottom bar gets drawn behind the translucent navigation bar. Is there a specific way I'm supposed to use this?

**Comment by alvarlagerlof** [comment]
Are your tabs colored?

**Comment by Sultone** [comment]
Use this code  :
`boolean hasMenuKey = ViewConfiguration.get(this).hasPermanentMenuKey();
boolean hasBackKey = KeyCharacterMap.deviceHasKey(KeyEvent.KEYCODE_BACK);
if(!hasMenuKey && !hasBackKey) {((ViewGroup.MarginLayoutParams) mBottomBar.getLayoutParams()).bottomMargin += "NavigationBarHeight";}`

**Comment by mehrdaad** [comment]
@Sultone I'm facing this problem too. How should I use the snippet you provided above?
@FabianShallari  did you solve your problem?

**Comment by Sultone** [comment]
@mehrdaad Paste it just after having declared your bottombar, then replace "NavigationBarHeight" by a method which get the nav bottombar height. You have few exemples here : [http://stackoverflow.com/questions/20264268/how-to-get-height-and-width-of-navigation-bar-programmatically](url)
It will add a bottom margin for your bottombar if there is a navigationbar :)

**Comment by roughike** [comment]
This is now fixed in the latest versions. You can have ```app:bb_behavior="underNavbar"``` and the BottomBar will automatically calculate the correct size for itself. No more "magical" auto detection for that, as it was highly unreliable.
