### ISSUE TITLE
Multi activity mangement

### ISSUE THREAD

**Issue by mehrdaad** [roughike/BottomBar#164]
I know you can have one activity with several fragments, each fragment representing a different tab.  
But the problem starts from here that you want to add more fragment in each fragment and you end up in a situation where you have multiple nested and complicated fragments.  
Not to mention that life cycle management of fragments becomes a headache.  
I'm curious what's your approach in handling each tab for multiple activities?  
tnx

**Comment by mehrdaad** [comment]
anybody here?

**Comment by Nolanus** [comment]
Not sure what kind of answer you expect. The BottomBar is only a way to handle opening/replacing fragments in one activity. You're free to start a new activity when a bottomBar item gets pressed and in that new activity display the same bottomBar but different "main" content. But probably all animations bottomBar performs are "lost" then and depending on the OS "inter-activity" animation it will look good or worse.

**Comment by aixumm** [comment]
Use Fragment instead of Activity

**Comment by mehrdaad** [comment]
@Nolanus yeah that seems possible (using multi-Activity approach) but I'm anticipating code duplicates.
@aixumm Yeah that seems possible too (fragments instead of activity) but, That will make fragments inside a fragment. And the code maintainability time and effort will seriously go up.

**Comment by mehrdaad** [comment]
@Nolanus you suggested to use fragments inside activity. But this requires to have just one activity for many separate tasks. Is there any better way you have come?

**Comment by Nolanus** [comment]
If you separate the concerns it shouldn't matter whether an activity performs a task or a fragment (e.g. moving logic into helper classes that get injected into the fragment or the fragment depends on). It will just add an additional level in your hierarchy: 

```
application -> activity -> util/functional class
application -> activity -> fragment -> util/functional class
```
