### ISSUE TITLE
BottomBar height not 56dp

### ISSUE THREAD

**Issue by hpost** [roughike/BottomBar#168]
The height of the bottom bar should be **56dp** according to the [Material Design Specs](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-specs).
It is too high at the moment.

**Comment by deepti1408** [comment]
yes ! Is there any way to adjust the height of the bottom bar?

**Comment by dentrite** [comment]
+1

**Comment by deepti1408** [comment]
@dentrite yes. I ended up doing the same. Fetched BottomBar reference from getBar() method and had set the params.

**Comment by hpost** [comment]
@deepti1408 I tried setting the height of the view obtained from BottomBar#getBar, but then the labels below the tab icons are cut off. Did you do something else?

**Comment by coderlife** [comment]
@hpost  i have override the BB_BottomBarItem_Fixed style ,but it not take effect.
Is there anything else need to do?

**Comment by hpost** [comment]
@coderlife here's what I did:
```xml
<style name="BB_BottomBarItem_Fixed">
    <item name="android:background">?attr/selectableItemBackgroundBorderless</item>
    <item name="android:orientation">vertical</item>
    <item name="android:gravity">bottom|center_horizontal</item>
    <item name="android:layout_width">wrap_content</item>
    <item name="android:layout_height">56dp</item>
    <item name="android:paddingTop">8dp</item>
    <item name="android:paddingBottom">5dp</item>
    <item name="android:paddingLeft">12dp</item>
    <item name="android:paddingRight">12dp</item>
</style>
```

**Comment by coderlife** [comment]
@hpost thanks a lot.  It affect! 
but I found that when the icon's original height is over 24dp, it can't be adjust to meet material design guideline.  Do you know anything about this?

**Comment by hpost** [comment]
@coderlife I would suggest to use icons with dimensions of 24dp x 24dp. That will give you the best results.

**Comment by coderlife** [comment]
@hpost i see . thanks

**Comment by StefanoGR** [comment]
@hpost How to override the theme? If I add it to the app style, it doesn't do anything. Usually style is set in xml, not programmatically. Thx

**Comment by nsranjith** [comment]
will vary as per ur image icon
