### ISSUE TITLE
how to unselect tab programmatically

### ISSUE THREAD

**Issue by deepti1408** [roughike/BottomBar#169]
BottomBar has a method unselectTab method which is private. In my project i have a navigation drawer which has 15 sets of items, and bottom bar which has 5 among them. On selecting the item from navigation drawer , **which are not in the bottom bar** i would like to unselect the tabs from bottom bar. Currently there is no method to do so. I have tried selecting an out of range tab position , but it doesnt help. Please suggest

**Comment by SanPinto** [comment]
Even I'm facing the same issue.Not able to unselect the tabs from bottom bar. I tried selecting out of range value, but it didn't help. 

Please suggest

**Comment by deepti1408** [comment]
Can anyone suggest . Is it possible to unselect all or specific tab ?

**Comment by roughike** [comment]
There's no "unselected all" functionality planned for now.

**Comment by jcrooke** [comment]
I think this is needed too 👍
