### ISSUE TITLE
SearchView results obstructed by BottomBar

### ISSUE THREAD

**Issue by Andrew-Walker** [roughike/BottomBar#17]
I'm using a SearchView, and I noticed that the bar sits above the keyboard and covers up some of the search results. I've attached a screenshot:

![screenshot_2016-03-17-16-03-42](https://cloud.githubusercontent.com/assets/12536970/13854106/cfec77be-ec61-11e5-84b9-e522df963aa5.png)

**Comment by roughike** [comment]
I can't see the BottomBar there. Did you paint a gray layer over it to hide some top-secret company data visible in the tabs or should I go see an optician?

**Comment by Andrew-Walker** [comment]
It just happened to be pretty much the same colour as my background. Here's a more clear image:

![screenshot_2016-03-17-17-44-49](https://cloud.githubusercontent.com/assets/12536970/13855403/3b4c38b8-ec68-11e5-8d68-c6e839ac132e.png)

**Comment by roughike** [comment]
I still can't figure out what in that pic is BottomBar.

Is it the area between the search result (where the black background ends) and the keyboard?

**Comment by Andrew-Walker** [comment]
Yeah, that's correct. I double checked that it is definitely the BottomBar by removing it and re-adding.

**Comment by roughike** [comment]
Got it. I'll try to replicate the bug and fix it.

**Comment by Andrew-Walker** [comment]
Great, thanks!

**Comment by Andrew-Walker** [comment]
I'm not sure when this was fixed, but it's not an issue now. The bar still shows above the keyboard, but it's not missing it's contents like the older version did.

Keep up the great work!

**Comment by roughike** [comment]
Nice to hear! I'm really glad you like it and got your issue fixed.
