### ISSUE TITLE
how to deal with this

### ISSUE THREAD

**Issue by drduan** [roughike/BottomBar#171]
[
![4 -20-2016 18-39-19](https://cloud.githubusercontent.com/assets/7875572/14671949/4d8b45ee-0727-11e6-9e8a-8cdf881938f5.gif)
](url)

like this

**Comment by Nolanus** [comment]
Please provide some additional information what your problem is about.

**Comment by drduan** [comment]
icon is smaller

**Comment by roughike** [comment]
[Refer to the README](https://github.com/roughike/BottomBar#creating-the-icons) for creating the icons. If the BottomBar is still too large to contain your stuff, just give it more height in your XML layout.
