### ISSUE TITLE
show text when in tablet mode?

### ISSUE THREAD

**Issue by stay4cold** [roughike/BottomBar#174]
I'm not finding the function of set show text or not in tablet mode?

**Comment by Nolanus** [comment]
According to [material design guidelines](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-usage), in tablet mode no text is visible (at least on the screenshot there is none). Additionally I don't really know where to show it, as only short or small in font-size labels will fit below the icons without enlarging the "bar's width".

**Comment by roughike** [comment]
Unfortunately, I'm not going to support showing titles on tablets when using the tablet layout with this library.
