### ISSUE TITLE
About setting visibility of bottombar

### ISSUE THREAD

**Issue by hellsayenci** [roughike/BottomBar#175]
Hi,

Thanks for this awesome lib. I just have a problem when trying to hide bottombar. Because of some input problems in my fragment (adjustResize) I wanted to hide bottombar when user interacs with the keyboard. Anyway when I set bottombar's visibility to gone my whole layout was gone because of I am attaching bottombar to my content layout in drawer layout. You guys got any advice for me? Thank you

**Comment by Nolanus** [comment]
The BottomBar offers [hide()](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L419) and [show()](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L426) methods. However, I think they are mismatched at the moment, see https://github.com/roughike/BottomBar/issues/148#issuecomment-212342783

**Comment by roughike** [comment]
Now you can show / hide the BottomBar just like any other View.
