### ISSUE TITLE
Toast showing on onLongClick Listener

### ISSUE THREAD

**Issue by sarang1996** [roughike/BottomBar#176]
I want to disable toast on longClick on any tab any ideas how to implement it?

**Comment by shaunkawano** [comment]
I thought maybe it would be great for us to `setOnLongSelectedTab` listener or some sort to handle when the tab is long clicked (or `onMenuTabLongSelected` if we try to keep the name space consistent in `OnMenuTabClickListener`), but what do you think @roughike ?

**Comment by sarang1996** [comment]
but can you please add a property to disable a toast? @shaunkawano @roughike

**Comment by shaunkawano** [comment]
@sarang1996 Instead of providing property, I have thought having an option to set listener and do whatever users want to do when tab is long clicked is somehow nicer, but what do you guys think? (In my PR above I have done this)

**Comment by sarang1996** [comment]
yeh its cool but he had added default listener method so if you override long clicked, default must be called then our method is called. @shaunkawano

**Comment by shaunkawano** [comment]
@sarang1996 Can you possibly indicate where the author's default listener is? I thought in my PR I have re-written the author's listener in here: https://github.com/roughike/BottomBar/pull/297/files#diff-8ec355181975d7353e57af74c71a8fceL1197

**Comment by yombunker** [comment]
@roughike is there a reason behind the Toast when the long click occurs?

**Comment by roughike** [comment]
The reason was originally to mimic the behavior of ActionBar. If you don't know what some icon stands for, you could long-press that. There probably should be an option for the users to decide if they want this feature or not though.

**Comment by roughike** [comment]
This can be controlled in the next release.

[See here](https://github.com/roughike/BottomBar/commit/b7e82e4650ff952491fa90080e4736bed07d3fe7)

**Comment by yombunker** [comment]
@roughike are you sure you want to just have a boolean? there's already a PR to add a longclicklistener the same way as the other 3 listeners

**Comment by roughike** [comment]
@yombunker What way would you have in mind? Having the toasts on by default, but overriden when a new onlonglicklistener is set?

**Comment by yombunker** [comment]
@roughike lets have this discussion on the PR comments :)
