### ISSUE TITLE
 Is there any way to adjust the height of the bottom bar?

### ISSUE THREAD

**Issue by leguang** [roughike/BottomBar#177]
In my App, the height of the bottom bar is too high. Is there any way to adjust the height of the bottom bar?

**Comment by hpost** [comment]
See #168

**Comment by roughike** [comment]
With the newest version this is easy. Just set the ```layout_height``` attribute to whatever you want.

**Comment by bharat1012** [comment]
in Bottombar class comment this method..resizeForDrawingUnderNavbar() your problem is solve...it
  protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
        super.onLayout(changed, left, top, right, bottom);

        if (changed) {
            updateTitleBottomPadding();

            if (isShy()) {
                initializeShyBehavior();
            }

            if (drawUnderNav()) {
               // resizeForDrawingUnderNavbar();
            }
        }
    }
