### ISSUE TITLE
A problem when I add Badges

### ISSUE THREAD

**Issue by Tower-Ye** [roughike/BottomBar#178]
I‘m not sure it's a bug or i used wrong way when I add badges.For example,i select Favorate first,then i select Food, the Favorate hasn't changed its state,then no matter select which menu, the Food will be keep the selected state all the time,and if select Food again ,the bg color won't turning to Food bg color,others can be.
I run the code again,and i find only when tabPosition=0,will cause the problem.
> code:BottomBarBadge unreadMessages = mBottomBar.makeBadgeForTabAt(0, "#FF0000", 13);

![screenshot_2016-04-26-15-04-44](https://cloud.githubusercontent.com/assets/18652326/14809949/0595c99e-0bc3-11e6-927a-c9828c38c0bd.png)
![screenshot_2016-04-26-15-18-42](https://cloud.githubusercontent.com/assets/18652326/14809950/088d4550-0bc3-11e6-86c3-45525a1a88fb.png)

**Comment by bpappin** [comment]
these appear to all be related: #178 #143 #139

**Comment by roughike** [comment]
Should have been fixed a long ago.
