### ISSUE TITLE
Fragments Transitions

### ISSUE THREAD

**Issue by miguelbronzovic** [roughike/BottomBar#181]
Hi could you provide an example or a mechanism as part of the library to transition between fragment tabs?
As Android's Material Design guidelines describes the transition needs to be a **cross fade animation** and not a swiping transition like the _viewpager_.
In case is already supporting, could add an example on the **readme**?
Thanks

**Comment by roughike** [comment]
[Duplicate, see 18](https://github.com/roughike/BottomBar/issues/18)
