### ISSUE TITLE
the bottom of my RecyclerView can't be seen by user because of Bottombar

### ISSUE THREAD

**Issue by coderlife** [roughike/BottomBar#182]
is the any way to let my recyclerview shown above the bottombar or hide the buttombar while scrolling?

**Comment by PsyGik** [comment]
`mBottomBar = BottomBar.attachShy((CoordinatorLayout) findViewById(R.id.coordinator_layout),
                findViewById(R.id.recycler_view), savedInstanceState);
`

**Comment by roughike** [comment]
Use the "shy" behavior as PsyGik described above.

On the 2.0 versions and up, see the README how to do it.

**Comment by LOG-TAG** [comment]
updated my old project to 2.0  up  , how to change this following code cc @PsyGik 
`mBottomBar=BottomBar.attachShy((CoordinatorLayout)findViewById(R.id.coordinator_layout),findViewById(R.id.recycler_view), savedInstanceState);`

by just adding app:bb_behavior="shy" ??

**Comment by roughike** [comment]
See the README.

https://github.com/roughike/BottomBar#how-do-i-hide-it-automatically-on-scroll
