### ISSUE TITLE
ChildFragmentManager question

### ISSUE THREAD

**Issue by PingForward** [roughike/BottomBar#183]
Hi
is this lib work with fragments??

And can I manage it like this way?
I have a fragment with layout

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <include layout="@layout/layout_toolbar" />

    <FrameLayout
        android:id="@+id/fragment"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/black" />

    <LinearLayout
        android:id="@+id/llTabHost"
        android:layout_width="match_parent"
        android:layout_height="56dp"
        android:orientation="horizontal">

    </LinearLayout>
</LinearLayout>
```

Then I init bar
`bottomBar = BottomBar.attach(rootView.findViewById(R.id.llTabHost), savedInstanceState);`
add items and change fragment on tab listener

```
        getChildFragmentManager()
                        .beginTransaction()
                        .add(R.id.fragment, Fragment.newInstance())
                        .commit();
```

Bar is visible and it seems the fragment added some where but it is not showing in the fragment container. Any suggestions?

**Comment by PingForward** [comment]
Sorry it seems I found what's wrong
I just need to set container on attach method not rootView
```
  View rootView = inflater.inflate(R.layout.fragment_shift_tabs, container, false);
   bottomBar = BottomBar.attach(container, savedInstanceState);
```

**Comment by PingForward** [comment]
No, it added to my activity instead fragment

**Comment by PsyGik** [comment]
Yes it works with Fragments. 
You need not specify the `LinearLayout (@+id/llTabHost)` in the XML just for the BottomBar.
In your Activity,
```
mBottomBar = BottomBar.attach(this, savedInstanceState);
```
then add a listener to the BottomBar like so, and update the fragments
```
        mBottomBar.setOnTabClickListener(new OnTabClickListener() {
            @Override
            public void onTabSelected(int position) {
                switch (position){
                    case 0:
                    getSupportFragmentManager().beginTransaction().replace(R.id.fragment,MyFragment.newInstance()).commit();
                   
                    break;
                }
            }
            @Override
            public void onTabReSelected(int position) {

            }
        });
```

**Comment by PingForward** [comment]
@PsyGik It will work but not as expected. I have one activity and stack of fragments in it and only one fragment should have the bottomBar. When I popBack fragment with bottomBar I expect that the bottomBar will be destroyed with the fragment but it attached to my activity.

**Comment by PsyGik** [comment]
@PingForward, I'm sorry I misread your original query. I get it now. You want the BottomBar to be in a single Fragment. Try this in your Fragment's `OnCreate`
```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View view = inflater.inflate(R.layout.my_fragment_layout, container, false);
    initViews(view);

    BottomBar bottomBar = BottomBar.attach(view, savedInstanceState);
    bottomBar.setItems(
        new BottomBarTab(R.drawable.ic_recents, "Recents"),
        new BottomBarTab(R.drawable.ic_favorites, "Favorites"),
        new BottomBarTab(R.drawable.ic_nearby, "Nearby")
    );

    return bottomBar;
}
```

**Comment by PingForward** [comment]
@PsyGik thanks! Works now.

**Comment by PsyGik** [comment]
Happy to help! Have fun coding! 💻

**Comment by brunochichava** [comment]
Hi!

First of all thank you for this awesome library.

Im following this particular issue, about using fragments in BottomBar, i followed the code you posted:

`mBottomBar.setOnTabClickListener(new OnTabClickListener() {
            @Override
            public void onTabSelected(int position) {
                switch (position){
                    case 0:
                    getSupportFragmentManager().beginTransaction().replace(R.id.fragment,MyFragment.newInstance()).commit();

                    break;
                }
            }
            @Override
            public void onTabReSelected(int position) {

            }
        });`

But im having an erros on this method: `newInstance()`

**Comment by PsyGik** [comment]
@brunochichava, that is just a Fragment factory method. Nothing to do with this library.

**Comment by ArunPandiyan** [comment]
I have a same issue here.A activity opens the a fragment based on navigationview. then that fragment is having the BottomBar, but earlier i was returning the rootview of fragment(which failed in IllegalStateException ). then on seeing this one i changed to returning the buttonbar, but now the listeners for button bar is not working.

**Comment by ArunPandiyan** [comment]
I got i cleared the above error. by populating the items from xml. It always got returning -1 when adding inside the code.
