### ISSUE TITLE
Too sensitive to hide / show

### ISSUE THREAD

**Issue by xizzhu** [roughike/BottomBar#184]
It's too sensitive that any scrolling will hide / show the bottom bar, is it possible to add some buffer, e.g. scroll at least 4 px before hiding / showing?

**Comment by NikolaDespotoski** [comment]
@xizzhu Yes, thats possible, but the MD guidelines do not specify such buffer, contrary it says that it suppose to hide **as soon as** user scrolls down and shows up **as soon as** user scrolls up.
