### ISSUE TITLE
Support for API level 8

### ISSUE THREAD

**Issue by tarolechaitanya** [roughike/BottomBar#186]
Hi !!!
Can you provide support for API level 8 ?

**Comment by NikolaDespotoski** [comment]
@tarolechaitanya If you look at API [distribution](http://developer.android.com/about/dashboards/index.html)  API 8 has 0.1% share. It's not worth the effort man. `minSdk=14` or `minSdk=16` ;)

**Comment by Aeiric** [comment]
@NikolaDespotoski Hello，I am blocked by a question which you mentioned at statckoverfow http://stackoverflow.com/questions/26697054/retrofit-how-to-send-a-post-request-with-constant-fields,can you give a demo ,thanks a lot~~~

**Comment by yombunker** [comment]
as @NikolaDespotoski said, this is not worth the effort. Even in Microsoft teams we only support 19 and above.
