### ISSUE TITLE
Scrolling Behaviour of BottomBar for Empty Views

### ISSUE THREAD

**Issue by PsyGik** [roughike/BottomBar#187]
If the RecyclerView (or any other scrolling view for that matter) is empty, then the BottomBar should not Hide. 
![device-2016-04-28-132811](https://cloud.githubusercontent.com/assets/5432911/14879253/b542f366-0d45-11e6-9c6e-3710bbb6c9d0.gif)

**Comment by mehrdaad** [comment]
This is not a problem related to bottom bar. set this method on your ``recyclerView`` and it will be solved.  ``        recyclerView.setNestedScrollingEnabled(false);
``
this methods means that the ``recyclerView `` will not get scrolling gestures so the container will manage it.
