### ISSUE TITLE
Shadow related issue when used in combination with MaterialDrawer

### ISSUE THREAD

**Issue by Discover-** [roughike/BottomBar#188]
I'm working on an app where there's both a drawer and a bottom menu for navigation. The bottom navigation only has 4 items (8 for tablets) at most, while the drawer has all the remaining navigation items. If there's more than X items (4 or 8), the bottom navigation is never initialized and there'll only be a drawer menu.

For the drawer I'm using this library by @mikepenz: https://github.com/mikepenz/MaterialDrawer.

There seems to be an issue when opening the drawer on a device with API > 15 (works on 15), the fragment that disappears behind the opening drawer doesn't properly get 'shadowed' (not sure how to explain what happens). Instead, the elements and toolbar and all that are staying the same color while the background of the fragment will properly turn to a darker color. Disabling the bottom navigation bar solves this issue.

A few screenshots to explain what I'm talking about:

Here's a Moto G running API 22. The bottom navigation is **disabled** here:
http://i.imgur.com/8ih0m9p.png

Here's the same phone with the bottom navigation **enabled**:
http://i.imgur.com/lddg7P5.png

So in the first screenshot you can see that the drawer works as expected. Enabling the bottom navigation somehow breaks this.

This issue also exists on my Samsung Tab A running API 21.
This issue **does not** exist on my HTC Incredible A running API 15.

I understand this is not of great concern here at all considering I'm using two 3rd party libs in combination with each other that are not meant to be used at the same time (or at least not designed to). Any advise is therefore appreciated. :smile:

**Comment by PsyGik** [comment]
Care to share your layout and how you've attached the BottomBar? I'd be easy to debug.

**Comment by Discover-** [comment]
Of course. Here's the code to attach the BottomBar:
```

    private List<BottomBarTab> bottomBarItems = new ArrayList<>();
    private List<IDrawerItem> drawerItems = new ArrayList<>();
    bottomBarItems.add(new BottomBarTab(R.drawable.ic_home_black_24dp, "Test 1"));
    bottomBarItems.add(new BottomBarTab(R.drawable.ic_home_black_24dp, "Test 2"));
    drawerItems.add(new PrimaryDrawerItem().withIcon(R.drawable.ic_home_black_24dp).withName("Test 1"));
    drawerItems.add(new PrimaryDrawerItem().withIcon(R.drawable.ic_home_black_24dp).withName("Test 2"));
...etc.

    private void initializeBottomNavigationBar(Bundle savedInstanceState) {
        if (bottomBarItems == null || bottomBarItems.size() == 0) {
            return;
        }

        setupBottomNavBar = true;

        bottomNavBar = BottomBar.attach(this, savedInstanceState);

        //bottomNavBar.noResizeGoodness();
        bottomNavBar.useFixedMode(); //! This turns the bar white and makes it always display text
        bottomNavBar.useOnlyStatusBarTopOffset(); //! This removes white top padding at toolbar, but leaves space FOR toolbar which is exactly what we need
        bottomNavBar.noTabletGoodness(); //@todo make this an API option

        //! All calls should be BEFORE setItems
        bottomNavBar.setItems(bottomBarItems.toArray(new BottomBarTab[bottomBarItems.size()]));

        bottomNavBar.setOnTabClickListener(new OnTabClickListener() {
            @Override
            public void onTabSelected(int position) {
                if (bottomNavBarIgnoreSelections) {
                    return;
                }

                openFragmentForPosition(position);

                if (drawer != null) {
                    drawerIgnoreSelections = true;
                    drawer.setSelectionAtPosition(position + 1);
                    drawerIgnoreSelections = false;
                }
            }

            @Override
            public void onTabReSelected(int position) {

            }
        });
    }

```
And here's the code to generate the drawer:
```
    private void initializeDrawerMenu() {
        if (drawerItems == null || drawerItems.size() == 0) {
            return;
        }

        AccountHeader header = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.drawer_header)
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile iProfile, boolean b) {
                        return false;
                    }
                })
                .withOnAccountHeaderSelectionViewClickListener(new AccountHeader.OnAccountHeaderSelectionViewClickListener() {
                    @Override
                    public boolean onClick(View view, IProfile iProfile) {
                        return false;
                    }
                })
                .build();

        drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(header)
                .withDrawerItems(drawerItems)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, final IDrawerItem drawerItem) {
                        if (position == 0 || drawerIgnoreSelections) {
                            return true;
                        }

                        //! Means a sticky footer item was selected
                        if (position == -1) {
                            if (drawerItem.getIdentifier() == SETTINGS_IDENTIFIER) {
                                drawer.closeDrawer();
                                startActivity(new Intent(MainActivity.this, SettingsActivity.class));
                            }
                            else if (drawerItem.getIdentifier() == ABOUTAPP_IDENTIFIER) {
                                showAboutAppDialog();
                                //! Don't close drawer for a dialog
                            }

                            return true;
                        }

                        drawer.closeDrawer();
                        openFragmentForPosition(position - 1);

                        if (setupBottomNavBar) {
                            bottomNavBarIgnoreSelections = true;
                            bottomNavBar.selectTabAtPosition(position - 1, true);
                            bottomNavBarIgnoreSelections = false;
                        }

                        return true;
                    }
                }).build();

        drawer.addStickyFooterItem(new PrimaryDrawerItem().withIcon(R.drawable.ic_info_outline_black_24dp).withSelectable(false).withIdentifier(ABOUTAPP_IDENTIFIER).withName("Over deze app"));
        drawer.addStickyFooterItem(new PrimaryDrawerItem().withIcon(R.drawable.ic_settings_black_24dp).withSelectable(false).withIdentifier(SETTINGS_IDENTIFIER).withName("Instellingen"));

        drawer.setSelectionAtPosition(currentFragmentPosition + 1);
    }
```



This should do most of it.

**Comment by PsyGik** [comment]
Can you test this? Instead of
```
 bottomNavBar = BottomBar.attach(this, savedInstanceState);
```
use
```
 bottomNavBar = BottomBar.attach(findViewById(R.id.fragmentContainer), savedInstanceState);
```

**Comment by Discover-** [comment]
Thanks for the suggestion. It does solve the shadow issue when opening my drawer, but after attaching the bottom drawer like this there's no more content displayed in the fragment container.

**Comment by PsyGik** [comment]
Can you share your layout?

**Comment by Discover-** [comment]
None of the fragments work, but this is the one displayed in the screenshots in my original post:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto" >

    <android.support.v4.widget.SwipeRefreshLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/swipe_refresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:scrollbars="vertical"
            android:paddingBottom="8dp"
            android:clipToPadding="false"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </android.support.v4.widget.SwipeRefreshLayout>
</RelativeLayout>
```

Then I use a Fragment class along with an adapter for the recyclerview to populate and style the items in the recyclerview. Do you need those too?

**Comment by PsyGik** [comment]
Okay, so instead of attaching the FrameLayout (container), give an id to the root LinearLayout and attach that instead.

**Comment by Discover-** [comment]
Tried it. The fragments do appear again now, but the original issue is back as well.

**Comment by PsyGik** [comment]
Just a shot in the dark, what is the sequence in which you initialise? Drawer first and then BottomBar or the other way around?

**Comment by Discover-** [comment]
Valid point. First I initialize the bottom bar and then the drawer.

I tried changing tried them around just now, sadly didn't change anything. :cry:

**Comment by mikepenz** [comment]
@Discover- hmm the `shadow` normally comes from the `DrawerLayout` and is defined via the `ScimColor` it is implemented in the `DrawerLayout` from the support libraries. Sot his is all original functionality. 

I see the `BottomBar` also has some auto attach functionality. as the `MaterialDrawer` does by default. By default it will directly inflate into the root of the view, and have everything wihin it's `DrawerLayout`

**Comment by Discover-** [comment]
Thanks for the follow-up. I assume you meant `ScrimColor`?

I am not too familiar with either of the libraries' codebase, but after some digging it seems as if this is related to the status bar. Both libraries are doing something with the status bar, and knowing that this bug does not exist on API 15 where it's not possible to tamper with the status bar, I think that's where the origin is.

I tried disabling the `useOnlyStatusbarOffset` call to the BottomBar but it didn't change anything, sadly.

Any idea's on what else we could try?

**Comment by PsyGik** [comment]
@Discover- , I'm just [pushing a demo app](https://github.com/PsyGik/DrawerWithBottomBar) which has both the BottomBar and Navigation Drawer along with Fragments. Can you test that and confirm if the result is what you're expecting?

**Comment by Discover-** [comment]
@PsyGik thanks! The issue does indeed exist on there as well. I changed the fragment_blank.xml to contain a cardview because the background of the view **does** properly change when the drawer is opened, unlike the actionbar/bottombar/sub-views. Here's my new layout:
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="16dp"
    tools:context="example.com.drawerwithbottombar.BlankFragment">

    <android.support.v7.widget.CardView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/cv_article"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginTop="8dp"
        android:layout_marginBottom="2dp"
        android:foreground="?selectableItemBackground"
        app:cardCornerRadius="2dp"
        app:cardElevation="2dp"
        app:cardPreventCornerOverlap="false"
        app:contentPadding="0dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <ImageView
                android:id="@+id/article_img"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:minHeight="360dp"
                android:src="@mipmap/ic_launcher"
                android:adjustViewBounds="true"/>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_margin="8dp"
                android:orientation="vertical">
                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:orientation="horizontal">
                    <TextView
                        android:id="@+id/txt_article_category"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textSize="13sp"
                        android:visibility="gone"
                        android:textColor="@color/primary"
                        android:text="Bla | Bla | Bla"/>
                    <TextView
                        android:id="@+id/txt_article_date"
                        android:layout_width="match_parent"
                        android:gravity="right"
                        android:textSize="13sp"
                        android:layout_height="wrap_content"
                        android:textColor="@color/primary"
                        android:text="26 feb. 2016"/>
                </LinearLayout>

                <TextView
                    android:id="@+id/txt_article_title"
                    android:layout_marginTop="4dp"
                    android:textColor="@android:color/black"
                    android:textStyle="bold"
                    android:textSize="21sp"
                    android:maxLines="5"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="Bla bla bla bla bla bla bla bla bla bla bla bla bla bla"/>
            </LinearLayout>
        </LinearLayout>
    </android.support.v7.widget.CardView>

</FrameLayout>
```

Here's a screenshot of how the app looks on my Moto G (API 22):
http://i.imgur.com/dpnx6ls.png

If you look closely you can see the cardview's right side next to the drawer and it's the same color it would normally be. Same goes for the bottom bar.

**Comment by Discover-** [comment]
I've also tried disabling the translucent statusbar for the MaterialDrawer. Didn't fix the issue.

**Comment by PsyGik** [comment]
Yes understood. I pushed another fix to the repo. On my device API 22 it looks like this,
![device-2016-04-29-155521](https://cloud.githubusercontent.com/assets/5432911/14913761/dea7baec-0e22-11e6-8c8c-770d6177cc97.png)

I'm guessing this is the expected result?

**Comment by mikepenz** [comment]
@PsyGik oh so you use the drawer with an `ActionBar` now or with a different container so it's below the `Toolbar`?
Shouldn't be like this if we want to follow the guidelines. 

I can also have a look at the sample repo later today after I come home

**Comment by Discover-** [comment]
@PsyGik your repository actually does indeed give the expected results! Going to investigate how to port this now, I think this does mean the issue is Toolbar-related somehow but I'm not sure yet. Will report back.

**Comment by PsyGik** [comment]
@Discover- , I don't think it is related to Toolbar. Check out [this commit](https://github.com/PsyGik/DrawerWithBottomBar/tree/72f98ee37a625e4db3d804ed8d16bec25ff5600f). The resulting screen is like this, 
![device-2016-04-29-160910](https://cloud.githubusercontent.com/assets/5432911/14914061/bfa28a12-0e24-11e6-97cd-4bcb1edb73d1.png)

**Comment by PsyGik** [comment]
@mikepenz , I wasn't really thinking about the guidelines when making that demo 😜

**Comment by Discover-** [comment]
So the issue got fixed by https://github.com/PsyGik/DrawerWithBottomBar/commit/0849c2eb78d31c693f8f51df80f8f006e5c76d50 (made sure to try reverting 1 by 1). Which means that your initial idea with the .attach() is indeed the cause of the issue, but implementing this in my own app somehow does not solve the issue for me.

I tried changing your demo project's activity_main.xml layout to the exact same of mine and it still works on the demo project, unlike my own app. I tried to get rid of these style properties without any change:
```
    <style name="AlphaActionBar" parent="@style/ThemeOverlay.AppCompat.Dark.ActionBar">
        <item name="android:windowActionBarOverlay">true</item>
        <item name="windowActionBarOverlay">true</item>
    </style>

    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />
    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />
```
(I also use a nested scrollview with a collapsing toolbar, hence)

I also tried syncing our styles entirely. Also tried adding `supportsRtl` (same as your demo project). I tried to use your exact layout (`fragment_blank.xml`) in one of my fragments without any luck (I thought maybe because it was using a FrameLayout).

Also tried to get rid of the `theme` and `popupTheme` for my toolbars, didn't change anything either.
```
    local:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
    local:popupTheme="@style/ThemeOverlay.AppCompat.Light"
```

I'm starting to run out of idea's on what to try. I can send my own project (preferably private) if you want to give it a try?

**Comment by PsyGik** [comment]
@Discover- , As long as you're okay sending the project. I can build and test it locally and report back to you if I find anything.

**Comment by Discover-** [comment]
@PsyGik: That'd be great. I will message you on Facebook!

**Comment by PsyGik** [comment]
@Discover- Cool. You can find me with the same username there

**Comment by Discover-** [comment]
@PsyGik: Did you get my message?

**Comment by PsyGik** [comment]
@Discover- , Yes I did. Let's continue the discussion there. I guess you could close this issue for now

**Comment by Discover-** [comment]
PsyGik has found the solution to this issue! :smile: 

@mikepenz maybe it's interesting for you to know where the origin of the issue is.

In my activity_main there was a LinearLayout (root) containing a toolbar (included layout file) and a FrameLayout. Since the root layout's orientation was set to vertical, they were stacked vertically by default. Apparently the root layout (Linear) was the issue because changing it to a RelativeLayout fixed the issue, but **only** if you also attach the bottom bar directly to the FrameLayout (see https://github.com/roughike/BottomBar/issues/188#issuecomment-215645236).

Changing it to a RelativeLayout where you put the FrameLayout below the toolbar using **layout_below** doesn't work for some reason. If you have this issue, use marginTop with a value of **?attr/actionBarSize** instead (56dp usually). Then you'll have to find a hack around the same padding issue that exists, but instead comes from the bottom. The bottom bar is typically also 56dp if the guidelines are followed.

I don't think we should close this issue because it is a bug. All we did is find a workaround.

Thanks to @PsyGik for figuring out a solution to the issue. All credits go to him! :+1:

**Comment by mikepenz** [comment]
@Discover- thank you for the information.

**Comment by Discover-** [comment]
I had to revert the fix from yesterday because it ended up giving more issues on API 15. Before this, API 15 worked fine but with the latest fixes explained in my last comment, the navigation bar often disappears behind the fragment and the elevation goes missing too because it's overwritten.

**Comment by alexbeville** [comment]
Hi, 

Before all, thanks for this amazing library.

I'm facing the issue with a classical DrawerLayout/NavigationView

I have an activity with this layout : 

`<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".activities.MainNavigationActivity">
    <FrameLayout
        android:id="@+id/fragmentContent"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>


    <android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:fitsSystemWindows="true"
        app:headerLayout="@layout/nav_header"
        app:menu="@menu/nav_menu" />

</android.support.v4.widget.DrawerLayout>`

In this activity, I'm loading the bottombar like this : 

`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_navigation);


        NavigationView navigationView = (NavigationView) findViewById(R.id.nav_view);
        navigationView.setNavigationItemSelectedListener(this);
        BottomBar mBottomBar = BottomBar.attach(findViewById(R.id.fragmentContent), savedInstanceState); //findViewById(R.id.main_content)
        mBottomBar.useFixedMode();
        mBottomBar.noTopOffset();
        // Use custom text appearance in tab titles.
        mBottomBar.setTextAppearance(R.style.BottomBarLabelInactive);

        mBottomBar.setItems(R.menu.bottom_nav_menu);
        mBottomBar.setActiveTabColor(ContextCompat.getColor(this,R.color.red_color));
        mBottomBar.setOnMenuTabClickListener(new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId) {
                switch (menuItemId){
                    case R.id.one :
                        loadFragment(new FragmentOne());
                        break;
                    case R.id.two :
                        loadFragment(new FragmentTwo());
                        break;
                    case R.id.three :
                        loadFragment(new FragmentThree());
                        break;
                    case R.id.four :
                        loadFragment(new FragmentFour());
                        break;
                }
                Log.d("MainActivity","onMenuTabSelected "+menuItemId);
            }

            @Override
            public void onMenuTabReSelected(@IdRes int menuItemId) {

            }
        });
    }`

And one of my fragment (for the moment, only FragmentOne is completed) :

`<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".fragments.FragmentOne"
    >

    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingTop="@dimen/appbar_padding_top"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:popupTheme="@style/AppTheme.PopupOverlay">

        </android.support.v7.widget.Toolbar>

        <android.support.design.widget.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </android.support.design.widget.AppBarLayout>

    <android.support.v4.view.ViewPager
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="end|bottom"
        android:layout_margin="@dimen/fab_margin"
        android:src="@drawable/ic_action_add" />
</android.support.design.widget.CoordinatorLayout>
`

The result is always having the DrawerLayout shadow behind the FragmentOne content.

Am I doing something wrong ?

**Comment by sayoojvalsan-demandmedia** [comment]
Same problem. Anyone fixed this ?

**Comment by sayoojvalsan-demandmedia** [comment]
As per reading comments above, my issue got resolved by wrapping the Framelayout in a Relativelayout. But I have no idea why it worked!. I don't reallly like the idea of unnecessary wrapping it with a Relativelayout. Anyone ?
