### ISSUE TITLE
Automatically show the bottom bar after delay when the scroll stops

### ISSUE THREAD

**Issue by UNCVR** [roughike/BottomBar#189]
After some tests, I observe that for non advanced users, it is not obvious to scroll up to make the bottom bar reappear.

It could be great to make the bottom bar reappear after some delay :)

**Comment by UNCVR** [comment]
By the way, it could facilitate the "scroll to top" action :
"Tapping on the active action in the bottom navigation bar will navigate the user to the top of the view."

**Comment by PsyGik** [comment]
> "Tapping on the active action in the bottom navigation bar will navigate the user to the top of the view."

You can always implement scrollToTop in `onTabReSelected`. I don't think BottomBar should be concerned about the scroll states.

**Comment by UNCVR** [comment]
That's what I do but when you are at the bottom of the list, user have to scroll up to make the bottom bar reappear to click on the tab and make the call to `onTabReSelected`. Make the bottom bar reappear on scroll top could remove the unnecessary scroll up gesture.

I don't think hiding permanently the navigation is a good practice.

**Comment by PsyGik** [comment]
Well as per the docs,

> The bottom navigation bar can appear and disappear dynamically upon scrolling:

> Scrolling downward hides the bottom navigation bar
> Scrolling upward reveals it

So I guess there's nothing we can do about it if this library strictly follows the guidelines. 

As for a solution, you can attach a scroll listener to the scrolling view and manipulate the BottomBar using `show()`/`hide()`.

**Comment by UNCVR** [comment]
Thanks for your answers and work, I will do that.

Hiding the navigation on neutral state is not a good behavior...
Hope they will update the guidelines in the future.

**Comment by yombunker** [comment]
This is part of googles CoordinatorLayout behavior
