### ISSUE TITLE
Set icon programmatically 

### ISSUE THREAD

**Issue by ncnlinh** [roughike/BottomBar#190]
Is there a way to change the icon of the tabs (maybe add something like setIcon() in BottomTabBar?)

**Comment by ratabb** [comment]
[BottomBarTab(Drawable icon, @StringRes int titleResource)](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBarTab.java#L54)
[BottomBar setItems(BottomBarTab... bottomBarTabs)](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L306)


```
        Context context = //....
        int[][] sResource = {
           { R.drawable.ic_phone_android_black_24dp, R.string.screen },
           { R.drawable.ic_image_black_24dp, R.string.background },
           { R.drawable.ic_style_black_24dp, R.string.badge }
        };
        int count = sResource.length;
        BottomBarTab[] barTabs = new BottomBarTab[count];
        for (int i = 0; i < count; i++) {
             Drawable icon = VectorDrawableCompat.create(context.getResources(), sResource[i][0], drawableRes, context.getTheme());
             barTabs[i] = new BottomBarTab(icon, sResource[i][1]);
        }
        BottomBar bottomBar = BottomBar.attach(activity, saveState);
        bottomBar.setItems(barTabs);
```

**Comment by amorenew** [comment]
((AppCompatImageView)bottomBar.findViewById(R.id.tabHome).findViewById(R.id.bb_bottom_bar_icon)).setImageResource(R.drawable.ic_home_filled);

**Comment by yombunker** [comment]
You can currently get the BottomBarTab view and do whatever you think is necessary, and maybe some extra fucntionality will be added in the near future, but, for now that's the closes it gets.
