### ISSUE TITLE
Bottombar is coming already selected with first item

### ISSUE THREAD

**Issue by MrYavuz** [roughike/BottomBar#195]
```
   bottomBar = BottomBar.attach(findViewById(R.id.navigation_view), savedInstanceState);

    bottomBar.setItemsFromMenu(R.menu.menu_bottom, new OnMenuTabClickListener() {
        @Override
        public void onMenuTabSelected(int itemId) {
            switch (itemId) {
                case R.id.checkin_item:
                    Snackbar.make(drawerLayout, "Recent Item Selected", Snackbar.LENGTH_LONG).show();
                    break;
                case R.id.message_item:
                    Snackbar.make(drawerLayout, "Favorite Item Selected", Snackbar.LENGTH_LONG).show();
                    break;
                case R.id.friends_item:
                    Snackbar.make(drawerLayout, "Location Item Selected", Snackbar.LENGTH_LONG).show();
                    break;
                case R.id.notification_item:
                    Snackbar.make(drawerLayout, "Location Item Selected", Snackbar.LENGTH_LONG).show();
                    break;
                default:
                    break;
            }
        }
        @Override
        public void onMenuTabReSelected(int itemId) {
            switch (itemId) {
                case R.id.checkin_item:
                    Snackbar.make(drawerLayout, "Recent Item Selected", Snackbar.LENGTH_LONG).show();
                    break;
                case R.id.message_item:
                    Snackbar.make(drawerLayout, "Favorite Item Selected", Snackbar.LENGTH_LONG).show();
                    break;
                case R.id.friends_item:
                    Snackbar.make(drawerLayout, "Location Item Selected", Snackbar.LENGTH_LONG).show();
                    break;
                case R.id.notification_item:
                    Snackbar.make(drawerLayout, "Location Item Selected", Snackbar.LENGTH_LONG).show();
                    break;
                default:
                    bottomBar.clearFocus();
                    break;
            }
        }
    });
```

when application run, First item is coming already selected . How can disable this ?

bottombar.clearFocus()  or which function ?

**Comment by JonathanMerritt** [comment]
I've needed the same behavior, what I ended up doing was simply save an int and keep track of the first selection and just have it pass through the listeners.

example:
`new OnMenuTabClickListener() {
            int i = 0;
            @Override
            public void onMenuTabSelected(@IdRes int tabId) {
                if (this.i != 0) {
                     // your action.
                }
                this.i++;
            }

            @Override
            public void onMenuTabReSelected(@IdRes int tabId) {
                if (this.i != 1) {
                    // your action.
                }
                this.i++;
            }
        });`

**Comment by MrYavuz** [comment]
Thanks @JonathanMerritt you are right and solution works but this solution is temporary. I'm using navigation drawer and bottombar together so I have to know that how can disable selected item. When I changed page nothing must be selected.

**Comment by JonathanMerritt** [comment]
@MrYavuz

Yes, it isn't the best solution either.

Since answering this, I've been looking at my setup over and over trying different things.

I've found that no matter what, on attach or shy it will always select an item, either chosen or default by the library. Also if you set an active tab color after attach or setting TabListener it will also select or reselect. So in my case I was doing the attach, selection, then setting a active color, reselection. Hence why I need the into to be 0 on select and 1 on reselect in my solution.

I really have no clue how to have it never select. Unless you only attach when the bar is needed, and set it default selection to the tab you want, on the nav drawer or wherever.

Sorry.

**Comment by yombunker** [comment]
If you update to the latest version there is a method that allows you to specify the starting tab
