### ISSUE TITLE
BottomBarTab icon's color is always white

### ISSUE THREAD

**Issue by midhunm45** [roughike/BottomBar#199]
I added .png image as tab icon using setItems() and the icon's color stays white(or like tinted into it)
this is my code:
        mBottomBar = BottomBar.attach(HomeActivity.this,savedInstanceState);
        mBottomBar.setItems(
          new BottomBarTab(ContextCompat.getDrawable(this,R.drawable.tab_one), "One"),
          new BottomBarTab(ContextCompat.getDrawable(this,R.drawable.tab_two), "Two"),
          new BottomBarTab(ContextCompat.getDrawable(this,R.drawable.tab_three), "Three"),
          new BottomBarTab(ContextCompat.getDrawable(this,R.drawable.tab_four), "Four"));

**Comment by minglini** [comment]
Did you solved your problem? If yes, how?

**Comment by roughike** [comment]
With the 2.0, the colors aren't that magical anymore.

[See the readme](https://github.com/roughike/BottomBar#all-customization-options)
