### ISSUE TITLE
Bottom Tabs are above Material Drawer

### ISSUE THREAD

**Issue by AlexLionne** [roughike/BottomBar#2]
I'm using a drawer menu, so I use the bottom tabs into a fragment. But when I open the drawer, tabs are above the drawer.

**Comment by AlexLionne** [comment]
I'm using bottom tabs as in example
```java
mBottomBar.setFragmentItems(getSupportFragmentManager(), R.id.fragmentContainer,
    new BottomBarFragment(SampleFragment.newInstance("Content for recents."), R.drawable.ic_recents, "Recents"),
    new BottomBarFragment(SampleFragment.newInstance("Content for favorites."), R.drawable.ic_favorites, "Favorites"),
    new BottomBarFragment(SampleFragment.newInstance("Content for nearby stuff."), R.drawable.ic_nearby, "Nearby")
);
```

**Comment by AlexLionne** [comment]
another thing do you know how to attach it to only one fragment and not an Activity ? in my case it attach it to all fragments then

**Comment by AlexLionne** [comment]
is this will do the trick ?
```java
 @Override 
    public static BottomBar attachFragment(Fragment fragment, Bundle savedInstanceState) {
        BottomBar bottomBar = new BottomBar(fragment.getActivity());
        bottomBar.onRestoreInstanceState(savedInstanceState);

        ViewGroup contentView = (ViewGroup) fragment.getActivity().findViewById(android.R.id.content);
        View oldLayout = contentView.getChildAt(0);
        contentView.removeView(oldLayout);

        bottomBar.getUserContainer()
                .addView(oldLayout, oldLayout.getLayoutParams());
        contentView.addView(bottomBar, 0);

        return bottomBar;
    }
```

**Comment by AlexLionne** [comment]
I can't Override it due to private access

**Comment by roughike** [comment]
I believe I found a way to fix the first problem. Change your ```attach(this, savedInstanceState)``` to this:

```java
// A new method for attaching to other things than just the Activity's root content view.
mBottomBar.attach(findViewById(R.id.fragmentContainer, savedInstanceState);
```

Let me know if this worked.

**Comment by AlexLionne** [comment]
okay ! I found something else. because I'm working wtih fragment into a drawer, when I'm selecting an item, the bottom bar is attached another time so I've got 1,2,3+... bottom tabs maybe we should attach webview only its not done ?

**Comment by AlexLionne** [comment]
wrong 1rst argument type yeah its View type but Activity is required

**Comment by roughike** [comment]
@AlexLionne
And for using separate BottomBars for single Fragments, try overriding your Fragment's ```onCreateView``` like this:

```java
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View view = inflater.inflate(R.layout.text, container, false);
    // initialize your views here

    BottomBar bottomBar = BottomBar.attach(view, savedInstanceState);
    bottomBar.setItems(
        new BottomBarTab(R.drawable.ic_recents, "Recents"),
        new BottomBarTab(R.drawable.ic_favorites, "Favorites"),
        new BottomBarTab(R.drawable.ic_nearby, "Nearby")
    );

    return bottomBar;
}
```

**Comment by roughike** [comment]
@AlexLionne 
I updated the library before commenting with that solution, so there is indeed an ```attach(View view, Bundle savedInstanceState)``` method there.

**Comment by AlexLionne** [comment]
Okay thanks I'm trying

**Comment by roughike** [comment]
@AlexLionne 
The library was approved to jCenter. I just updated the Readme, go there to check for instructions how to update.

Tell me if everything works, so I can close the issue. :)

**Comment by AlexLionne** [comment]
I know it will work you can close it thanks alot :)
