### ISSUE TITLE
how to hide softkey area?

### ISSUE THREAD

**Issue by jinnybrain** [roughike/BottomBar#20]
![image](https://cloud.githubusercontent.com/assets/8475621/13866485/114401d6-ecf9-11e5-9086-7b5bf4b42cd4.png)

how to hide softkey area?

**Comment by roughike** [comment]
How did you get that result? Did you hide the Navigation Bar (=softkeys) by yourself?

**Comment by jinnybrain** [comment]
no, i just use your sample.
Device is Galaxy s4, has not SoftKey.


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar.hideShadow();
        mBottomBar.setItemsFromMenu(R.menu.navigation, new OnMenuTabSelectedListener() {
            @Override
            public void onMenuItemSelected(@IdRes int menuItemId) {

            }
        });
        mBottomBar.mapColorForTab(0, ContextCompat.getColor(this, R.color.colorAccent));
        mBottomBar.mapColorForTab(1, 0xff5d4037);
        mBottomBar.mapColorForTab(2, "#7B1FA2");
        mBottomBar.mapColorForTab(3, "#FF5252");
        mBottomBar.mapColorForTab(4, 0xffffffff);
    }

**Comment by roughike** [comment]
I'll fix this. Stay tuned for 15mins or so.

**Comment by roughike** [comment]
And it's fixed in the version _1.0.5_. 

It should now detect if the the device has physical navigation buttons and just work.

If it for some reason doesn't, call ```mBottomBar.noNavBarGoodness();``` right after ```BottomBar.attach();```

Let me know if this works for you now.
