### ISSUE TITLE
scrollable bottom bar

### ISSUE THREAD

**Issue by HabibRasyid** [roughike/BottomBar#200]
i try to use bottom bar, can i make it scrollable like a tab layout?

**Comment by zhywang** [comment]
Seems Google doesn't think it's a good idea:
`
If your top-level navigation has more than six destinations, provide access to destinations not covered in bottom navigation through alternative locations, such as a navigation drawer.
`
https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-usage

**Comment by roughike** [comment]
This won't be supported by this library, so I'm closing this issue.
