### ISSUE TITLE
BottomBar Tab Color Issue

### ISSUE THREAD

**Issue by fatihkahveci** [roughike/BottomBar#202]
Hello,

We have a weird issue. When we test our app Nexus 5 (Android 6.0) device bottom tabs does not take color. But when we test an other phone our code run perfect.

![alt code](http://i.imgur.com/YmCMcVQ.png "Code")

![alt device](http://i.imgur.com/1JeLmk1.png "device")

**Comment by krazykira** [comment]
@fatihkahveci In order to make this work you need to call   `mBottomBar.setMaxFixedTabs(4);` before you add items to bottom bar.

**Comment by roughike** [comment]
If you mean that the NavBar isn't transparent, that behavior is fixed in the 2.0 version. [See the README](https://github.com/roughike/BottomBar#how-do-i-draw-it-under-the-navbar) how to implement it.
