### ISSUE TITLE
.jar file

### ISSUE THREAD

**Issue by ghost** [roughike/BottomBar#207]
I'm looking for .jar file, for some reason i cannot get it from gradle

**Comment by PsyGik** [comment]
You cannot make a .jar file because this library contains layout files. You can fork this repo and build it locally where it'll show up in the _build/outputs/aar/_ directory.

**Comment by Runico** [comment]
```
Error:(26, 13) Failed to resolve: com.roughike:bottom-bar:1.3.3
<a href="openFile:C:/Users/Yophiel/Desktop/BioGram/Android/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```

what's wrong

**Comment by flameboy** [comment]
I have the same problem with the 1.3.9 version, other versions, and even if I try with 1.3.+

```
Error:(81, 13) Failed to resolve: com.roughike:bottom-bar:1.3.+
Show in File
Show in Project Structure dialog
```

I tried to use SDK 23 and Gradle 1.3.1 but no more idea... :(

Any idea?

**Comment by juanvaldemar** [comment]
tengo el mismo problema, ¿Cúal fue la solucion los que aplicaron?
