### ISSUE TITLE
Tab Selection

### ISSUE THREAD

**Issue by sandeshlasnapure** [roughike/BottomBar#212]
Sometimes two tabs get selected on my Samsung S4.
![screenshot_2016-05-09-07-40-12](https://cloud.githubusercontent.com/assets/12455411/15102210/25000064-15ba-11e6-80aa-a03e05c5a61f.png)

**Comment by Gonzom** [comment]
I've also encountered this issue.

**Comment by roughike** [comment]
Fixed in the newest version (2.0 and up).
