### ISSUE TITLE
Bottom bar hide/show on sliding left/right between viewpager

### ISSUE THREAD

**Issue by niteshkhatri** [roughike/BottomBar#215]
Hi guys. I have BottomBar with two tabs in it at the bottom of my screen. When first tab is selected Fragment1 is shown and on selecting second tab Fragment2 is shown.

In Fragment1 I have TabLayout at the top having 3 tabs with viewpager below. These tabs changes on viewpager swipe. Same is the case with Fragment2. I have used attachShy() method to show/hide BottomBar on scroll up/down. When I scroll up/down it works perfectly. However, When I change tabs inside Fragment1 by swiping left/right, even then the BottomBar hide/show is happening.

I want to hide/show BottomBar on slide up/down and not on slide left/right or sliding left/right at an angle. Is there any threshold I can set to avoid this behaviour?

How can prevent this from happening?

**Comment by yombunker** [comment]
Is it still happening on the latest version? will be closing for now. Feel free to re-open if so.
