### ISSUE TITLE
`useFixedMode()` makes bottom bar appears above the keyboard

### ISSUE THREAD

**Issue by abdelhady** [roughike/BottomBar#216]
When I use the `useFixedMode()` (or even `attachShy()` with `android:fitsSystemWindows="true"`), the keyboard doesn't hide the bar behind it as per the material design (I'm opening the keyboard to write inside a webview).

before opening the keyboard:
![2016-05-16-16-11-22_small](https://cloud.githubusercontent.com/assets/2075626/15296815/6a1abdf0-1b97-11e6-98d3-4c80b3fea1bc.png)

after opening the keyboard:
![2016-05-16-16-11-42_small](https://cloud.githubusercontent.com/assets/2075626/15296881/be2f1e36-1b97-11e6-8619-219e2afc63ae.png)

using an actual LG G2 device, running Kitkat 4.4.2. Also got the same behavior when using simulators running Lollipop & Marshmallow.

**Comment by shaunkawano** [comment]
I think providing a screenshot will help people understand your situation more, easily.

**Comment by abdelhady** [comment]
@shaunkawano I've updated the issue with the screenshots, thanks.

**Comment by Xstar97** [comment]
Try something like if the keyboard is in view(use)
dettach bottombar & if the keyboard is not in use anymore reattach bottom bar

or if you show how you implemented bottombar we will be able to help further

**Comment by abdelhady** [comment]
I've tried to listen for keyboard show/hide events, but I couldn't find how to do that (all I found is some non-working hacks)

& the code I'm using is exactly like the example used here in the ReadMe, I just used `useFixedMode()` like I said before

**Comment by glalwani2** [comment]
I am facing the same issue, the bottom bar is coming above keyboard and also the navigation drawer in the left when I open it, I can click the bottom bar(which should not be the case) the bottom bar should be behind navigation drawer and keyboard as per the guidelines(also coz it makes sense).How to do that I am stuck please help. @abdelhady @roughike

**Comment by pocheshire** [comment]
For fix this you need add `<activity android:windowSoftInputMode="adjustPan"/>` (on Xamarin it's like activity attribute `[Activity(WindowSoftInputMode=SoftInput.AdjustPan)]`)

**Comment by Xstar97** [comment]
Thanks! just confirming its working...now I can update & fix that stupid keyboard bug

**Comment by abdelhady** [comment]
@pocheshire I've tried `"adjustPan"` before & it is really working, but unfortunately, it had a bad side effect where the keyboard can cover the field I'm writing in, 
but without the `"adjustPan"` if the keyboard is going to cover the field I'm writing in, the activity will scroll the layout to bring the field above the keyboard, so I can see what I'm writing.

**Comment by agarwalkeshav** [comment]
http://stackoverflow.com/questions/2150078/how-to-check-visibility-of-software-keyboard-in-android

Check this out, the NEW ANSWER. Works well for me.
