### ISSUE TITLE
Toolbar gets truncated when i use bottombar

### ISSUE THREAD

**Issue by krazykira** [roughike/BottomBar#217]
Bottombar seems to work well on devices that have **hard menu keys** for navigation like **s6 3dge** but its doesnt seem to work properly for phones that use **soft menu keys** for navigation like

### LG G2  (Android Version 4.4.2)
![device-2016-05-09-152443](https://cloud.githubusercontent.com/assets/2201511/15114427/3f0017ac-15fa-11e6-80f5-e080d62b4b5f.png)

### Nexus 6 (Android Version 6.0.1)
![nexus6](https://cloud.githubusercontent.com/assets/2201511/15114907/802d4b4e-15fc-11e6-9ac8-dbcf2d4910e3.png)

**This is how i have implemented the bottom bar**

  ```
 bottomBar = BottomBar.attachShy(coordinatorLayout, frameLayout, null);
//        If i use noNavBarGoodness() then it is displayed properly with black soft menu keys
//        bottomBar.noNavBarGoodness();
        bottomBar.setMaxFixedTabs(2);

        bottomBar.setItemsFromMenu(R.menu.main_tab_items, menuTabClickListener);
        // Setting colors for different tabs when there's more than three of them.
        // You can set colors for tabs in three different ways as shown below.
        bottomBar.mapColorForTab(0, ContextCompat.getColor(this, R.color.oneTabColor));
        bottomBar.mapColorForTab(1, ContextCompat.getColor(this, R.color.twoTabColor));
        bottomBar.mapColorForTab(2, ContextCompat.getColor(this, R.color.threeTabColor));
```

when i remove the `bottombar` then the toolbar is displayed properly

**Comment by Nolanus** [comment]
Have you tried setting fitsSystemWindows="true" on your root layout?
Some reading about this property: https://medium.com/google-developers/why-would-i-want-to-fitssystemwindows-4e26d9ce1eec#.lacrvku7u

**Comment by krazykira** [comment]
Yes i have tried that but it doesn't solve the problem. The only way i am able to solve the problem is if i use  `bottomBar.noNavBarGoodness();` but in this way the **navigation bar** doesn't get colored and app looks ugly

**Comment by Xstar97** [comment]
have you tried something like this?

coordinatorLayout = (CoordinatorLayout) findViewById(R.id.MainActivity);

        mBottomBar = BottomBar.attach(this, savedInstanceState);
                //this helps to remove extra space
		mBottomBar.noTopOffset();
//this part is a fix for my issue #230 
		if(Build.VERSION.SDK_INT == 23){
			
		}else{
			mBottomBar.useFixedMode();
		}
        mBottomBar.setItemsFromMenu(R.menu.bottom_menu, new OnMenuTabClickListener() {
				Fragment fragment;	
			    @Override
				public void onMenuTabSelected(@IdRes int menuItemId) {
					if (menuItemId == R.id.one) {
						fragment = new OneFragment();
					}
					if (menuItemId == R.id.two) {
						fragment = new TwoFragment();
					}
					if (menuItemId == R.id.three) {
						fragment = new ThreeFragment();
					}
					if (menuItemId == R.id.four) {
						fragment = new FourFragment();
					}
					FragmentManager fragmentManager = getSupportFragmentManager();
					fragmentManager.beginTransaction()
						.replace(R.id.content, fragment)
						.commit();
				}

				@Override
				public void onMenuTabReSelected(@IdRes int ..............................................................................................................
...........................................................................................................................................................................................
				}
			});
		
		mBottomBar.setActiveTabColor("#C2185B");
        mBottomBar.mapColorForTab(0, ContextCompat.getColor(this, R.color.colorAccent));
        mBottomBar.mapColorForTab(1, "#3F51B5");
        mBottomBar.mapColorForTab(2, "#303F9F");
        mBottomBar.mapColorForTab(3, "#FF5252");

This solved my issue with spacing...how about you?

**Comment by krazykira** [comment]
@Xstar97 I don't understand what you mean, i want to have colored tabs and so i can't use `bottomBar.useFixedMode() `because if i use it then our tabs are not colored when they get selected.

If you are saying that i should wrap my Layout in a CoordinatorLayout then i have already done that. My layout file is like

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/drawerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/coordinatorlayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:elevation="-10dp">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="@color/colorPrimary"
                android:title="@string/app_name"
                app:layout_scrollFlags="scroll|enterAlways"/>
        </android.support.design.widget.AppBarLayout>

        <FrameLayout
            android:id="@+id/fragmentContainer"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"/>
    </android.support.design.widget.CoordinatorLayout>

    <android.support.design.widget.NavigationView
        android:id="@+id/navigationView"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:menu="@menu/drawer_items"/>
</android.support.v4.widget.DrawerLayout>
```

and  i am attaching my `bottom bar`using the code below
      `  bottomBar = BottomBar.attachShy(coordinatorLayout, frameLayout, null);`

**Comment by Xstar97** [comment]
Okay..sorry my solution only works on devices before sdk22 & if you have 4 or more items...its a bug
However to fix your issue try this app_bar_main.xml

<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
	xmlns:ads="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
	android:id="@+id/MainActivity"
    tools:context=".activities.MainActivity">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/actionBar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/AppTheme.AppBarOverlay">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="@color/colorPrimary"
                app:popupTheme="@style/AppTheme.PopupOverlay" />

        </android.support.design.widget.AppBarLayout>
		
		<FrameLayout
            android:id="@+id/content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
		
    </RelativeLayout>

//Fab goes here unless you want it in the fragment....

</android.support.design.widget.CoordinatorLayout>

mBottomBar = BottomBar.attach(this, savedInstanceState);
//call notopoffset right after attach(shy)
		mBottomBar.noTopOffset();

///define the colors as normal
		mBottomBar.setActiveTabColor("#C2185B");
        mBottomBar.mapColorForTab(0, ContextCompat.getColor(this, R.color.colorAccent));
        mBottomBar.mapColorForTab(1, "#3F51B5");
        mBottomBar.mapColorForTab(2, "#303F9F");

If it doesnt work...let me know...& i will try it a different way since I am also had trouble with this

**Comment by Xstar97** [comment]
I solved your problem!
by using this
mBottomBar.noNavBarGoodness();

The space is gone on my pre-mm device...so you do something this...if it works normally on other sdk versions
		if(Build.VERSION.SDK_INT == 23){
			
		}else{
			mBottomBar.noNavBarGoodness();
		}

**Comment by krazykira** [comment]
@Xstar97 i know about that. i said this when i reported the issue 
```
//        If i use noNavBarGoodness() then it is displayed properly with black soft menu keys
//        bottomBar.noNavBarGoodness(); 
```
But this is not a solution as the Navbar is not colored anymore if i use it. This is more of a workaround then solution.

**Comment by Xstar97** [comment]
I know...so until bottombar is updated you will just have to use until its fixed

**Comment by meNESS** [comment]
@krazykira Please use the latest version, then follow this step:
- You have to set `android:fillViewPort` property `true` to `CoordinateLayout` and its views except the `Toolbar`. Furthermore, if you're using fragments and have an Activity layout which holds fragments (it must has a container view), you also have to set that property for that container or the root view. This would fix the truncated toolbar issue.

**Comment by roughike** [comment]
This is now not an issue with the new versions (2.0 and up).
