### ISSUE TITLE
How to remove elevation ？

### ISSUE THREAD

**Issue by baoyachi** [roughike/BottomBar#218]
Now，my project just have three bottom view in bottom ,I just want remove shadow use this method,that does not work:
        btoombar.setElevation(0);
so,I want to know how to solution? Thanks

**Comment by vbuberen** [comment]
To remove shadow you should use method `hideShadow()` which is already implemented in the lib.

**Comment by baoyachi** [comment]
Yeah，So great!

**Comment by ptykamikaze** [comment]
Hello! Why I cant call the method hideShadow() on the Buttom Bar. I'm using version 2.0.2

**Comment by ChaosLeong** [comment]
@ptykamikaze To do this in current version (2.1.1) of BottomBar is add `app:bb_showShadow="false"`.
