### ISSUE TITLE
FloatingActionButton Overlap

### ISSUE THREAD

**Issue by kolbasan** [roughike/BottomBar#219]
Hey guys. I am trying to achieve the following layout: Single activity with bottom bar, having 4 different fragments for each tab, while only one of the fragments has a floating action button above the bottom bar.
The fragments are scrollable and the bottom bar should be shyAttached.
I tried playing around with different layouts but failed, therefore I need your help.
Thank you!

**Comment by Xstar97** [comment]
How are you implementing the fragments?
through xml or java code?
did you try it this way?

______activity____________
mBottomBar = BottomBar.attachShy((CoordinatorLayout) findViewById(R.id.myCoordinator), 
    findViewById(R.id.myScrollingContent), savedInstanceState);

_______xml______________
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/myCoordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/myScrollingContent"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        

    </android.support.v4.widget.NestedScrollView>

</android.support.design.widget.CoordinatorLayout>

**Comment by MarcusWolschon** [comment]
@Xstar97 where in your example is the Floating Action Button placed and attached to?

**Comment by the-invader** [comment]
I also have the same issue.
Bottombar and FAB both are direct child of CoordinatorLayout.
The floating action button is overlapping the bottombar due to a fixed "layout_marginBottom" attribute value. Please help.

**Comment by agogl** [comment]
has anyone found a solution yet? got the same problem

**Comment by MarcusWolschon** [comment]
Does the behavior of the FAB correctly depend on the BottomBar-type?

**Comment by yombunker** [comment]
I will be closing this as there is not enough information to know if this library is to blame of that behavior, if you still face this on the latest version and you have more information to provide please feel free to re-open.
