### ISSUE TITLE
Adds space above attached view

### ISSUE THREAD

**Issue by NickM-27** [roughike/BottomBar#22]
Just updated to the latest build and it now adds space above the attached view. Check out the screenshot. 
![screenshot_20160317-223455](https://cloud.githubusercontent.com/assets/14866235/13867835/fbf514ae-ec90-11e5-920b-be5815584234.png)

**Comment by roughike** [comment]
Give me 15 minutes or so and this will be fixed.

**Comment by roughike** [comment]
What does your layout look like? Are you using ```fitsSystemWindows="true"``` or anything special?

I can't replicate the problem.

**Comment by NickM-27** [comment]
yes, I will post below:

`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/list_coordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:orientation="vertical">`

    `<android.support.design.widget.AppBarLayout
        android:id="@+id/list_bar_layout"
        android:layout_width="match_parent"
        android:layout_height="256dp"
        android:fitsSystemWindows="true"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/list_collapsing_toolbar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:contentScrim="@color/action_primary"
            app:title="@string/hub"
            android:fitsSystemWindows="true"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:statusBarScrim="@color/color_primary_dark">

            <ImageView
                android:id="@+id/toolbar_image"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fitsSystemWindows="true"
                android:scaleType="centerCrop"
                app:layout_collapseMode="parallax"
                tools:ignore="ContentDescription" />

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:popupTheme="@style/PopupStyle"
                app:layout_collapseMode="pin" />

        </android.support.design.widget.CollapsingToolbarLayout>

    </android.support.design.widget.AppBarLayout>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/list_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

</android.support.design.widget.CoordinatorLayout>`

**Comment by roughike** [comment]
It'll take a 15 minutes more. I just had to fix a force close before this.

**Comment by NickM-27** [comment]
yeah, I think I experienced that FC as well so all good for me! :D

**Comment by roughike** [comment]
```bottomBar.noNavBarGoodness()``` should fix this, but this way the Navigation Bar won't be transparent as seen in the second demo gif in the Readme.

**Comment by NickM-27** [comment]
Ok, just tested **without ** the `bottomBar.noNavBarGoodness()` and now the bottombar is inside of the navigation bar. The method above does fix this.

**Comment by roughike** [comment]
Now I think I got it.

Remove ```bottomBar.noNavBarGoodness()``` and replace it with a new method ```mBottomBar.noTopOffset()```. You'll get the NavBar goodness without the top offset badness!

Tell me if it works.

**Comment by NickM-27** [comment]
Possibly, but now I have a different issue with that on. See below, that listview with food pass and buffet used to go all the way to the bottom, now it is stuck higher

And not sure what you mean by CV but thanks! Was really happy when I saw this library! Perfect for the app!

![screenshot_20160317-235856](https://cloud.githubusercontent.com/assets/14866235/13868944/7105dae8-ec9c-11e5-92db-c2a1e887ccc5.png)

**Comment by roughike** [comment]
Does removing ```android:fitsSystemWindows="true"``` and *not* using  ```mBottomBar.noTopOffset()``` or ```bottomBar.noNavBarGoodness() ``` at all work?

**Comment by NickM-27** [comment]
Ok, turning them all off results in that original top bar problem. If I get rid of the system windows but keep offset on it works except that the toolbar is inside the status bar

**Comment by roughike** [comment]
Damn.

Try updating to version 1.0.8 and trying only ```bottomBar.useOnlyStatusBarTopOffset()```.

If that doesn't work, I'll try again on Monday.

**Comment by NickM-27** [comment]
Mostly, you fixed the other activities when I got rid of the systemWindows. But then it made it so the first panel with the collapsing toolbar had a statusbar filled already so that didn't work anymore. What I would recommend is just creating a method for each fragment that sets the status like you have now. That way you can set it up based on what kind of view is being used

**Comment by roughike** [comment]
One thing you could try is putting your RecyclerView inside of BottomBar like this:

```java
bottomBar.attach(findViewById(R.id.list_main), savedInstanceState);
```

Try playing with the ```attach(View view, Bundle savedInstanceState)```

**Comment by NickM-27** [comment]
Interesting approach, but then wouldn't the bar completely disappear when I change from a different fragment to another? (using the built-in fragment support.

**Comment by roughike** [comment]
I don't think it would. Then again, I'm drunk at the moment.

Try and see, and report the results.

**Comment by NickM-27** [comment]
No dice, that did the same issue where the views can't go all the way (the last screenshot)

**Comment by roughike** [comment]
Now updated the library to version 1.0.9.

Try if this now works (basically the same thing than before):

```java
mBottomBar = BottomBar.attach(this, savedInstanceState);
mBottomBar.noTopOffset();

// other sexy magic
```

**Comment by NickM-27** [comment]
Nope, still has that same issue in the second screenshot. Personally I don't mind using the noNavBarGoodness since a bar that changes color doesn't work for thematically for the app I am developing .

**Comment by roughike** [comment]
That's weird. For me it worked.

Glad it works for you without the goodness though.

**Comment by NickM-27** [comment]
I think the issue is coming from the fact that I have multiple fragments with different layouts, one that fits system windows and one that doesn't. Regardless I wouldn't worry about it since I already have my solution and I haven't seen anyone else with that issue.

**Comment by roughike** [comment]
And here I was (almost) ripping my hair out of my head!

Well I'm closing this one for now.

**Comment by PiyushPoriya** [comment]
Hello Please help through this,,

I am not able to change fragment using mBottomBar.selectTabAtPosition(1,true); its just change tab but not changing Fragment..

Dose any one face this problem?

**Comment by NickM-27** [comment]
The library doesn't support fragments anymore, you need to do everything yourself.
