### ISSUE TITLE
Set Titles to always visible

### ISSUE THREAD

**Issue by jessfog** [roughike/BottomBar#220]
Is it possible to set the menu titles ALWAYS visible?

Is it possible to use the Tablet mode (LEFT Tab) with all the bells and whistles (animation, background colors, etc)?

**Comment by Nolanus** [comment]
For the first please refer to https://github.com/roughike/BottomBar/issues/130

**Comment by roughike** [comment]
In the newest version, yes! You can have 5 fixed tabs, you can have color changing bar on tablets, everything.

**Comment by MarcABernard** [comment]
What's the magic to get 5 fixed tabs (with visible titles) working, in the new version?
