### ISSUE TITLE
Orientation change issue

### ISSUE THREAD

**Issue by Lintom** [roughike/BottomBar#221]
Hi. I have stack of fragments in tab. If opened last fragment from stack and change of orientation, is reset to first fragment. How to fix this?

**Comment by Xstar97** [comment]
1. you can add this to your manifest to the activity thats hosting your bottombar...
android:configChanges="orientation|screenSize"

2. add this to the activity(maybe fragment too?) thats hosting your bottombar
 @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);

        mBottomBar.onSaveInstanceState(outState);
    }
3. if you show what you have implemented so far if the two solutions dont work...I will probably be able to help better

**Comment by naveen1389** [comment]
You can get current position when before orientation change and save it in OnSaveInstanceState. and get in OnCreate()

@Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putInt(TAB_STATE, bottomBar.getCurrentTabPosition());
    }

In OnCreate : 
 if(savedInstanceState != null){
            currentTabState = savedInstanceState.getInt(TAB_STATE, 0);
        }

        bottomBar.selectTabAtPosition(currentTabState, true);

**Comment by Xstar97** [comment]
I like that solution..once my phone charges(since its dead) I will test it out thanks!

**Comment by Lintom** [comment]
Here is my code

```
public class TabActivity extends AppCompatActivity {
final protected String LOG_TAG = "TabActivity"
private BottomBar mBottomBar;

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mBottomBar = BottomBar.attach(this, savedInstanceState);

        mBottomBar.setItemsFromMenu(R.menu.bottombar_menu, new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId) {
                showFragment(menuItemId);
            }

            @Override
            public void onMenuTabReSelected(@IdRes int menuItemId) {
                Log.d(LOG_TAG, "reselected");
            }
        });

        if (savedInstanceState == null) {
             showFragment(R.id.bottomBarItemOne);
        }       
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        if (mBottomBar != null) {
            mBottomBar.onSaveInstanceState(outState);
        }
    }

    private void showFragment(int menuItemId) {
        Fragment fragment = null;
        String tag = null;

        switch (menuItemId) {
            case R.id.bottomBarItemOne:
                fragment = FirstFragment.newInstance();
                tag = FirstFragment.TAG;
                break;
            case R.id.bottomBarItemTwo:
                fragment = SecondFragment.newInstance();
                break;
            case R.id.bottomBarItemThree:
                fragment = ThirdFragment.newInstance();
                break;
        }

        FragmentManager fm = getSupportFragmentManager();

        fm.beginTransaction().replace(R.id.fragmentContainer, fragment, tag).commit();
    }
}
```

In FirstFragment i add another fragment
```
AnotherFragment anotherFragment = AnotherFragment.newInstance();
getFragmentManager().beginTransaction().hide(this).replace(R.id.fragmentContainer, anotherFragment, AnotherFragment.TAG).addToBackStack(AnotherFragment.TAG).commit();
```

And when i rotate device, is reset to FirstFragment.

**Comment by Xstar97** [comment]
you creating a fragment from your activity...then creating another fragment from another fragment....is that what you did?

did you try to pop the first fragment?

**Comment by Xstar97** [comment]
if (savedInstanceState == null) {
             showFragment(R.id.bottomBarItemOne);
        }       
    }
thats find however is a solution you should add to the manifest that host your bottombar
android:configChanges="orientation|screenSize"

Now by adding that it will expect you to handle the orientation which you don't need to do at all & if you rotate your device the fragment/activity will not reset

**Comment by Lintom** [comment]
Thanks, but `android:configChanges="orientation|screenSize"` it's not a solution. Thats means handling `onConfigurationChanged()` by yourself in activity.

**Comment by Xstar97** [comment]
Like I said...you dont need to handle it
I had this problem before & when I set that in my manifest my fragments, activities, or even my recyclerview do not reset
how about implementing it first before you argue with someone trying to
help you...I wouldn't have told you it was a solution if it didn't work

**Comment by aleksamarkoni** [comment]
@Xstar97 https://stackoverflow.com/questions/37787042/why-using-androidconfigchanges-is-a-bad-practice

**Comment by Xstar97** [comment]
At the time yes as it was a just a work around before V2...but now it's not needed.
