### ISSUE TITLE
Navigating in tab

### ISSUE THREAD

**Issue by Nominalista** [roughike/BottomBar#224]
How to accomplish something like in Google [example](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-behavior) where they click on Kodaline album in Music tab, and then new view is showing on top without disappearing bottom bar?

**Comment by JonathanMerritt** [comment]
Sounds like something you need to do in your app. Nothing for the library to do.

**Comment by Nominalista** [comment]
Do you know any examples with that solution ? You're right, it's not for library.

**Comment by Xstar97** [comment]
Its most likely a fragment thats implements...there are many tutorials on how to do so, but I made a tutorial while back with the navigation drawer....so here the link....https://github.com/Xstar97/Navigation-Drawer-Example

Go through that & see how to implement a fragment then try it through bottombar

**Comment by Xstar97** [comment]
if you have trouble...I wll make a new "tut" with the navigation drawer & bottombar as a base project for anyone to use
