### ISSUE TITLE
libc: Fatal signal 11 with android 4.1

### ISSUE THREAD

**Issue by StefanoGR** [roughike/BottomBar#225]
Maybe it's an emulator fault, but have you noticed any fatal signal using android 4.1? BottomBar works without issues on other versions.

**Comment by Xstar97** [comment]
show the code & xml of what you implemented if you need help still

**Comment by yombunker** [comment]
I will close this bug as there's not much to go with. If @StefanoGR has more information and wants to re-open feel free to do so. But, for now there is nothing we can do about this.
