### ISSUE TITLE
mapFragment issue with match_parent

### ISSUE THREAD

**Issue by TurKurT656** [roughike/BottomBar#226]
Hi, TnQ for this great library. There is a problem in my project.
I have an activity contains BottomBar. ( Bellow Activity's XML )

``` xml
<CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <!-- This is For Replacing Fragment -->
            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </NestedScrollView>
</CoordinatorLayout>
```

On one of BottomBars Tab has a mapFragment ( Bellow XML )

``` xml
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <fragment
        android:id="@+id/frag_map"
        android:name="com.google.android.gms.maps.SupportMapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>
```

The first problem is that when i trying to view this mapFragment its height collapses to a small height ( but in xml you see that its height is set to "match_parent").
I change the size of height manually (ex: 400dp. but We cant be sure that it fits the height of any device) and i can see map. But Second problem is that I cant scroll in vertical direction (in map).

**Comment by TurKurT656** [comment]
I have solved my own problem. if anyone has this problem, just remove the `NestedScrollView`

**Comment by Xstar97** [comment]
why don't you add the fragment via java code instead...?
Wouldn't that have been easier?

**Comment by TurKurT656** [comment]
@Xstar97 No, I want to put it in a circular reveal Layout. so i have 2 do it by xml

**Comment by Xstar97** [comment]
have you tried styling it & calling the style like this...
MapFragment.setStyle( MapFragment.STYLE_NORMAL, R.style.circular_reveal);

of course you need to create other xmls files to achieve the shape

**Comment by TurKurT656** [comment]
@Xstar97 no, can u help more? i didnt know what it does?

**Comment by Xstar97** [comment]
in your styles.xml
create something like this


	<style name="circular_reveal_layout">
        <item name="circular_reveal">@anim/circular_reveal</item>
        </style>
	
    <style name="circular_reveal" parent="Theme.AppCompat.Light.Dialog.Alert">
        <item name="android:windowAnimationStyle">@style/circular_reveal_layout</item>
		<item name="android:windowNoTitle">true</item>
		<item name="android:backgroundDimEnabled">false</item>
		<item name="android:windowIsFloating">true</item>
		<item name="colorAccent">#ffffff</item>
        <item name="android:textColorPrimary">#ffffff</item>
		</style>
Its really easy to create a shape.xml & reference in circular reveal layout

**Comment by Xstar97** [comment]
in the circular_reveal.xml that's place in anim...
add this

<?xml version="1.0" encoding="utf-8"?>
<shape
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">

   <solid 
       android:color="#666666"/>

   <size 
       android:width="120dp"
        android:height="120dp"/>
</shape>

**Comment by TurKurT656** [comment]
i will try this. TnQ

**Comment by Xstar97** [comment]
however if you still want to use <fragment
.../>
you can add this either to the <fragment/> or its actual xml(preferred)
 android:background="@drawable/circular_reveal_shape"
of course you will need to move the shape xml that you made to drawable folder

**Comment by Xstar97** [comment]
Did it work for you?

**Comment by TurKurT656** [comment]
@Xstar97 I've not tested yet. Tnq for ur concern. i will inform you when i tested this.
