### ISSUE TITLE
back button doesn't work with tab change

### ISSUE THREAD

**Issue by jy617lee** [roughike/BottomBar#228]
what I want to do is apply back button to tabs. 
for example, 
1. select tab1
2. select tab2
3. press back button
4. goes to tab1

I add fragments attatched to each tap to backstack when tab selection is changed. So when I press backbutton, fragments goes to the previous one while tab is still not changed. How can I solve this problem?

**Comment by jbrasted** [comment]
Navigating between tabs using the back button is explicitly something that should not happen, according to the Google Material Design standards.

https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-style

```
On Android, the Back button does not navigate between bottom navigation bar views.
```

Please see #80. @roughike states in this issue that he won't add logic to support this type of use case.
