### ISSUE TITLE
how to customize the icon in the selected BottomBarTab

### ISSUE THREAD

**Issue by chenyucheng97** [roughike/BottomBar#229]
I want to change the drawable icon in the selected BottomBarTab,What should I do ?

**Comment by Xstar97** [comment]
1. have you tried to set image via java code on the selected tab?
2. have you tried the first option but, run it from the ui thread?
3. could you explain why you want to do this?

**Comment by yombunker** [comment]
@chenyucheng97 This might be added in the next release or at least something close to what you need, but, there are no promises as to what day

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
