### ISSUE TITLE
How to apply the apperence of the second picture in README.md file?

### ISSUE THREAD

**Issue by wspl** [roughike/BottomBar#231]
![](https://raw.githubusercontent.com/roughike/BottomBar/master/demo_shifting.gif)

What's the method or prop to apply this apperence? Thanks!

**Comment by Nolanus** [comment]
Without having tried in on my own, but maybe "mapColorForTab()" which is also mentioned in the Readme example.

**Comment by roughike** [comment]
See the readme for [color changing tabs](https://github.com/roughike/BottomBar#those-color-changing-tabs-look-dope-howdoidodat) & [drawing under navbar](https://github.com/roughike/BottomBar#how-do-i-draw-it-under-the-navbar).
