### ISSUE TITLE
How to user only icons in bottom bar?

### ISSUE THREAD

**Issue by naveenkumarmallappa** [roughike/BottomBar#232]
I tried by setting empty for text but it given more space on bottom

**Comment by Xstar97** [comment]
the design specs states you HAVE to set a title & icon..since some icons are too ambiguous...so you need to show your users where they are navigating to

**Comment by charlesdurham** [comment]
> the design specs states you HAVE to set a title & icon..since some icons are too ambiguous...so you need to show your users where they are navigating to

Where does the design spec say that? The below quote implies to me that text is optional.

"Because bottom navigation actions are presented as icons, they should be used for content that can be suitably communicated with icons."
https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-style

**Comment by Xstar97** [comment]
I only glanced it, but hey I look it up again
you probably dont have to set a title if you are inflating a menu...but programmatically you can not(I think)
//design spec references text
Height:
56dp

Icon: 
24 x 24dp

Content alignment: 
Text and icon are centered horizontally within the view.

Padding:

6dp above icon (active view), 8dp above icon (inactive view)
10dp under text
12dp left and right of text
Text label:

Roboto Regular 14sp (active view)
Roboto Regular 12sp (inactive view)

**Comment by Xstar97** [comment]
if you really want to use just icons then dont declare title in the menu.xml
but, this can NOT be done programmatically IE bottombar gives us the option to set the menu from a xml file but also progammatically through java code which an xml is not needed
I believe its hard coded to contain both icon & title, but try to fiddle with both & see if it works for your case

**Comment by yombunker** [comment]
@charlesdurham if you don't set a text in the xml it will only show your icon, thou it will still take the space the text, it will just not have anything, is this what you meant? if not, feel free to re-open

**Comment by yashagw** [comment]
how to off the shifting mode with icon only

**Comment by sunegowtham** [comment]
To off the shifting mode though, you can get a reference to to navigation and call the disableShifMode function inside the onCreate method.
`BottomNavigationView navigation = findViewById(R.id.navigation);
  disableShiftMode(navigation);`
