### ISSUE TITLE
The layout of BottomBar is totally wrong when change the orientation from (initial) landscape to portrait

### ISSUE THREAD

**Issue by quanmltya** [roughike/BottomBar#233]
I think this is a serious issue of BottomBar!
How to reproduce this issue:
BottomBar set up with 5 items.
1. Start application in landscape mode. I mean initialized with landscape.
2. Rotate device to Portrait.
Now BottomBar only shows 3 items. In addition, the layout is wrong.
If anyone have the same problem, please comment here!

Landscape:
![device-2016-05-17-143747](https://cloud.githubusercontent.com/assets/12856132/15314649/669a8808-1c3d-11e6-9bec-46ede3cd879f.png)

Portrait:
![device-2016-05-17-143801](https://cloud.githubusercontent.com/assets/12856132/15314650/669b3992-1c3d-11e6-938f-339acf7d0fe7.png)

**Comment by quanmltya** [comment]
Did a look into the source code.
The mScreenWidth is set only one time when the BottomBar is initialized might be the root cause.

`private void init(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
...
mScreenWidth = MiscUtils.getScreenWidth(mContext);
...
}`

Maybe we need to update this variable each time the size/layout of BottomBar change.
Possibility onSizeChanged().
Any idea for this issue?

**Comment by charlesdurham** [comment]
Do you have `android:configChanges="orientation|screenSize"` on your activity? Other android widgets have similar oddities in situations like this. The one example I can think up off the top of my head is the misplacement of the navigation icon in a toolbar after rotation.

**Comment by quanmltya** [comment]
Yes I have android:configChanges="orientation|screenSize" in the manifest.
As I commented above, the same situation occurs if you switch from initial portrait to landscape.
In initial portrait, the BottomBar takes the width of screen as its width and calculates the size for each items.
After rotation, the variable mScreenWidth has not been updated, so when device is in landscape mode, the BottomBar still takes the old value of mScreenWidth, not the new screen width in landscape mode. The will lead the space at the start and end of BottomBar.

**Comment by Lintom** [comment]
Hi. How to fix this issue?

**Comment by quanmltya** [comment]
Still have no solution... Hope talent developers can fix this issue and merge into master.
I think this is a major bug!

**Comment by Reline** [comment]
I've done some fiddling around with this issue and came to the conclusion that the BottomBar **DOES NOT** readjust its size when the corresponding activity has
```
android:configChanges="orientation|screenSize"
```
but any other value will work just fine.

I've had some trouble with using fragments in coordination with this due to configuration changes recreating fragments if the `android:configChanges` is not set to the above value, so I'll be looking into a fix for that.

**Comment by renaud-myatlas** [comment]
I have the exact same problem and have no idea how to fix it.

Does anyone know how to initialise the bar as if he screen is in portrait mode ? (no matter if it's in landscape or portrait) at least it will provide a solution for having all the tabs fitting in the bar at all time.

Thank you

**Comment by quanmltya** [comment]
No one fixes this issue.
If I have time, I will try to investigate it and provide the fix.

**Comment by xtien** [comment]
If you don't put 
`            android:configChanges="orientation|screenSize"
`
in your manifest, the bottombar properly scales with the orientation.

**Comment by roughike** [comment]
This is now fixed thanks to merging a [PR that changed the width calculations to use the BottomBar width as a reference instead of the screen width.](https://github.com/roughike/BottomBar/commit/742b1d7cde3158f4b90955e24c137e7931e92ed1)
