### ISSUE TITLE
Feature Request: Unselectable Items

### ISSUE THREAD

**Issue by mgursch** [roughike/BottomBar#236]
Hi

thanks for this amazing library. I have following feature request:

I want to click one of my bottom bar tabs and open an external browser (or maybe chrome custom tabs) without changing the bottom bar state.

There are 4-5 tabs. One of them should fire fire the OnTabSelectedListener but should not update change the selected states.

Is this a feature you will implement? 

Thanks a lot

**Comment by TostF** [comment]
This feature already exists but the method is private :C
Don't know why tho - propably might throw some errors.

**Comment by mgursch** [comment]
Would be nice to be allowed to access it :)

**Comment by charlesdurham** [comment]
> This feature already exists but the method is private :C
> Don't know why tho - propably might throw some errors.

If you want to get hacky you could use reflection to invoke the private method. http://stackoverflow.com/a/880400/3474528

**Comment by yombunker** [comment]
The latest merge to master includes what you want, is called OverrideTabSelectionListener, you receive the current tab and the tab that was selected and you are given the opportunity to prevent the switch and you can do whatever you need to do based on the tab that was selected.
