### ISSUE TITLE
NullPointerException while switching tabs and have bottom bar badge.

### ISSUE THREAD

**Issue by chauhanmahesh** [roughike/BottomBar#238]
Found a issue where the BottomBar.java throws a NullPointerException when we switch the tabs. This occurs when we have a BottomBar badge on some tabs.
Use case:
- Have 4 tabs
- Show BottomBar badge at tab 1 (0 based index)
- Start the application (It starts from tab 0)
- Switch to tab 1
- Switch back to tab 0

It crashes in handleBadgeVisibility() of BottomBar.java
The crash exists in 
if (oldBadge.getAutoShowAfterUnSelection()) {
                oldBadge.show();
            } else {
                oldBadge.hide();
            }
and 
BottomBarBadge newBadge = (BottomBarBadge) mOuterContainer
                    .findViewWithTag(mBadgeMap.get(newPosition));
            newBadge.hide();

**Comment by Nolanus** [comment]
Maybe you can include the beginning part of the stracktrace, that allows the developer to more easily understand what caused the error and how it got to that call.

**Comment by fschrofner** [comment]
I ran into the same issue, see the stacktrace here:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
at com.roughike.bottombar.BottomBar.handleClick(BottomBar.java:1153)
at com.roughike.bottombar.BottomBar.access$000(BottomBar.java:57)
at com.roughike.bottombar.BottomBar$1.onClick(BottomBar.java:751)
at android.view.View.performClick(View.java:5280)
at android.view.View$PerformClick.run(View.java:21239)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:234)
at android.app.ActivityThread.main(ActivityThread.java:5526)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by grestuccia1** [comment]
The problem is when you run twice makeBadgeForTabAt

**Comment by fschrofner** [comment]
Hmm might be.. how am I supposed to update the count of the badge then, if not by calling makeBadgeForTabAt again?

**Comment by mohit-trantor** [comment]
I am also facing the same issue, Did you find any solution?

**Comment by fschrofner** [comment]
I didn't spend any time looking for a solution yet, so unfortunately: no.

**Comment by chauhanmahesh** [comment]
While creating the Bottom bar badges using "makeBadgeForTabAt()", keep hold of the instance of BottomBarBadge and whenever you need to update the count, just call "badge.setCount(<newCount>)".

Just to show, below could be the implementation (pseudo code):
```
BottomBarBadge badge = mBadges.get(id);
if (badge == null) { // First Time
        badge = bar.makeBadgeForTabAt(id, "#FF0000", 
        badge.setAutoShowAfterUnSelection(true);
        badge.setAutoHideWhenSelection(false);
        mBadges.put(id, badge);
}

// Whether we created new badge or its already existed one, update the count now.
if (badge != null) {
      badge.setCount(badgeCount);
      badge.show();
} 
```

**Comment by fschrofner** [comment]
Works perfectly fine, thanks!
