### ISSUE TITLE
can we add only title of menu item 

### ISSUE THREAD

**Issue by sdubey0201** [roughike/BottomBar#239]
is there any way where i can set only title of menu item not icon

**Comment by Xstar97** [comment]
Yes...just dont include the icon in menu.xml
however programmatically no...which I think has been hardcoded to have an icon
You can set bottombar from a menu or programmatically in java(no xml is needed)

**Comment by jbrasted** [comment]
Yes, you don't need to include an icon if you don't want to. Just set the `Drawable` parameter to null.

```Java
BottomBar bottomBar = BottomBar.attachShy(coordinatorLayout, null, savedInstanceState);
bottomBar.setItems(new BottomBarTab(null, "Fred"), new BottomBarTab(null, "Bill"), new BottomBarTab(null, "Bob"));
```

<img width="321" alt="screen shot 2016-05-24 at 2 15 56 pm" src="https://cloud.githubusercontent.com/assets/5277042/15520232/15ecf56c-21ba-11e6-9435-8a3f54e4804e.png">

**Comment by jboxx** [comment]
have same issue.  if setting on xml without including icon or set drawable parameter to null just make fill the icon to something transparent. I need to make the icon gone, only title of menu item. So how I can do that?

**Comment by yombunker** [comment]
as other people has said before me, if you don't set an icon in the xml configuration it will only show the text, but, keep in mind that what it will happen is that the text will move up and take the place of the icon.
