### ISSUE TITLE
error when switch from 1.0.1 to 1.0.3

### ISSUE THREAD

**Issue by zhangzhzh** [roughike/BottomBar#24]
using 1.0.1, my app runs well, except the ugly top border.
after switch to 1.0.3, and add the statement:mBottomBar.hideShadow(), just like below:
`mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar.hideShadow();
        mBottomBar.setItemsFromMenu(R.menu.menu_bottombar, new OnMenuTabSelectedListener() {
            @Override
            public void onMenuItemSelected(int resId) {
                switch (resId) {
                    case R.id.bottomBarHome:
                        displayView(0);
                        break;`
the ugly top border appear above the toolbar:
before:
<img width="280" alt="2016-03-18 12 23 49" src="https://cloud.githubusercontent.com/assets/1575989/13868554/2b521c82-ed05-11e5-9616-538ae928e826.png">
after:
<img width="282" alt="2016-03-18 12 22 33" src="https://cloud.githubusercontent.com/assets/1575989/13868556/34782734-ed05-11e5-8904-0f45163d8c68.png">

next, when click the bottom icon, error occurs:
<img width="1060" alt="2016-03-18 12 31 33" src="https://cloud.githubusercontent.com/assets/1575989/13868572/6827143c-ed05-11e5-9e37-79d5b6301c2e.png">

the code have been posted in the [issue:](https://github.com/roughike/BottomBar/issues/3)
How to style top border? #3

**Comment by roughike** [comment]
Try updating to 1.0.7, it should fix that force close.
