### ISSUE TITLE
as I can keep the colors of three items when using four items?

### ISSUE THREAD

**Issue by alf182** [roughike/BottomBar#240]
Its possible keep the bottombar style when use 4 items

**Comment by Xstar97** [comment]
So you want the normal bottombar 3 button color style when using four?

**Comment by alf182** [comment]
yes

**Comment by Xstar97** [comment]
//This disables transparent Navigation Bar
mBottomBar.noNavBarGoodness();

//Show all titles even when there's more than three tabs.
mBottomBar.useFixedMode();

// Set the color for the active tab. Ignored on mobile when there are more than three tabs.
mBottomBar.setActiveTabColor("#009688");

//optional:
number of tabs minus 1...so in your case remove "n-1" and replace it with 3 if the other options did not work
mBottomBar.setMaxFixedTabs(n-1);

**Comment by Odaym** [comment]
useFixedMode() method is not available on the bottomBar, any idea why? Not in BottomBar.java either

**Comment by Xstar97** [comment]
what?
use it after you call attach....
// Show all titles even when there's more than three tabs.
mBottomBar.useFixedMode();

**Comment by MattMcComb** [comment]
@Odaym useFixedMode possibly isn't available in the version of the library you are using...?  Try including version 1.3.4 in your project dependencies.

`compile "com.roughike:bottom-bar:1.3.4"`

**Comment by seasonyuu** [comment]
@MattMcComb Why had to use `mBottomBar.noNavBarGoodness();` ??

**Comment by Xstar97** [comment]
OP asked to have the default UI(3 tabs original UI) which technically means OP should use mBottomBar.noNavBarGoodness();
but OP doesnt have to...it was just a suggestion

**Comment by seasonyuu** [comment]
@Xstar97 I read the spec of Bottom Navigation again and over again , I hadn't found any words about the relation between item counts with translucent navigation bar . There is a coincidence that every picture in the spec which has more than 3 items' bottom bar would use colorful background.


PS ; I don't know what the meaning of 'OP' is ...

**Comment by Xstar97** [comment]
OP means "original Poster"

**Comment by seasonyuu** [comment]
Thanks for your explain , I had resolved the problem by adding two line of code , and make a pull request ( It doesn't matter if roughike will merge it , I just want the one who need can see the commit , maybe I should put it into issue =_= , whatever )

**Comment by Odaym** [comment]
That did the trick Matt, I was working with an older version

**Comment by alf182** [comment]
Only want four options with the color white of bottom bar

**Comment by ubaierbhat** [comment]
I only have three items and the colors don't work :( .. any idea how to fix this

**Comment by roughike** [comment]
Now less pain free when using the versions 2.0 and up.
