### ISSUE TITLE
Badge disappear if I select the tab

### ISSUE THREAD

**Issue by chauhanmahesh** [roughike/BottomBar#245]
My requirement is that, the notification badge should be shown even when I select that particular tab. By looking at the documentation, setAutoShowAfterUnSelection() seems to be the API to acheive this. However, even when I set it to "true" I am finding the same issue.

**Comment by westlinkin** [comment]
I made a pull request(#247) to fix this issue, you can wait for @roughike to merge this PR or simply pull the code.

**Comment by ivandiazmolina** [comment]
Is it fixed already? I have this error in version 2.0.2

**Comment by eul** [comment]
The same problem (.

**Comment by yombunker** [comment]
This is fixed in the 2.1.2 version that was released this week, feel free to update and enjoy the new version.
