### ISSUE TITLE
toggle tablet mode programmatically

### ISSUE THREAD

**Issue by Ydcool** [roughike/BottomBar#248]
It seems that tablet mode only determined by `noTabletGoodness` and the value `bb_bottom_bar_is_tablet_mode` in `values-sw600dp-v13`, will it be possible to `setTabletMode` programmatically  in the future? Because I want to set BottomBar to left side for landscape layout.

**Comment by Talklesscodemore** [comment]
I have already forked and developed this feauture I will create a pull request for this

**Comment by roughike** [comment]
It's now possible with 2.0 and up.

[See the Readme](https://github.com/roughike/BottomBar#what-about-tablets)
