### ISSUE TITLE
How to change tabs icon  ?

### ISSUE THREAD

**Issue by majidpersian** [roughike/BottomBar#249]
Is there a way to change tab icon ? I can not find any method to change it !!!

It will be great if we can change an icon for the BottomBar at any time.
Would be awesome if you implement it.

Thanks

**Comment by Nolanus** [comment]
There multiple resources to check out to understand, how you can set the menu items and specify the icons with them:
- Wiki: https://github.com/roughike/BottomBar/wiki/Getting-Started
- Readme: https://github.com/roughike/BottomBar/blob/master/README.md#i-dont-want-to-set-items-from-a-menu-resource
- If you want to "change the icon" if it got tabbed/selected: Look into existing "issues": https://github.com/roughike/BottomBar/issues/118, https://github.com/roughike/BottomBar/issues/153

**Comment by majidpersian** [comment]
"Look into existing "issues": #118, #153"

I did not find any solution in these pages :(

@roughike said in these pages: Changing the icon is could be confusing to the user, and it's not endorsed in the Guidelines.

**Comment by Nolanus** [comment]
Right, so there won't be any "official" support for that. However, it is still possible to "manually" grab the view from the view hierarchy and change the drawable. Downside of course is that it might break due to updates of the library or any dependency.

**Comment by majidpersian** [comment]
"However, it is still possible to "manually" grab the view from the view hierarchy and change the drawable"

How do I do it ? Please give me a sample code

**Comment by Xstar97** [comment]
run code on the UIthread & if the image is view change it from an if else statement
I have not tried this, but may help you

**Comment by majidpersian** [comment]
Finally, to change the tab icon by creating two BottomBar and switch between them using logical Flag, my problem was solved partially.

To do this i have written below code in which the two BottomBar created with deffernt icons and switch between them in onTabReSelected event

```
public class MainActivity extends AppCompatActivity implements  OnTabClickListener{
        protected void onCreate(Bundle savedInstanceState) {
           mBottomBarA = BottomBar.attach(mLayout, savedInstanceState);
           mBottomBarB = BottomBar.attach(mLayout, savedInstanceState);
           barTabsA = new BottomBarTab(icon_1, title_1)
           barTabsB = new BottomBarTab(icon_2, title_2)
           mBottomBarA.setItems(barTabsA);
           mBottomBarB.setItems(barTabsB);
           mBottomBarA.setOnTabClickListener(this);
           mBottomBarB.setOnTabClickListener(this);
           mBottomBarB.hide();
      }

    @Override
    public void onTabReSelected(int position) {
        if (flag==false){
            mBottomBarA.hide();
            mBottomBarB.show();     
            flag=true;
        }else{
            mBottomBarB.hide();
            mBottomBarA.show();
           flag=false;
        }

}
```

**Comment by yombunker** [comment]
If you really want to do this you can get a reference to the BottomBarTab by using any of the provided methods in the latest version, and from there you can get access to the view and do whatever you feel is necessary with them. I'll close it for now.

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
