### ISSUE TITLE
Badge problem

### ISSUE THREAD

**Issue by EpsilonOrionis** [roughike/BottomBar#250]
I'm trying to set a badge in response to an event, but it is ellyptical (it wraps the number without leaving a little padding on the number sides to create a circle drawable). Anyway badge works as it is supposed to do (in my case) only if I set the badge below the BottomBar tabs definition ect... . Another problem that I encountered is that if I want to add a new badge there's no machanism that checks if that tab has already a visible badge. It should check if it is visible and update the number inside it, instead of adding another badge next to the exsiting one overlapping it.

**Comment by Xstar97** [comment]
I had a similiar issue with badge however it when I rotated my device the same badge was added on top of another one... which messed up the UI...however I fixed my issue, but in your case I don't have the knowledge to help you

**Comment by Xstar97** [comment]
I found this from another bug issue...I dont know if this will help or not..
-AbhishekM473
For now you can do this...
mBottomBar.refreshDrawableState();
after you use the mBadge.setCount() method :)
