### ISSUE TITLE
Why different effect

### ISSUE THREAD

**Issue by drduan** [roughike/BottomBar#252]
![1](https://cloud.githubusercontent.com/assets/7875572/15542517/b1d7e4c8-22c3-11e6-8677-3a28aab2c5da.jpg)

**Comment by Xstar97** [comment]
The UI is different because of the design spec...however you can change this & make the tablet have the same UI effect as the mobile by using this:
// Disable the left bar on tablets and behave exactly the same on mobile and tablets instead.
mBottomBar.noTabletGoodness();

**Comment by drduan** [comment]
thank you

**Comment by Xstar97** [comment]
If your issue now fixed... Could you add this to your title "[SOLVED]" & close this issue?
