### ISSUE TITLE
Flicker When Changing Tabs

### ISSUE THREAD

**Issue by jd-alexander** [roughike/BottomBar#253]
I noticed that I'm experiencing a flicker at times when I switch tabs, that actually trigger the switch of fragments. It doesn't take place every time but happens with every other attempt. 

This is the way I am doing the navigation. 

`

private void navigateToFragment(Fragment fragment)
 {
    FragmentManager fragmentManager = getSupportFragmentManager();
    FragmentTransaction transaction = fragmentManager.beginTransaction();
    transaction.replace(R.id.main_content, fragment);
    transaction.commit();
  }

 private void setupBottomBar(Bundle savedInstanceState) {
    bottomBar = BottomBar.attachShy(coordinator,mainContent,savedInstanceState);
    bottomBar.useFixedMode();

```
bottomBar.setItemsFromMenu(R.menu.bottombar_menu, new OnMenuTabClickListener() {
    @Override
    public void onMenuTabSelected(@IdRes int menuItemId) {

        switch (menuItemId)
        {
            case R.id.all_tab:
                navigateToFragment(new AllFragment());
                break;

            case R.id.yours_tab:
                navigateToFragment(new DispatchFragment());
                break;

            case R.id.drafts_tab:
                navigateToFragment(new DraftsFragment());
                break;


            case R.id.submissions_tab:
                navigateToFragment(new SubmissionsFragment());
                break;
        }
    }`
```

**Comment by pszychiewicz** [comment]
+1

**Comment by vibinr** [comment]
Same here..was wondering if this has something to do with my fragment code.

**Comment by jd-alexander** [comment]
For me this flicker was taking place on my emulator but stopped once I used a real device.

**Comment by yombunker** [comment]
I close this issue for now, but, feel free to re-open it if you still experience it in the latest version, and we can have a look at it. Also, make sure that this is not happening because you are doing to much work on the UI Thread when you are switching tabs.
