### ISSUE TITLE
Change the color and height of the bottombar top margin/dvider

### ISSUE THREAD

**Issue by midhunm45** [roughike/BottomBar#255]
I like to know if i can change the color and height of the bottombar's top margin/divider. I'm talking about the divider between bottombar and the our fragment

**Comment by alvarlagerlof** [comment]
There shoudn't be one

**Comment by midhunm45** [comment]
Actually there is one, it's a drawable xml file (bb_bottom_bar_top_shadow.xml). I edited that file to make custom top divider. Sorry, I forgot to close the issue..
Anyway, thanks for your response @alvarlagerlof
