### ISSUE TITLE
can not understand the README

### ISSUE THREAD

**Issue by DanteAndroid** [roughike/BottomBar#26]
In **Can it handle my Fragments and replace them automagically when a different tab is selected?**, codes are:

```
mBottomBar.setFragmentItems(getSupportFragmentManager(), R.id.fragmentContainer,
    new BottomBarFragment(SampleFragment.newInstance("Content for recents."), R.drawable.ic_recents, "Recents"),
    new BottomBarFragment(SampleFragment.newInstance("Content for favorites."), R.drawable.ic_favorites, "Favorites"),
    new BottomBarFragment(SampleFragment.newInstance("Content for nearby stuff."), R.drawable.ic_nearby, "Nearby")
);
```

But in **Separate BottomBars for individual Fragments**, they are:

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)     {
    View view = inflater.inflate(R.layout.my_fragment_layout, container, false);
    // initialize your views here

    BottomBar bottomBar = BottomBar.attach(view, savedInstanceState);
    bottomBar.setItems(
        new BottomBarTab(R.drawable.ic_recents, "Recents"),
        new BottomBarTab(R.drawable.ic_favorites, "Favorites"),
        new BottomBarTab(R.drawable.ic_nearby, "Nearby")
    );

    // Important! Don't return the view here. Instead, return the bottomBar, as it already contains your view.
    return bottomBar;
}
```
   
So if I wanna use Bottom bars connected with 4 different fragments, what should I use?

BTW, you guys are really fast for this repository.

**Comment by DanteAndroid** [comment]
I think maybe I misunderstand (forgive my poor English), is it 

> Separate BottomBars for individual **Fragment**?

**Comment by feijilbj** [comment]
@DanteAndroid   Download and try it out

**Comment by roughike** [comment]
The first one.

The second example means that whenever your fragment changes, the whole visible BottomBar changes to to a completely different one. Somebody asked me how to do it.

I'll remove that from the Readme, as that's just creating unnecessary confusion and most people won't (and they probably shouldn't) use it.

Thanks for asking.
