### ISSUE TITLE
Not Hiding while Scrolling when Scrolling Item is Viewpager

### ISSUE THREAD

**Issue by Kiran89kumar** [roughike/BottomBar#261]
Bottom bar is not getting hide when the scrolling content is viewpager and the viewpager fragment is having Toolbar.

**Comment by golontico** [comment]
ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close){
            @Override
            public void onDrawerOpened(View drawerView){

                super.onDrawerOpened(drawerView);
                mBottomBar.hide();
            }
            @Override
            public void onDrawerClosed(View drawerView){

                super.onDrawerClosed(drawerView);
                mBottomBar.show();
            }

        };

**Comment by FrancisLawlor** [comment]
Try putting the NestedScrollView inside the ViewPager instead of the other way around.
