### ISSUE TITLE
How to display text only for selected tab? 

### ISSUE THREAD

**Issue by ronaldo-getreveel** [roughike/BottomBar#264]
How can I display the tab's label only when the tab is selected as in the image bellow? 

![image](https://cloud.githubusercontent.com/assets/15217193/15681491/ff76b7c2-271e-11e6-95c1-328d4e0ec078.png)
 
As present [here](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-usage).

**Comment by ronaldo-getreveel** [comment]
Its working properly when there are more than 3 tabs. I'm  looking for the same behavior when there are 3 tabs.

**Comment by RatHN** [comment]
mBottomBar.setMaxFixedTabs(n-1);

where n is the number of tabs you have.

**Comment by sarang1996** [comment]
Its not working i think because i have 5 tabs and am not able to do that think help if possible. @RatHN @ronaldo-getreveel

**Comment by roughike** [comment]
It's not restricted in the versions 2.0 and up anymore.

[See the readme](https://github.com/roughike/BottomBar#all-customization-options)
