### ISSUE TITLE
Check bar visibility

### ISSUE THREAD

**Issue by TostF** [roughike/BottomBar#270]
We've got `hide()` and `show()` also `toggleShyVisibility()` and `isShy()` both protected tho.
How are we suppose to check the visibility state of `BottomBar` ?

**Comment by Nolanus** [comment]
I once experimented with `if (((CoordinatorLayout.LayoutParams) mBottomBar.getLayoutParams()).getBehavior() != null) {`, it should be true if the bottombar is not visible, but not sure whether it still works or whether it's reliable at all.

**Comment by JonathanMerritt** [comment]
if (this._bottombar.getBar().isShown) this._bottombar.hide();
else this._bottombar.show();

**Comment by roughike** [comment]
Although there's no show / hide methods in the new version (yet), you can just change the visibility like any other View now.
