### ISSUE TITLE
how can I change the default colors?

### ISSUE THREAD

**Issue by cmonfortep** [roughike/BottomBar#274]
How can I set a default background color for the bottom bar? By default is set to `R.attr.colorPrimary`, is there any way to set another color?

And also, the icons and text are always white. How could I change this default color?

I was reading the [guidelines](https://www.google.com/design/spec/components/bottom-navigation.html) and the color of the icons and text don't have to be white, they have to use the app's primary color.

> Color: Tint the active icon with the app’s primary color. Use black or white if the bottom navigation bar is already colored.

**Comment by alanfagner** [comment]
Also I wonder if it is possible to do this ?

**Comment by MerveGencer** [comment]
Hi, I couldn't manage to do it, also. My theme is light, my icons are black and my bottom bar's icons turn white so they become unseen. I want my original icon colors which is black.

**Comment by ubaierbhat** [comment]
I have the same problem. I only have 3 tabs. My theme is same as in the sample. and I tried to use mapColorForTab to change color of tabs but my bottom bar always has a white color. My settings are same as shown in the sample code but the colors won't change :(

**Comment by eul** [comment]
As ugly workaround you can override `<color name="white">#3b5998</color>` in your `colors.xml`. this will change icon and titles color (

**Comment by roughike** [comment]
You can just set the backgroudn color by ```android:background``` XML attribute in the newest version.
