### ISSUE TITLE
hide/show - how and from where to call them?

### ISSUE THREAD

**Issue by rmnbhl** [roughike/BottomBar#278]
What Is the right approach to use these methods? I am in situation where I have recyclerView with fast scroll library with alphabet indexes. Library is using **scrollToPosition** and does not fire **onScrolled** listener. So I have to implement my own logic to achieve shy show/hide behavior of bottomBar. I tried to call hide/show from everywhere but I am still keep getting this error:

> java.lang.IllegalArgumentException: The view is not associated with BottomNavigationBehavior
>                                                                                at com.roughike.bottombar.scrollsweetness.BottomNavigationBehavior.from(BottomNavigationBehavior.java:124)
>                                                                                at com.roughike.bottombar.BottomBar.toggleShyVisibility(BottomBar.java:1010)
>                                                                                at com.roughike.bottombar.BottomBar.setBarVisibility(BottomBar.java:987)
>                                                                                at com.roughike.bottombar.BottomBar.hide(BottomBar.java:420)

All the views from where I called these methods are children of scroll content. While debug I can see that **((CoordinatorLayout.LayoutParams) params)
                .getBehavior() returns null**.
Here is my menuTabClickListener:

``` java
mBottomBar.setItemsFromMenu(R.menu.bottom_tabs, new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId) {
                temp = (ViewGroup) findViewById(R.id.main_view);
                temp.removeAllViews();
                switch (menuItemId) {
                    case R.id.bottomBarFestival:
                        if (fest_view == null)
                            fest_view = (FestivalViewWithViewPager) inflater.inflate(R.layout.activity_main_festivals, temp, false);
                        temp.addView(fest_view);
                        break;
                    case R.id.bottomBarArtists:
                        if (artists_view == null)
                            artists_view = (BandsViewWithViewPager) inflater.inflate(R.layout.activity_main_band, temp, false);
                        temp.addView(artists_view);
                        break;
                    case R.id.bottomBarCalendar:
                        if (calendar_view == null)
                            calendar_view = (CalendarView) inflater.inflate(R.layout.activity_main_calendar, temp, false);
                        temp.addView(calendar_view);
                        break;
                    case R.id.bottomBarMap:
                        if (map_view == null)
                            map_view = (MapView) inflater.inflate(R.layout.activity_main_map, temp, false);
                        temp.addView(map_view);
                        break;
                    case R.id.bottomBarDashboard:
                        if (dashboard_view == null)
                            dashboard_view = (DashboardView) inflater.inflate(R.layout.activity_main_dashboard, temp, false);
                        temp.addView(dashboard_view);
                        break;
                    default:
                        throw new IllegalArgumentException("Unknown bottom bar item id !");
                }
            }
```

Any ideas appreciate, thanks! 
Cheers

**Comment by badams299** [comment]
I am also getting that Exception. I am trying to call hide on the BottomBar from my activity that contains the bar. Did you find a solution?

**Comment by rmnbhl** [comment]
No, I did not so we have to drop show/hide behavior for whole application. pitty

**Comment by roughike** [comment]
With the versions 2.3.0 and up, in shy mode, you can show / hide the bar as follows:

```java
// Show:
bottomBar.getShySettings().showBar();

// Hide:
bottomBar.getShySettings().hideBar();
```
