### ISSUE TITLE
Hidding BottomBar without scroll.

### ISSUE THREAD

**Issue by abramov73** [roughike/BottomBar#279]
How to hide BottomBar when RecyclerView little smaller than height of screen and BottomBar overrides last element in list.
mBottomBar.hide() doesn't work.
Elements fill all space on the screen excepting space under BottomBar. 
How to solve this issue without adding more elements?

**Comment by Cary-Ciccone** [comment]
pretty sure you have to do mBottomBar.getBar().hide()

**Comment by roughike** [comment]
With the new version you can just show / hide it just like any other View.
