### ISSUE TITLE
android flyme adaptation problems

### ISSUE THREAD

**Issue by wogenhaosini** [roughike/BottomBar#28]
![image](https://cloud.githubusercontent.com/assets/10138880/13872576/9a0ec848-ed26-11e5-9177-56975bcc216f.png)

**Comment by roughike** [comment]
What version are you using? Newest version is 1.0.8. The library has already been updated several times and I thought this was fixed.

However, if you have the latest version but the detection doesn't still work, you can call ```bottomBar.noNavBarGoodness()``` to disable the bigger height.
