### ISSUE TITLE
Does not detect whether device have soft navigation bar or not

### ISSUE THREAD

**Issue by norton0000** [roughike/BottomBar#29]
If no detect whether android device have soft navigation bar or not then the height of bottom bar will abnormal.
Modification:
BottomBar.java
navBarMagic() {
  ...
            boolean hasMenuKey = ViewConfiguration.get(activity).hasPermanentMenuKey();
            boolean hasBackKey = KeyCharacterMap.deviceHasKey(KeyEvent.KEYCODE_BACK);
            final int navBarHeight;

            if(!hasMenuKey && !hasBackKey) {
              if (navBarIdentifier > 0) {
                navBarHeight = res.getDimensionPixelSize(navBarIdentifier);
              } else {
                navBarHeight = MiscUtils.dpToPixel(activity, 48);
              }
            } else {
              navBarHeight = 0;
            }
  ...
}

**Comment by roughike** [comment]
What version are you using? Newest version is 1.0.8. The library has already been updated several times and I thought this was fixed.

However, if you have the latest version but the detection doesn't still work, you can call ```bottomBar.noNavBarGoodness()``` to disable the bigger height.
