### ISSUE TITLE
A newbie question. Connect Activity with bottom bar item.

### ISSUE THREAD

**Issue by JEKos** [roughike/BottomBar#291]
Hi,
How can I connect different activities with the bottom bar, for example if I press  the second bar item, then will go to a different activity without losing the menu bar at the bottom.
I don't want just simple to change e.g a textView on the same activity like your demo, but to go on new activity that I have create already.

```
public void onMenuTabSelected(@IdRes int menuItemId) {
                if (menuItemId == R.id.bottomBarItemOne) {
                    // What need to write here to go to new activity without losing the bottom bar menu?
                }
            }
```

**Comment by JonathanMerritt** [comment]
Do you have a wrapper activity that holds the BottomBar on its content view?

Then have the clicks start your individual tab activities.

That seems a little overboard though, any reason your not just inflating fragments?

**Comment by JEKos** [comment]
I did it!
With fragments,here : 
```
public void onMenuTabSelected(@IdRes int menuItemId) {
                if (menuItemId == R.id.bottomBarItemOne) {
                    // The user selected item number one.
                    FirstFragment firstFragment = new FirstFragment();
                    getSupportFragmentManager().beginTransaction().replace(R.id.content_id,firstFragment).commit();
                }
```

content_id is the id from the content_main.xml file
