### ISSUE TITLE
Unknown white empty action bar

### ISSUE THREAD

**Issue by yerenutku** [roughike/BottomBar#294]
When you are using toolbar,  you will get an empty unknown, annoying, non-removable, white action bar. Its look terrible. Far as i know this bug happens in LG G3 5.0.0 . 

Solution: This will happen if you not call the **.noTopOffset()** function. It takes my 3 days to solve this.

**Comment by markoslo** [comment]
This is not helping for me. The white action bar is still there.

**Comment by yerenutku** [comment]
I run my codes in nexus 5x but its working good. Here is my flow:
```
mToolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(mToolbar);
        mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar.noNavBarGoodness();
        mBottomBar.noTopOffset();
        mBottomBar.noTabletGoodness();
        mBottomBar.noResizeGoodness();
```
Can you share your flow too

**Comment by SebLorea** [comment]
+1 for useOnlyStatusBarTopOffset()

**Comment by roughike** [comment]
There's no ugly white space on top anymore. Those nasty "no*Goodness" and *offset methods are (thankfully) gone in the newest versions.
