### ISSUE TITLE
Its a bit laggy when selecting tabs since 1.3.7+

### ISSUE THREAD

**Issue by Xstar97** [roughike/BottomBar#295]
Since version 1.3.7 & now 1.3.9 it lags a lot on sdk22 or lower...but works well on sdk23(Testing device SDK23 Shield TV and SDK22 LGK7)
So at first I thought I was using too many dependencies/useless code..so got rid of most of them...However it still lags...even If i am switching to a tab that has very light code in it.
 
Also I havent check if this was fixed yet, but since 1.x.x or something I have to use noNavbarGoodness();
If I dont on Lollipop the view is moved passed my toolbar & the snackbar is moved up too.

**Comment by roughike** [comment]
Should've been fixed by now in the latest versions.
