### ISSUE TITLE
set five tab as three tab in simply color (In urgent if possible)

### ISSUE THREAD

**Issue by sarang1996** [roughike/BottomBar#299]
I want to set five tabs in bottombar like you put three tabs in blue color but its creating full background which i don't want.so, if you have any solution for that then comment please! @roughike

**Comment by alvarlagerlof** [comment]
It's not men to show all the three colors individually they should fill the whole view when clicked

**Comment by sarang1996** [comment]
yeh i actually don't want to fill the whole view, i want simple just icon and textview is highlight when clicked.if possible through this lib. @alvarlagerlof

**Comment by alvarlagerlof** [comment]
Aha, thought you wanted a background too

**Comment by roughike** [comment]
Now it's possible! The newest version doesn't force you to have a primary background and shifting tabs if you have more than three.
