### ISSUE TITLE
How to style top border?

### ISSUE THREAD

**Issue by zhangzhzh** [roughike/BottomBar#3]
the top border is ugly, how to style it, such as color, size, and so on? 

<img width="270" alt="2016-03-17 08 56 45" src="https://cloud.githubusercontent.com/assets/1575989/13833180/45ba71b0-ec1e-11e5-9249-96494dda0926.png">

**Comment by LiuDeng** [comment]
download the source code to read

**Comment by roughike** [comment]
@zhangzhzh 
How did you get it to look like that? It would be helpful if you provide some code to duplicate your problem so I can fix it.

**Comment by AlexLionne** [comment]
its about the shadow, there is not methods in support libs to implement it as shadow(`eleveation`) instead like this ? I mean like a toolbar elevation

**Comment by roughike** [comment]
Yes there is, but the direction of the shadow can't be changed.

**Comment by zhangzhzh** [comment]
@roughike 
I  just set the LinearLayout's android:background to black in the activity_main.xml:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="#000000"
    tools:context=".activity.MainActivity">

    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:orientation="vertical">

        <include
            android:id="@+id/toolbar"
            layout="@layout/toolbar" />
    </LinearLayout>

    <FrameLayout
        android:id="@+id/container_body"
        android:layout_width="fill_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>

</LinearLayout>

menu.xml:

<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">

    <item
        android:id="@+id/bottomBarHome"
        android:icon="@drawable/ic_home"
        android:title="@string/nav_item_home" />
    ......
</menu>

MainActivity.java:

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mToolbar = (Toolbar) findViewById(R.id.toolbar);

        setSupportActionBar(mToolbar);
        getSupportActionBar().setDisplayShowHomeEnabled(true);

        mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar.setItemsFromMenu(R.menu.menu_bottombar, new OnMenuTabSelectedListener() {
            @Override
            public void onMenuItemSelected(int resId) {
                switch (resId) {
                    case R.id.bottomBarHome:
                        displayView(0);
                        break;
                    ...
                    default:
                        displayView(0);
                        break;
                }
            }
        });

        displayView(0);
    }

private void displayView(int position) {
        Fragment fragment = null;
        switch (position) {
            case 0:
                fragment = new HomeFragment();
                break;
            ......
            default:
                fragment = new HomeFragment();
                break;
        }

        FragmentManager fragmentManager = getSupportFragmentManager();
        FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
        fragmentTransaction.replace(R.id.container_body, fragment);
        fragmentTransaction.commit();
    }

**Comment by roughike** [comment]
@zhangzhzh 
Alrighty then, I'll add an option for turning the shadow off in the next release (soon...!). Stay tuned!

**Comment by roughike** [comment]
Now you can hide the shadow in the library version _1.0.3_ by calling ```bottomBar.hideShadow()```.
