### ISSUE TITLE
Hide/Show

### ISSUE THREAD

**Issue by FaradjSaadana** [roughike/BottomBar#301]
Hello

For me the methods Hide and Show are inverted. Also isShown always returns true even when the BottomBar is hidden.

Is other people have this problem ?

**Comment by JonathanMerritt** [comment]
Are using `this._Bottombar.getBar()`?

```
if (this._Bottombar.getBar().isShown) this._Bottombar.hide();
else this._Bottombar.show();
```

**Comment by FaradjSaadana** [comment]
This has have the same behavior.

**Comment by JonathanMerritt** [comment]
@FaradjSaadana You'll have to post some code.

I'm not sure how these methods would invert. Just for you. Seems really strange.

**Comment by OlegFilimonov** [comment]
Same here. Methods are inverted

**Comment by roughike** [comment]
This is greatly simplified in the new version of the library. Although there's no show / hide methods (yet), you can hide it just like any other View.
