### ISSUE TITLE
[Help] I want to show icon and caption.

### ISSUE THREAD

**Issue by striderblue** [roughike/BottomBar#305]
I use command use useFixedMode() to show all titles but it show error when I compile application.
At logcat, it said I have to use forceFixedMode() method.

please, I need some advice.

thank you

**Comment by ynhenggg** [comment]
you must use useFixedMode() before setItems().

**Comment by roughike** [comment]
It's not so constrained in the v2.0 and up anymore. All tabs show titles by default now.
