### ISSUE TITLE
I want use it in my new project , but I have two problem about config it...

### ISSUE THREAD

**Issue by ynhenggg** [roughike/BottomBar#306]
dear roughike:
I found your BottomBar on github ,it's beautiful ,I love it ,
so I want to use it in my new application project this week .
but I there are two problem when I test it ,
I can not slove myself:

1---I mapColorForTab() for everyTab, it's ok , but I want the title show always, so I use setMaxFixedTabs() / useFixedMode() , then the bottomBar lost color ....

2---setActiveTabColor() will not work when I use it with mapColorForTab()

the effect I want is as blow:
1---show title always
2---have backgroudcolor
3---the drawable has color when it's selected

looking forward for you reply , thanks...

best regards...

**Comment by roughike** [comment]
You can have all those with the newest version of this library.
