### ISSUE TITLE
 icon size can not be random , be sure to press you to request it

### ISSUE THREAD

**Issue by guoyoujin** [roughike/BottomBar#309]
icon size can not be random , be sure to press you to request it

**Comment by alvarlagerlof** [comment]
?

**Comment by akshayspeaks** [comment]
Icon size has to be 24dp. Here's how I did it.

`final float scale = mActivity.getResources().getDisplayMetrics().density;
final int bottomNavPixels = (int) (24 * scale + 0.5f);
Drawable dr = new BitmapDrawable(getResources(), Bitmap.createScaledBitmap(bitmap, bottomNavPixels, bottomNavPixels, true));`

Now use the drawable in `mBottombar.setItems(new BottomBarTab(dr, "Title"));`

**Comment by cabelloruizcarlos** [comment]
It works for me! Thanks!!
