### ISSUE TITLE
Need options to disable animations and let text to show at first.

### ISSUE THREAD

**Issue by tinybright** [roughike/BottomBar#31]

**Comment by roughike** [comment]
Could you elaborate what you exactly mean?

**Comment by WatingForYou** [comment]
BottomBar cancel animation, not to choose and select display text and ICONS, just icon and text color, how to do?

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just setAll background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by tinybright** [comment]
1. I guess you can bottombarMain.setColored(false);  or just set All background  of AHBottomNavigationItem to same.
2.You should go to AHBottomNavigation and remove the animation you needn't.

**Comment by zhweeant** [comment]
how to make always show all Title below the icon, not only if these items selected . please advice . thanks

**Comment by tinybright** [comment]
Search alpha in AHBottomNavigation.
