### ISSUE TITLE
If i use only two menu item then the color is not set which i want but its set white always

### ISSUE THREAD

**Issue by DivyeshTarsariya** [roughike/BottomBar#312]
please give me a proper solution for it 

on this site or my email account

divyesh.tarsariya@gmail.com

**Comment by wuchangfeng** [comment]
two menu item ? at least three items with bottom bar.

**Comment by roughike** [comment]
You can customize the tab colors or the background color anyway you want with the new version. 

[Check the README](https://github.com/roughike/BottomBar#all-customization-options)
