### ISSUE TITLE
Only two items and cannot set any color

### ISSUE THREAD

**Issue by WrathChaos** [roughike/BottomBar#314]
Hello,

i love your work, really i do. I only need to use two menu items and i cannot set any background or icon color for that. Is there any solution for this?

Thank you so much.

**Comment by alvarlagerlof** [comment]
"If there are fewer than three destinations, consider using tabs instead" https://material.google.com/components/bottom-navigation.html#bottom-navigation-usage

**Comment by johan-polymorph** [comment]
This is still a bug imo. 
And you have the same issue for 3 menu items - the background colour is only applied when the private variable mIsShiftingMode is true (ok, there are a few more conditions...) and that only happens once you have 4 or more tabs...
`mIsShiftingMode = mMaxFixedTabCount >= 0 && mMaxFixedTabCount < bottomBarItems.length;`

**Comment by johan-polymorph** [comment]
A workaround for setting the background colour is to add this 
`mBottomBar.getBar().setBackgroundColor(ContextCompat.getColor(this, R.color.colorAccent));` 
_after_ you have added the bottomBar and the menu items

**Comment by roughike** [comment]
It's not so constrained on versions 2.0 and up anymore.

[See the readme](https://github.com/roughike/BottomBar#all-customization-options)
