### ISSUE TITLE
BottomBar mess up with frameLayout

### ISSUE THREAD

**Issue by tjouin** [roughike/BottomBar#315]
Hey, first i want to thanks yout for the good work. Thats really good :D.

I got some issue to integrate your tools in my current project. I got a mainActivity composed of a simple frameLayout.

If i dont use the NestedScrollView all my content is fucked up : (here the screen)
![screenshot_20160625-000658](https://cloud.githubusercontent.com/assets/12596693/16352096/2a45ec34-3a6b-11e6-87b5-4c4fb94db53d.png)

And if i use it, its just desapear ^^ (Here the screen again)
![screenshot_20160625-000620](https://cloud.githubusercontent.com/assets/12596693/16352093/2686369e-3a6b-11e6-9ce7-9821c02b59b3.png)

I don't know if its a commun error. i don't find something like this in issue.

Thanks for help.

**Comment by oalpayli** [comment]
Hi tjouin ,

I have faced this problem too. Did you find any solution?

Thank You.

**Comment by tjouin** [comment]
No i didn't, i'have made my own BottomBar it's easier ^^

**Comment by oalpayli** [comment]
I got it. Do you think Is the problem because of framelayout? If I change frameLayout with Relative Layout or another layouts?

**Comment by tjouin** [comment]
Maybe, i didn't try because i needed a frameLayout. U can give a try

**Comment by roughike** [comment]
Now the BottomBar behaves like any other View, so this shouldn't be an issue anymore.
