### ISSUE TITLE
Transparent navigation bottom bug

### ISSUE THREAD

**Issue by mac229** [roughike/BottomBar#316]
Hi, 
I have problem with transparent bottomon older devices (Android 4.1.2).
On newer devices navigation bottom is white, but on older is transparent.

Here is my code from activity where I use also fragments (but they are changing):
`	final BottomBar bottomBar = BottomBar.attach(this, savedInstanceState);
	bottomBar.setTextAppearance(R.style.MatebyNavBottomText);
	bottomBar.noNavBarGoodness();
	bottomBar.noTabletGoodness();
	bottomBar.setItems(R.menu.navigation_bottom);
	bottomBar.setOnMenuTabClickListener(this);
	bottomBar.setActiveTabColor(ContextCompat.getColor(this, R.color.main_color));`

Below is example how it looks:
[Example](https://scontent-cdg2-1.xx.fbcdn.net/v/t34.0-12/13551059_601667930011657_1605516553_n.png?oh=8130d2784d1977b27fb32952ff21aa2a&oe=5772245E)

**Comment by wuchangfeng** [comment]
Hello.
Can not see the Image!
