### ISSUE TITLE
Bottom Bar hiding behind navigation buttons

### ISSUE THREAD

**Issue by kevjett** [roughike/BottomBar#321]
I'm having trouble getting the bottom bar to display correctly. It is hiding behind the navigation buttons at the bottom. It behaves the same way on an emulator or device.

<img width="427" alt="screen shot 2016-06-28 at 4 58 10 pm" src="https://cloud.githubusercontent.com/assets/2198452/16433848/dfaf0e1e-3d51-11e6-9459-6d568177ea9d.png">

Here is my code. The icons were generated by the icon generator in the ReadMe.

```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tab);
        mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar.setItems(R.menu.bottombar_menu);
}
```

Layout xml
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.android.activity.TabActivity">
    <FrameLayout
        android:id="@+id/tabcontent"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent">

</FrameLayout>
</RelativeLayout>
```

Any ideas?

**Comment by wuchangfeng** [comment]
hello.

 i copy your code into my as,and the icons from the author demo ,I  run it normally.

I think It maybe your icons's problem. 

you can use the icons that the author supported.  

And test it!

**Comment by Sidhanthsur** [comment]
I am facing the same issue though I use icons of size 24px

**Comment by alvarlagerlof** [comment]
@Sidhanthsur px or dp?

**Comment by Sidhanthsur** [comment]
@alvarlagerlof it's px.

**Comment by kevjett** [comment]
After taking @wuchangfeng suggestion I took a look at the difference in my icons and the ones from the example. I noticed right away that mine had a padding around the icons in the images. As soon as I used the icon generator again and set the padding to 0, it worked great. Thanks for helping my find my problems. Now someone else who has this problem might learn from my mistake.

@Sidhanthsur Look at your icon images. Is there a white padding around them? If so, you need to remove the padding so the icon goes to the edges of the image.

**Comment by Sidhanthsur** [comment]
Oh yes you are right. Thanks for the tip.
