### ISSUE TITLE
[ Adding a line above the bottombar ]

### ISSUE THREAD

**Issue by christaupher** [roughike/BottomBar#322]
Hi,

I would like to add a small horizontal line above the boottombar,

just like the link : 
![bottombar](https://cloud.githubusercontent.com/assets/19349361/16456391/00a5bc5a-3e18-11e6-9e68-f2d62026cae6.jpg)

Do you have any idea how to make it ?

**Comment by wuchangfeng** [comment]
any App like that?

**Comment by JonathanMerritt** [comment]
I would imagine exposing setting the shadows resource will make this possible. On the library end that is.

For now maybe you can try some reflection to achieve the same effect. Using an XML drawable would probably be best though.

**Comment by christaupher** [comment]
Thank you for your answers,
I can also add the green line on all the fragments in the bottom of each activity...
But it's not optimized at all ahah ! Probably need to custom more the bottombar

**Comment by alvarlagerlof** [comment]
Why would you want that? Just querious

**Comment by christaupher** [comment]
Ahaha simply for the design, this green line will separate the content  from the bottombar.
I haven't found a solution yet, any ideas ?

**Comment by a-mehta** [comment]
Create a layer-list drawable:

http://stackoverflow.com/questions/24095223/android-linearlayout-add-border-with-shadow-around-a-linearlayout

**Comment by JonathanMerritt** [comment]
@a-mehta Where and how would he set the drawable? Aside from making a mock view over the bottom bar to set your own... Seems like overkill though.

@christaupher I'm close to finishing up a project I'm calling BottomBeam. It'll have the option to change the shadow to a color or drawable. I'll tag you here, that's if you even still need this anymore. Just let me know.

**Comment by a-mehta** [comment]
The layer-list drawable should be put in the `res/drawables` folder. The way you set this as a drawable would be to set the `bottomBar.getBar()`'s background.

The layer list allows for the first layer to be set as the bar colour, and to have the second layer have a little bit of an inset so that the first layer "peeks" through, giving the illusion of a bar. The only difference between this problem and the one I linked is that you don't need a corner radius in either layer, and that there should be a `top` offset instead of a `bottom` offset.

**Comment by JonathanMerritt** [comment]
@a-mehta You're absolutely right. I'm pretty sure I read your solution as if you were saying a shape drawable and my mind swapped out all the layer lists... 

Thank you for spending the time in clarifying that for me, even though it was originally clear to begin with. My apologies.

**Comment by a-mehta** [comment]
All good, original post could have been clearer!
