### ISSUE TITLE
Issues with RecyclerView

### ISSUE THREAD

**Issue by shunishya** [roughike/BottomBar#327]
I am having problem with recycler view after adding this library

**Comment by alvarlagerlof** [comment]
Can you discribe the issues in more detail? Maybe paste the error from the log?

**Comment by shunishya** [comment]
actually its not giving any log. whenever i add this library my code shows can't resolve recyclerview error.

**Comment by JonathanMerritt** [comment]
@shunishya 
If you're using `_BottomBar.attachShy(_Coordinator, _RecyclerView, _Bundle)`
Make sure the recycler is somewhere on the focused content view.

If not, you'll have to provide some code. Sorry.
