### ISSUE TITLE
Activity doesn't blackout when navigation drawer is opened

### ISSUE THREAD

**Issue by samoilovich** [roughike/BottomBar#328]
Hello. I'm Natali.
Can you help me how I can blackout activity when navigation drawer is opened on android 5.1 (screenshot 1). No problem on android 4.1 (screenshot 2)
May be I miss something in configuration of BottomBar?
`

    private void initBottomNavigationBar(Bundle savedInstanceState) {
        bottomBar = BottomBar.attach(coordinatorLayout, savedInstanceState);
        bottomBar.noNavBarGoodness();
        bottomBar.hideShadow();
        bottomBar.setActiveTabColor(ContextCompat.getColor(this, R.color.violet_light));
        bottomBar.setMaxFixedTabs(1);
        bottomBar.setItems(R.menu.activity_main_bottom_nav_bar_menu);
        bottomBar.setOnMenuTabClickListener(new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId) {
                bottomNavBarSelectedItemId = menuItemId;
                switchFragmentOnBottomNavTabSelected();
            }

            @Override
            public void onMenuTabReSelected(@IdRes int menuItemId) {
            }
        });
    }
`

![screen_1](https://cloud.githubusercontent.com/assets/7480005/16558963/210886e8-41f2-11e6-8798-9dee0be05495.png)
(screenshot 1)

![screen_2](https://cloud.githubusercontent.com/assets/7480005/16559106/2250904e-41f3-11e6-8888-168eb8fbf483.png)
(screenshot 2)

Thanks

**Comment by roughike** [comment]
Now the BottomBar is just a regular View, so this kind of issue shouldn't exist anymore.
