### ISSUE TITLE
Space Below Btoom tab bar  in nexus 6p(Devices have menu on screen)

### ISSUE THREAD

**Issue by govind1988** [roughike/BottomBar#333]
Hi ,
I am facing a weird issue  having extra space below bottom bar on Nexus 6p.

if i change the code from mBottomBar=BottomBar.attach(findViewById(R.id.fragment_container),savedInstanceState);
to
mBottomBar=BottomBar.attach(this,savedInstanceState);
space is shiting above the bottom bar.

My layout looks below

`<?xml version="1.0" encoding="utf-8"?>

<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:id="@+id/cordinator_layout"
    tools:context=".activity.HomeActivity">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay"
        >

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"

            app:popupTheme="@style/AppTheme.PopupOverlay" >
            <RelativeLayout
                android:id="@+id/notification"
                android:background="@android:color/transparent"
                android:layout_width="wrap_content"

                android:layout_height="wrap_content"
                >
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/fragment_title"
                    android:text="Title"
                    android:layout_centerInParent="true"
                    android:textSize="20sp"
                    android:layout_alignParentLeft="true"/>
                <FrameLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginRight="5dp"
                    android:layout_alignParentRight="true">
                <TextView
                    android:id="@+id/txt_notification_count"
                    android:layout_alignParentBottom="true"
                    android:layout_alignParentRight="true"
                    android:textColor="@android:color/darker_gray"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="right|top"
                    />
                <ImageView
                    android:id="@+id/notificaion_icon"

                    android:background="@android:color/transparent"
                    android:src="@drawable/ic_bell_outline"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerVertical="true"
                    android:layout_toStartOf="@+id/txt_notification_count"
                    android:contentDescription="Notification" />
                </FrameLayout>
            </RelativeLayout>
        </android.support.v7.widget.Toolbar>

    </android.support.design.widget.AppBarLayout>

    <include layout="@layout/content_home" />

</android.support.design.widget.CoordinatorLayout>
`

@roughike  please help me on this.

**Comment by algibe** [comment]
use this mBottomBar.noNavBarGoodness(); after attach

**Comment by govind1988** [comment]
its working fine. Thanks.
