### ISSUE TITLE
Using selectTabAtPosition(n,true) doesn't honor the mapped colors for the tabs

### ISSUE THREAD

**Issue by manrock007** [roughike/BottomBar#335]
I have an Activity which receives an intent with a string extra, and decides which fragment to load. My fragments are in a view pager, tied to the bottom bar. I use selectTabAtPosition to jump to a certain fragment. I also the paint toolbar in my OnMenuTabClickListener with the exact same color as the bottom bar. 

I get this when I manually click on a tab
![right](https://cloud.githubusercontent.com/assets/910015/16633153/80f7103e-43e5-11e6-9a8c-e8f7ca62f006.png)

I get this when I use selectTabAtPosition 
![wrong](https://cloud.githubusercontent.com/assets/910015/16633159/88a1cef0-43e5-11e6-949f-f5655d266807.png)

**Comment by manrock007** [comment]
Bump?

**Comment by manrock007** [comment]
Bump again?

**Comment by roughike** [comment]
Should've been fixed in the 2.0 release.
