### ISSUE TITLE
How do I scroll the bottom bar icons horizontally? 

### ISSUE THREAD

**Issue by manrock007** [roughike/BottomBar#336]
Right now I have 8 icons in the bottom bar. The icons have reduced in size as the bottom bar tries to fix everything in the screen width.. Is there a way to allow the bottom bar to go beyond the screen and allow for horizontal scrolling?

**Comment by pollax** [comment]
I would highly recommend not doing so since that goes against the guidelines for a bottom navigation (https://material.google.com/components/bottom-navigation.html)

> Usage:
> Three to five top-level destinations

> Don't.
> Avoid scrollable content in the bottom navigation bar.

> Don't.
> Avoid using more than five destinations in bottom navigation as tap targets will be situated too close to one another.

**Comment by sethgnavo** [comment]
@manrock007 sure, @pollax is right. You should not be using more than 5 top-level destinatinos in the bottom bar according to Google's guidelines. You can still [use tabs or a Navigation drawer](https://material.google.com/components/bottom-navigation.html#bottom-navigation-usage)

**Comment by roughike** [comment]
With this library it isn't possible, and I'm not intending to support it, sorry.
