### ISSUE TITLE
Tablet Side Bar doesn't take any theme or color changes

### ISSUE THREAD

**Issue by NickM-27** [roughike/BottomBar#34]
The tablet side bar seems to always be white, even changing the new color normally doesn't work. Is this intentional?

**Comment by roughike** [comment]
Yes. As far as I can tell, this is according to the spec.

**Comment by roughike** [comment]
Although I'll probably add a dark theme for it when I can.

**Comment by NickM-27** [comment]
Gotcha, dark theme would definitely be appreciated

**Comment by roughike** [comment]
Dark Theme has been now possible with the latest versions.
