### ISSUE TITLE
How add padding for bottomBar caption ?

### ISSUE THREAD

**Issue by z85510** [roughike/BottomBar#343]
Hi , how can i fix it to display text completely ? 
![photo_2016-07-10_01-37-32](https://cloud.githubusercontent.com/assets/8364557/16710300/e70728cc-463e-11e6-9416-9aec23fd2b59.jpg)

**Comment by Boxroma** [comment]
Also having the same problem..

**Comment by navid507** [comment]
the reason of this problem is the icon padding! icon`s padding must be zero
cheers...

**Comment by zhaoyou** [comment]
I having the same problem.

icon cover the title？(the left two icon downloaded from website, other two is android drawble icon default.)

![woooo](https://cloud.githubusercontent.com/assets/612257/17829917/88b21ce6-66f0-11e6-9ad8-4ad801b04c78.png)


I download icon from [AndroidAssetStudio](https://romannurik.github.io/AndroidAssetStudio/icons-generic.html#source.type=clipart&source.space.trim=1&source.space.pad=0&source.clipart=res%2Fclipart%2Ficons%2Faction_accessibility.svg&size=24&padding=8&color=33b5e5%2C100&name=ic_action_accessibility)

![screen shot 2016-08-20 at 3 50 48 pm](https://cloud.githubusercontent.com/assets/612257/17829867/8a5d892e-66ee-11e6-95a5-1ad5a20e0d17.png)

**Comment by SergeyAppDroid** [comment]
Padding around the optical icon must be 0 dip
