### ISSUE TITLE
Badge position

### ISSUE THREAD

**Issue by Remcoj** [roughike/BottomBar#344]
I am using the bottom bar with 5 tabs. When I receive a notification I add a badge to the first tab.
Mostly this works fine, except when I start switching tabs. When the tab containing the badge is active the badge is shown in the top right corner after switching to another tab the badge is almost gone.
When I add a badge when the badgetab is inactive it is displayed correctly, but when I switch to the badgetab the badge is displayed over the tab icon.
I have attached the images to show the situation.

![screenshot_20160711-113249](https://cloud.githubusercontent.com/assets/19925732/16726326/e4dd1656-475b-11e6-9829-47c6dc06b60a.png)
![screenshot_20160711-113252](https://cloud.githubusercontent.com/assets/19925732/16726328/e91b15c4-475b-11e6-8a7f-6c0d0c2eea88.png)

![screenshot_20160711-113534](https://cloud.githubusercontent.com/assets/19925732/16726332/ed570292-475b-11e6-9a4a-13bfff2b7eb3.png)
![screenshot_20160711-113537](https://cloud.githubusercontent.com/assets/19925732/16726334/efc6826e-475b-11e6-9463-e3421b620782.png)

**Comment by Manu206** [comment]
I noticed the same behavior!

**Comment by Remcoj** [comment]
I do not have a solution jet, however a way to "work around" this problem is by disabling the ResizeGoodness on the bottombar. By doing this the bar will nog longer scale the images, but the badge will also stay on the correct position.

BottomBar.noResizeGoodness();

**Comment by roughike** [comment]
The badge position logic was improved on the 2.0 version and this shouldn't happen anymore. Give it a go, and reopen / repost if this issue remains.
