### ISSUE TITLE
visual differences while transiting from 1.3.3 to 1.4.0

### ISSUE THREAD

**Issue by oradkovsky** [roughike/BottomBar#346]
hi. it's best illustrated using attachments below. in short:
1. in one case (01-vxxx.png) system bar of back-home-menu changed color from black to gray
2. in another case (02-vxxx.png) bottom bar started to overlap with system bar of back-home-menu (notice floating button is rendered correctly above the system bar).

is this misuse on my end or a bug?

![01-v1 3 3](https://cloud.githubusercontent.com/assets/9694896/16739016/e065ce16-47a0-11e6-88b7-d497466c1b77.png)
![01-v1 4 0](https://cloud.githubusercontent.com/assets/9694896/16739018/e06a7a74-47a0-11e6-896b-6f3f5101914a.png)

--

![02-v1 3 3](https://cloud.githubusercontent.com/assets/9694896/16739017/e0682346-47a0-11e6-8248-da1896092c47.png)
![02-v1 4 0](https://cloud.githubusercontent.com/assets/9694896/16739019/e06b05b6-47a0-11e6-887c-a83bc3a35b6c.png)

**Comment by oradkovsky** [comment]
(scrolling is involved in 2nd pair of screenshots)

**Comment by mehrdaad** [comment]
Yeah I'm facing the same problem.  
Your lib use to be a good library but I break things so carelessly.

**Comment by roughike** [comment]
The positioning should've been fixed in versions 2.0 and up.
