### ISSUE TITLE
Bottom bar blocking fab

### ISSUE THREAD

**Issue by patrickoramah** [roughike/BottomBar#348]
Bottom bar is not placing framelayout on top making it cover views instead of placing it on top of the bar, example:

![screenshot_2016-07-11-03-25-39](https://cloud.githubusercontent.com/assets/16429199/16741460/414f3f42-479b-11e6-9360-5dbcfbf69c2a.png)
![screenshot_2016-07-11-03-25-47](https://cloud.githubusercontent.com/assets/16429199/16741461/419e5b4a-479b-11e6-8cb7-6c2b0a34575d.png)

My code:
XML:
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    android:fitsSystemWindows="true">
    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".NavDrawerActivity">
        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <android.support.design.widget.AppBarLayout
                android:id="@+id/home_appbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
                android:fitsSystemWindows="true">
                <android.support.v7.widget.Toolbar
                    android:id="@+id/home_toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="?attr/actionBarSize"
                    android:background="?attr/colorPrimary"
                    app:layout_scrollFlags="scroll|enterAlways"
                    app:popupTheme="@style/ThemeOverlay.AppCompat.Light"/>
                <android.support.design.widget.TabLayout
                    android:id="@+id/home_tabLayout"
                    android:scrollbars="horizontal"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_below="@+id/toolbar"
                    android:background="?attr/colorPrimary"
                    app:layout_scrollFlags="scroll|enterAlways"
                    android:visibility="gone"
                    app:tabMode="fixed"
                    app:tabIndicatorHeight="3dp"
                    app:tabIndicatorColor="@color/white"/>
            </android.support.design.widget.AppBarLayout>
            <FrameLayout
                android:id="@+id/home_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@+id/home_appbar"
                app:layout_behavior="@string/appbar_scrolling_view_behavior">
            </FrameLayout>
        </RelativeLayout>
    </android.support.design.widget.CoordinatorLayout>
    <android.support.design.widget.NavigationView
        android:id="@+id/nav_drawer_navigation"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:headerLayout="@layout/nav_drawer_header"
        app:elevation="20dp"
        app:menu="@menu/nav_drawer_items"/>
</android.support.v4.widget.DrawerLayout>
`

And JAVA:
```
`    private void setupBottomBars(Bundle savedInstanceState){
        List<Fragment> fragments = new ArrayList<>(3);
        fragments.add(FeedsFragment.newInstance());
        fragments.add(CommunityFragment.newInstance());
        fragments.add(NotificationFragment.newInstance());
        mNavController = new FragNavController(getSupportFragmentManager(), R.id.home_container, fragments);
        bottomBar = BottomBar.attach(findViewById(R.id.home_container), savedInstanceState);
        //bottomBar.setMaxFixedTabs(2);

        bottomBar.setItems(R.menu.bottom_bar_items);
        bottomBar.setOnMenuTabClickListener(new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId) {
                switch (menuItemId){
                    case R.id.bottomBarItemFeeds:
                        mNavController.switchTab(INDEX_FEEDS);
                        break;
                    case R.id.bottomBarItemCommunity:
                        mNavController.switchTab(INDEX_COMMUNITIES);
                        break;
                    case R.id.bottomBarItemNotification:
                        mNavController.switchTab(INDEX_NOTIFICATIONS);
                        break;
                }
            }

            @Override
            public void onMenuTabReSelected(@IdRes int menuItemId) {
                mNavController.clearStack();
            }
        });
    }
`
```

Am i doing anything wrong?

**Comment by alexbeville** [comment]
Did you solved your issue ?

**Comment by patrickoramah** [comment]
Nope

**Comment by alexbeville** [comment]
Why did you close it ? :)

**Comment by tudorific** [comment]
I have a similar issue, I am adding a fragment to the fragment manager, but instead of opening overtop of everything, I think its actually opening below or beside the bottom bar.
