### ISSUE TITLE
Bottom Bar background colour doesn't change

### ISSUE THREAD

**Issue by dwinnbrown** [roughike/BottomBar#349]
Firstly, I just wanted to say thanks for this great project.

It has definitely helped me a lot but I am now trying to customize the bar to fit with my colour scheme.

I am using this code:
`
        mBottomBar.setItems(R.menu.bottombar_menu);
        //Colours
        //mBottomBar.mapColorForTab(0, ContextCompat.getColor(this, R.color.colorAccent));
        mBottomBar.mapColorForTab(0, "#000000");
        mBottomBar.mapColorForTab(1, "#000000");
        mBottomBar.mapColorForTab(2, "#7B1FA2");
        mBottomBar.mapColorForTab(3, "#FF5252");
`
for my four tab bar items. However nothing changes and the bar remains white. I have tried uncommenting the line for tab 0 but it causes an error. Anyone got any ideas?

Thanks

**Comment by decubate** [comment]
I'm having the same issue, though only in fixed mode it seems.

**Comment by dwinnbrown** [comment]
Yes i think it is just fixed mode.
I resorted to doing this, as I didn't need the tab bar colour to change depending on the tab:
`mBottomBar.getBar().setBackgroundColor(getResources().getColor(R.color.colorPrimary));`
and then used this to set the active tab colour:
`mBottomBar.setActiveTabColor("#ffffff");`
Thanks

**Comment by manrock007** [comment]
Not sure, but you might be affected by the night mode setting. Try this out..     
`mBottomBar.ignoreNightMode();`

**Comment by dwinnbrown** [comment]
I tuned on dark mode also which made inactive tabs a readable white colour
