### ISSUE TITLE
change the inactive icon

### ISSUE THREAD

**Issue by rraayy** [roughike/BottomBar#355]
Hi, do you have plan to support developer to change the icon when the tables is inactive?
We only can change the icon color, but no way to change the icon.
 Hope can provide the method to change the icon.

Many Thanks.

**Comment by Kyle-Xie** [comment]
+1

**Comment by hcw2175** [comment]
+1

**Comment by Nolanus** [comment]
Duplicate of #153, #249

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
