### ISSUE TITLE
Snackbars should go above the bottom bar.

### ISSUE THREAD

**Issue by rosenpin** [roughike/BottomBar#36]
I don't know if it was already reported, but when I implement this library and try to attach a snack bar like so:

`Snackbar.make(bottomBar, "Some text", Snackbar.LENGTH_LONG).show();`

I get [this result](http://i.imgur.com/1qymQLk.png) (The snackbar overlays the bottom bar).

According  to the guidelines it should look [like this](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HQTdycnRmdXlFbEk/components_bottomnavigation_spec_elevation1.png).

And once again, thank you for this great and quick implementation.

**Comment by jml90** [comment]
For this, the bottom bar needs to be inside a coordinator layout. I think that the library doesn't have to care about that because is coordinator layout work . Hope that this doesn't break some flexibility

**Comment by roughike** [comment]
You can try attaching the BottomBar inside CoordinatorLayout by attaching it to a view that's directly inside it.

For example:

**activity_main.xml**
```xml
<CoordinatorLayout
    ...>
    <FrameLayout android:id="@+id/myContent" />
    <FloatingActionButton 
    ...  />
    ...
</CoordinatorLayout>
```

**MainActivity.java**
```java
bottomBar.attach(findViewById(R.id.myContent), savedInstanceState);
```

**Comment by roughike** [comment]
If you're using ```bottomBar.attach(this, savedInstanceState)```, give the Snackbar the CoordinatorLayout as the first parameter.

**activity_main.xml**

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/myCoordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    ...

</android.support.design.widget.CoordinatorLayout>
```

**MainActivity.java**
```java
Snackbar.make(findViewById(R.id.myCoordinator), "Can you smell what The Rock is cooking?", Snackbar.LENGTH_LONG).show();
```

**Comment by rosenpin** [comment]
Works!

**Comment by roughike** [comment]
Awesome!

**Comment by rajas47** [comment]
I used the co-ordinator layout as you said, but the snackbar never appeared
this.myCoordinator = (CoordinatorLayout) findViewById(R.id.myCoordinator);
 this.bottomBar = (BottomBar) findViewById(R.id.bottomBar);
    snackbar = Snackbar.make(myCoordinator, "This is a snackbar", Snackbar.LENGTH_INDEFINITE);
    snackbar.show();

Am i doing something wrong here?

**Comment by sembozdemir** [comment]
Hi @roughike, @rosenpin 

I am using 2.1.1 version. Snackbar is not visible in anyway. How did you achieve this? Could you provide more detailed code, please? I could not find any method like BottomBar#attach()

That's my code:

```
Snackbar.make(coordinatorLayout, "message", Snackbar.LENGTH_LONG).show();
```

```
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activityHomeRoot"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <include layout="@layout/layout_cci_toolbar"/>

    <FrameLayout
        android:id="@+id/activityHomeFrameLayoutContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        android:layout_marginBottom="@dimen/home_bottom_bar_height_without_shadow"/>

    <com.roughike.bottombar.BottomBar
        android:id="@+id/activityHomeBottomBar"
        android:layout_width="match_parent"
        android:layout_height="@dimen/home_bottom_bar_height"
        android:layout_gravity="bottom"
        style="@style/CCIBottomBar"/>

</android.support.design.widget.CoordinatorLayout>
```

```
<resources>

    <style name="CCIBottomBar">
        <item name="bb_tabXmlResource">@xml/home_bottom_bar_tabs</item>
        <item name="bb_activeTabColor">@color/colorPrimary</item>
        <item name="bb_inActiveTabColor">@color/gunmetal</item>
    </style>

</resources>
```

**Comment by jkwiecien** [comment]
@rosenpin Could you provide your working layout xml?

**Comment by yombunker** [comment]
@jkwiecien how are you displaying the SnackBar?

**Comment by MonShein** [comment]
When I use android support library com.android.support:design:25.2.0,the snackbar won't work.is there any solution?
