### ISSUE TITLE
mBottomBar.noTopOffset()  dosn't have the desired effect

### ISSUE THREAD

**Issue by lwj1994** [roughike/BottomBar#361]
when i   use  mBottomBar.noTopOffset()  . it stretch into status bar . and status bar covers the content.

**Comment by biagio1995** [comment]
I have the same problem..

**Comment by xvarlez** [comment]
I had the same issue. Solved it by using
`bottomBar.useOnlyStatusBarTopOffset()`
instead of 
`bottomBar.noTopOffset()`

**Comment by roughike** [comment]
With the newest version of the library, shouldn't happen. xvarlez's answer solves it for the old versions.
