### ISSUE TITLE
Selection issue

### ISSUE THREAD

**Issue by DhavalsShah** [roughike/BottomBar#362]
How to disable default selection of tab position 0. I do not want to select any tab by default. I want that whenever user click on the perticular tab then it should be in action.  I have tried with mBottomBar.setSelection(false). But it doesn't help me to disable selection. Any idea how to disable by default selection of tab?

**Comment by Nolanus** [comment]
As far as I know this is not supported. One tab needs to be selected by default. You may change which one this should be, not there is no state "no tab selected".

**Comment by roughike** [comment]
One tab needs to be selected with this library. I'm not planning on supporting having no selected tabs, sorry.

**Comment by sembozdemir** [comment]
This option has been added to library with this [commit](https://github.com/roughike/BottomBar/commit/c71f6dff71c05811883150261de9418aa8f9811c)

Set tab select listener like this:

    bottomBar.setOnTabSelectListener(this, false);
