### ISSUE TITLE
White space above bar

### ISSUE THREAD

**Issue by biagio1995** [roughike/BottomBar#366]
Hi, nice work, but i have a problem, when i put your bar in my app there is a white space (height of the system bar) above your bottombar...
![screenshot_2016-07-19-11-49-54](https://cloud.githubusercontent.com/assets/2057475/16945978/b5385ecc-4da7-11e6-8eab-8a71fcc3cb0c.png)

How can i fix this?

**Comment by alizarei95** [comment]
same here
https://github.com/roughike/BottomBar/issues/331

**Comment by biagio1995** [comment]
I had already found that solution but is not what i am looking for, i want to maintain the transparent bar

**Comment by Drakot** [comment]
Post it!

**Comment by biagio1995** [comment]
I added "<item name="windowActionBar">false</item>" in app style and removed topSpace.. Then it worked

**Comment by s3286837** [comment]
@biagio1995 could you be more specific in what you set to false and what you mean by 'removed topSpace'. I have tried many things but am still stuck with this issue though only when the keyboard is displayed

**Comment by roughike** [comment]
Fixed in 2.3.0.
