### ISSUE TITLE
Different color for icons than text on BottomBar?

### ISSUE THREAD

**Issue by tudorific** [roughike/BottomBar#368]
I have 3 tabs on the BottomBar and each tab has an orange icon. When I open my app, the icon and the text are both gray while inactive and white while active.

If I use this: `mBottomBar.setActiveTabColor(getResources().getColor(R.color.orange));` to set the active tab color to orange, both the icon and the text are turned orange for the active tab.

Can I turn only the icon to orange and leave the text white? How can I achieve this?

Thanks!

**Comment by roughike** [comment]
[See the README](https://github.com/roughike/BottomBar#all-customization-options).

**Comment by csdinon** [comment]
@roughike I don't believe this feature exists. I looked through the ReadMe and found nothing about setting color **only** for the title. The source doesn't seem to have anything either. This feature would be especially useful for primary colors that don't conform to accessibility standards.
