### ISSUE TITLE
Can we change BottomBar size ?

### ISSUE THREAD

**Issue by gurikoxo** [roughike/BottomBar#37]
Can we change bottom bar size ?

**Comment by roughike** [comment]
Not right now.

What element's size would you want to change?

**Comment by gurikoxo** [comment]
I want to change bar height.

**Comment by roughike** [comment]
The bar height is automatically adjusted according to the space the titles and icons take. So would you want to have some extra space or what are you trying to do?

**Comment by gurikoxo** [comment]
I want to change top and bottom margin of icons.

**Comment by jd-alexander** [comment]
Can the margins of the icons and titles be adjusted now?
