### ISSUE TITLE
Remove texts from tabs in FixedMode

### ISSUE THREAD

**Issue by alizarei95** [roughike/BottomBar#373]
how can i remove tab titles in FixedMode ?
removing title attribute in menu file makes empty space in bottom of icons and icons gets smaller size , any idea ?
![capture](https://cloud.githubusercontent.com/assets/4469948/17017173/8b3294ca-4f47-11e6-9d94-c55ca14f6006.PNG)

**Comment by alizarei95** [comment]
@roughike thank you for this library , can you help me in this case ?

**Comment by Drakot** [comment]
+1

**Comment by David-lab** [comment]
Add this after mBottomBar.setItems(),


```
View viewTab = mBottomBar.getBar();
View parentView = (View) viewTab.getParent();
ViewGroup mItemContainer = (ViewGroup) parentView.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_item_container);

for (int i = 0; i < mItemContainer.getChildCount(); i++) {
	View viewItem = mItemContainer.getChildAt(i);
	TextView titleTab = (TextView) viewItem.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
	titleTab.setVisibility(View.GONE);
}


```
