### ISSUE TITLE
 java.lang.ClassCastException: android.support.v7.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by rubysuki** [roughike/BottomBar#377]
I used that code : 
mBottomBar = BottomBar.attach(findViewById(R.id.layout_content), savedInstanceState);
And exception was throw : 
 java.lang.ClassCastException: android.support.v7.view.ContextThemeWrapper cannot be cast to android.app.Activity                                                                       
at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:342)

And this is my layout : 
<?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="@color/toolbar_header_color"
        android:minHeight="?attr/actionBarSize"
        android:theme="@style/ToolbarTheme">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/full_transperent"
            android:focusable="true"
            android:focusableInTouchMode="true"
            android:orientation="horizontal">

            <EditText
                android:id="@+id/edittext"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_marginLeft="@dimen/distance_four_dp"
                android:layout_weight="1"
                android:background="@null"
                android:ellipsize="end"
                android:hint="@string/returntrip_text_search_hint" />

            <ImageView
                android:id="@+id/image_edit"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:contentDescription="@string/app_name"
                android:src="@drawable/ic_cancel"
                android:visibility="gone" />
        </LinearLayout>
    </android.support.v7.widget.Toolbar>

    <RelativeLayout
        android:id="@+id/layout_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <fragment
            android:id="@+id/map"
            class="com.google.android.gms.maps.SupportMapFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

        <FrameLayout
            android:id="@+id/content_seach"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </RelativeLayout>

</LinearLayout>

**Comment by roughike** [comment]
This issue is non-existent with the newest version, since you can just add the BottomBar to your layout like any other View.
