### ISSUE TITLE
NoActionBar with BottomBar

### ISSUE THREAD

**Issue by thapabipin** [roughike/BottomBar#379]
I am using BottomBar for a project and I don't have a use of ActionBar/ToolBar. So disabled it from the style with theme Theme.Appcompat.NoActionBar but when I run the code, the ActionBar is there occupying the space in the layout. I tried many thing but the ActionBar still exist. I am using nexus 4 as my testing device. When  test in other device which has no soft keys, the ActionBar doesn't come. It comes only in Phones with soft keys like the phones Nexus.

What is the problem here? Can't I used BottomBar without ActionBar?

**Comment by natig8x** [comment]
Try calling this on the bottom bar `mBottomBar.useOnlyStatusBarTopOffset();`

**Comment by josefkorbel** [comment]
Thanks @natig8x !!!! I was getting desperate

**Comment by jchen236** [comment]
@natig8x  thank you so much!! The space at the top has been KILLING me.

**Comment by roughike** [comment]
The old solution was indeed ```useOnlyStatusBarOffset();```, but it isn't needed anymore, since the new BottomBar is now a regular View instead of a magical entity.
