### ISSUE TITLE
Needs an option to change items color for less than 4 items

### ISSUE THREAD

**Issue by rosenpin** [roughike/BottomBar#38]
When I use 3 items or less I can't seem to be able to change each item color, it's being set to my primary color automatically which in my case doesn't fit.

**Comment by roughike** [comment]
As far as I know, this is the way it should behave according to the specs. The specs say to not use different colors for the icons and the titles.

**Comment by rosenpin** [comment]
You are correct, the guidelines specifically says:

> Tint the current bottom navigation action (including the icon and any text label present) with the app’s primary color.

But in my case for example, the primary color is too bright to be visible on top of the white background of the bottom bar, so it looks [like this](http://i.imgur.com/W2vIeZf.png)

So in this specific case I would like to have the option to customize the color.

**Comment by roughike** [comment]
Fair point.

I'll add an option for changing that.

**Comment by rosenpin** [comment]
Awesome, thanks!

**Comment by roughike** [comment]
Now it's possible from version _1.1.0._ and up.

```java
// Set the color for the active tab. Ignored on mobile when there are more than three tabs.
mBottomBar.setActiveTabColor("#009688");
```
