### ISSUE TITLE
requestLayout() improperly called by android.support.v7.widget.AppCompatTextView

### ISSUE THREAD

**Issue by jchen236** [roughike/BottomBar#386]
I keep getting this error upon starting the app. Sometimes there are only a few error messages, sometimes the errors are infinite. Has anyone experienced this before/know what to do? Please advise.

**Comment by REWKyleB** [comment]
+1

**Comment by jessexx** [comment]
I think this is the same issue as #371.  Seems @roughike is looking into it as he added the bug label to it.

**Comment by roughike** [comment]
Indeed, same as #371. Let's move discussion there.
