### ISSUE TITLE
bb_unSelectBottomBarItemColor

### ISSUE THREAD

**Issue by SanVakil** [roughike/BottomBar#388]
Hi Team,
Can you please change "white " color property to "bb_unSelectBottomBarItemColor", So every one can customize the un select bottom bar item color in own application. If we used "white" property it will conflict in the project.  if you changed color property name in the colors.xml,  We can config bb_unSelectBottomBarItemColor color in our project color.xml file itself.

**colors.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="bb_inActiveBottomBarItemColor">#747474</color>
    <!--<color name="white">#FFFFFF</color>-->
    <color name="bb_unSelectBottomBarItemColor">#FFFFFF</color>
    <color name="bb_darkBackgroundColor">#212121</color>
    <color name="bb_tabletRightBorderDark">#505050</color>
</resources>
```

**BottomBar.Java**
```
 if (mUnSelectColor == null) {
            mUnSelectColor = ContextCompat.getColor(getContext(), R.color.bb_unSelectBottomBarItemColor);
            mPrimaryColor = MiscUtils.getColor(getContext(), R.attr.colorPrimary);
            mInActiveColor = ContextCompat.getColor(getContext(), R.color.bb_inActiveBottomBarItemColor);
        }
```

Thanks,
San

**Comment by roughike** [comment]
You can now specify the unselected color directly by using the ```bb_inActiveTabColor``` attribute.

[See the README](https://github.com/roughike/BottomBar#all-customization-options).
