### ISSUE TITLE
RecyclerView inside FrameLayout doesen't work

### ISSUE THREAD

**Issue by michelelacorte** [roughike/BottomBar#39]
Hello, I used the code below, the frame layout have recyclerview, but it doesn't show with BottomBar, only recyclerview or bottombar not both..

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.roughike.bottombar.BottomBar
        android:id="@+id/bb_bottom_bar"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white" />
    <FrameLayout
        android:id="@+id/fragmentContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</LinearLayout>

**Comment by roughike** [comment]
BottomBar doesn't work by XML. 

Try binding it to your fragmentContainer (or it's outer view if it doesn't work):

```java
bottomBar.bind(findViewById(R.id.fragmentContainer), savedInstanceState);
```

**Comment by michelelacorte** [comment]
bind doesn't exist, you mean attach?

**Comment by roughike** [comment]
Yeah, my bad. I'm on mobile and did indeed mean attach.

**Comment by michelelacorte** [comment]
Yes it works, but i need XML view, i've read pull request #14 and with his library it works..

**Comment by roughike** [comment]
Try it on tablets and you'll see what I mean when I say it doesn't work with XML.

Why do you want to specifically inflate it by XML?

**Comment by michelelacorte** [comment]
Nothing, it would be much easier to use, and you may do many things !

**Comment by roughike** [comment]
The XML way is problematic because the tablet issues.

I'm closing this issue as it's now resolved.
