### ISSUE TITLE
Hide BottomBar while RecyclerView scrolling Up and show when it is stopped

### ISSUE THREAD

**Issue by LOG-TAG** [roughike/BottomBar#392]
```
 mBottomBar = BottomBar.attachShy((CoordinatorLayout) rootView.findViewById(R.id.main_cord_content),
                rootView.findViewById(R.id.frag_container), savedInstanceState);

//frag_container is the child fragment id which contains RecyclerView)

```

I'm using RecyclerView withis library , while swiping down (content scrolling down) bottom bar shows , while swiping up(content scrolling up) bottom bar becomes invisible !! (expected Results) 

My requirement is while swiping up once bottom bar becomes invisible that is fine, but once scolling stops Bottom bar should become visible (to improve UX, some user will doesn't know to scroll down make bottom bar visible )

**Comment by DiligentMe** [comment]
Yes, the same question i have. How to check whether is it visible or not, ishown alsways fails and getVisiblity always tells visible. What to do?

**Comment by LOG-TAG** [comment]
@roughike any fix available for this?

**Comment by roughike** [comment]
With the versions 2.3.0 and up, in shy mode, you can show / hide the bar as follows:

```java
// Show:
bottomBar.getShySettings().showBar();

// Hide:
bottomBar.getShySettings().hideBar();
```
