### ISSUE TITLE
Can't change inactive color

### ISSUE THREAD

**Issue by Hary25** [roughike/BottomBar#395]
i cant change inactive color on tab, anyone help?

**Comment by arisprung** [comment]
me too

**Comment by edwinperaza** [comment]
Hi @Hary25 try with this method.

` mBottomBar.setFixedInactiveIconColor(ContextCompat.getColor(context, R.color.primary));`

**R.color.primary** is declared in color.xml, also you need to know that the documentation says:

**NOTE: This value is ignored if not in fixed mode.**

In my project I have more that 3 tabs and I don't want to use the background color so i use

`mBottomBar.setMaxFixedTabs(N);`
`where N > 3.`

**Comment by Hary25** [comment]
your method is not work hmm @edwinperaza

**Comment by roughike** [comment]
Now possible with the version 2.0. and up.

[See here](https://github.com/roughike/BottomBar#all-customization-options)

**Comment by edwinperaza** [comment]
Thanks @roughike  for the new version. I will try it asap.

**Comment by nicknabdullah** [comment]
Hi @roughike @edwinperaza 

Im using 2.1.1 and inactive color don't seem to work.
Tried in xml, like `inActiveColor ="#ffffff"`
As well as in code:

```
for (int i = 0; i < mBottomBar.getTabCount(); i++) {
	mBottomBar.getTabAtPosition(i).setInActiveColor(ContextCompat.getColor(this, R.color.white));
}		
```
But don't seem to work.
