### ISSUE TITLE
Hide/Not hide depending on page in a ViewPager

### ISSUE THREAD

**Issue by Hiike** [roughike/BottomBar#396]
Hi,

I'm using a ViewPager in my project and I used BottomBar.attachShy to allow the first page in the ViewPager to be able de hide/show the bottombar.
What I want is to enable this behavior in the first page only and the next pages will always show the bottombar as if I only used BottomBar.attach.

Should I use BottomBar.attach and implement myself the behavior or is there another way ?

**Comment by roughike** [comment]
With the versions 2.3.0 and up, in shy mode, you can show / hide the bar as follows:

```java
// Show:
bottomBar.getShySettings().showBar();

// Hide:
bottomBar.getShySettings().hideBar();
```
