### ISSUE TITLE
how to use it in xml?

### ISSUE THREAD

**Issue by zhangzhzh** [roughike/BottomBar#4]
How use it in activity_main.xml file rather than in MainActivity.java?

**Comment by roughike** [comment]
I'll look into this.

**Comment by roughike** [comment]
Another problem with inflating it from XML is that on tablets it won't behave properly. It should look [like this](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HSTd3UFY2aEp2ZDg/components_bottomnavigation_usage2.png) but the BottomBar has no way to not overlap your content.

**Comment by roughike** [comment]
So here's what I found about the XML issue:

* A bit awkward to use it directly by xml, as you would have to use a RelativeLayout with two children, your main content with ```android:layout_above="@+id/bottomBar"``` and BottomBar with ```android:layout_alignParentBottom="true"``` set to get started.
* **Even after that it won't behave properly on tablets without extra configuration** from the user (an extra layout in layout-sw600dp folder). It should look [like this](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HSTd3UFY2aEp2ZDg/components_bottomnavigation_usage2.png) but the BottomBar has no way to not overlap content. 

**But you can add the BottomBar practically anywhere to your layout by using ```bottomBar.attach(findViewById(R.id.myView), savedInstanceState)```. This will let you control what View the BottomBar should contain. Basically with this you can put it anywhere in the View hierarchy.**

Using the BottomBar should be as simple as possible and same code should work by default for both tablets and phones solution.

For these reasons, I'm closing this issue.
