### ISSUE TITLE
Probably needs support for night mode

### ISSUE THREAD

**Issue by rosenpin** [roughike/BottomBar#40]
Should probably be auto adjusted to "dark style" if the app is using night mode.

**Comment by roughike** [comment]
Will add this to my TODO list.

Thanks for suggestion!

**Comment by NickM-27** [comment]
Oh yes! This would be perfect since I am using night mode for my dark and light themes.

**Comment by roughike** [comment]
This is now automatically supported starting from library version _1.2.2._

If you for some reason want to disable it:

```java
mBottomBar.ignoreNightMode();
```

Thanks for your great suggestion!
