### ISSUE TITLE
Failed to resolve com.roughike:bottom-bar:1.4.0.1

### ISSUE THREAD

**Issue by shinayser** [roughike/BottomBar#402]
Hey guys!

I've added the  compile 'com.roughike:bottom-bar:1.4.0.1' on my gradle file but I only get this error while trying to build it:

`Error:(207, 13) Failed to resolve: com.roughike:bottom-bar:1.4.0.1`

Anyone knows how to resolve this?

**Comment by sharifi-91** [comment]
i have same problem

**Comment by edwinperaza** [comment]
Hi, 

I do the same now without problem, check again please.

**Comment by adityadey2** [comment]
Hi,I have the same problem.

**Comment by edwinperaza** [comment]
Did you have jcenter()?  @adityadey2 

I am using `compile 'com.roughike:bottom-bar:1.4.0.1'` without problem.

**Comment by adityadey2** [comment]
@edwinperaza  Thanks for the help. I accidentally removed that piece of code. :+1:  Its working fine now.

**Comment by edwinperaza** [comment]
Your welcome @adityadey2
