### ISSUE TITLE
Can't change text color or icon color?

### ISSUE THREAD

**Issue by MiralDesai** [roughike/BottomBar#403]
Seems like quite a basic thing. I tried using some of the available methods however they did nothing.

For example setting the TextAppearance worked on the default tab only, but even then after you move to a different tab, and then back again, the text color reverted back to white.

This is not very useful when the background of the bottom bar is also white. I have assets that are the correct color I want, and this library turns them to white for some reason. Is there a way I can change the tint?

I'm either missing something, or there are just a lot of bugs with this library and basic features missing.

**Comment by midoreigh** [comment]
To change color of text and icon use this in your tabs
```
activeColor="#FAFAFA"
inActiveColor="#FAFAFA"
```

One of my tab is like this

```
<tab
            id="@+id/tab_favorite"
            icon="@drawable/ic_favorite_white_24dp"
            title="Favorite"
            barColorWhenSelected="#FFA726"
            activeColor="#FAFAFA"
            inActiveColor="#FAFAFA" />
```
