### ISSUE TITLE
Always show titles

### ISSUE THREAD

**Issue by squiggie** [roughike/BottomBar#404]
Is there a way to always show the title for an item? I want to have it where there is no icon but just the title and the title always shows. I've tried a combination of settings to achieve this but haven't been successful. I just wanted to know if I was missing something before I start editing code to try and achieve this.

**Comment by sarang1996** [comment]
i think there is no method for only title, creator make this library for specially transactions of both title and icon.

**Comment by vbuberen** [comment]
Confirm, that there is no built-in option to show only titles. So you should modify the library code to get it.
