### ISSUE TITLE
Change typeface

### ISSUE THREAD

**Issue by maddog05** [roughike/BottomBar#41]
Is it possible to change the typeface of the labels by a function like bottomBar.setTypeface(Typeface tf) ?

**Comment by roughike** [comment]
This is not currently built-in, but meanwhile you can use [Calligraphy](https://github.com/chrisjenx/Calligraphy).

**Comment by roughike** [comment]
Just updated the library to version _1.1.2._ and this is now supported.

```java

// Use custom typeface that's located at the "/src/main/assets" directory.
mBottomBar.setTypeFace("MyFont.ttf");
```

**Comment by maddog05** [comment]
Thanks
