### ISSUE TITLE
.hide() & .show() should always animate

### ISSUE THREAD

**Issue by jonasborggren** [roughike/BottomBar#411]
As of now, it only animates if the boolean `isShy` is set to true.

```
protected void setBarVisibility(int visibility) {
        if (mIsShy) {
            toggleShyVisibility(visibility == VISIBLE);
            return;
        }
        ...
}
```

The part that animates should not be kept in that if clause.

**Comment by roughike** [comment]
With the new version, you can just hide / show it just like any other View, animated or not.

**Comment by jonasborggren** [comment]
Great. This isn't by using the BottomBar.getBar() is it? Tried that already and it only moves everything inside the wrapping view.

To help other users searching your issues you should explain how.
