### ISSUE TITLE
BottomBar not visible properly

### ISSUE THREAD

**Issue by Shraddha2702** [roughike/BottomBar#414]
Here is the screenshot of my activity, am not able to figure out what is wrong. Plz Help
![screenshot_2016-08-19-00-48-49-890](https://cloud.githubusercontent.com/assets/20888124/17787564/4cf217be-65a7-11e6-8cd2-4d1010afe44f.jpeg)

**Comment by jd-alexander** [comment]
Seems those icons are way too big. Are they 24 dp?

**Comment by roughike** [comment]
Yep, @jd-alexander is right.

[See here how to create the icons properly.](https://github.com/roughike/BottomBar#creating-the-icons)
