### ISSUE TITLE
Can bottom bar be used programmatically?

### ISSUE THREAD

**Issue by mehrdaad** [roughike/BottomBar#419]
Can we still use ``BottomBar.attachShy`` in version 2+ ?

**Comment by FilipeOS** [comment]
What version 2+?

**Comment by mehrdaad** [comment]
Yes I mean version >2

**Comment by FilipeOS** [comment]
Yes but Is there any +2 version?  Where? What changed?

**Comment by mehrdaad** [comment]
Yes, https://github.com/roughike/BottomBar/blob/master/CHANGELOG.md says they are on 2.0.1.
Are a core contributor?

**Comment by FilipeOS** [comment]
No, sorry. I'm trying to use this and FragNav, I've made some changes but it's not working..

**Comment by FilipeOS** [comment]
Answering your question, no, after I change to v2 a lot of codes got deprecated. You need to make changes according the read me. I can't help you more since my BottomBar+NavFrag is not working anymore even without the nested scroll.....

**Comment by mehrdaad** [comment]
Oh, crap. I hate this kinda work that the developer assumes everybody loves the change.

**Comment by FilipeOS** [comment]
This was a very good change but in my case, I'm not figuring out the solution....

**Comment by mehrdaad** [comment]
Actually I was following a OOP design in my app, so every activity extending BottomBarActivity would have a bottom bar by default. 
It won't work now.

**Comment by FilipeOS** [comment]
I found a perfect solution after a day wasted: https://github.com/aurelhubert/ahbottomnavigation very simple with fragments too, worked like a charm..... FragNav simply sucks.

**Comment by mehrdaad** [comment]
Seems like that lib is more stable that this. @FilipeOS I'd love to hear your experience from that lib.

**Comment by FilipeOS** [comment]
The experience was very good (Be aware that I'm talking about the BottomBar+NavFrag) but.... the content appeared under the bottom navigation and I was not able to fix it... and when you press the tab items did not make the zoom effect leaving always the 1st zoom in....

I'm tired of this, 3 days wasted trying to put a proper bottom nav + fragments working...

**Comment by roughike** [comment]
Will be properly supported in the **2.0.2** version. See [here](https://github.com/roughike/BottomBar/commit/de24fb0abefb32d4f2f66e9c2168c10f47a5a4aa) and [here](https://github.com/roughike/BottomBar/commit/571a3561a278904e0ac1a6468791157a685cc587).
