### ISSUE TITLE
Hiding bar shadow

### ISSUE THREAD

**Issue by renaud-myatlas** [roughike/BottomBar#423]
Hello,

The method BottomBar.hideShadow() has apparently been removed in the v2.
How can I achieve the same action now ?

Thank you!

**Comment by roughike** [comment]
[Possible in the upcoming version](https://github.com/roughike/BottomBar/commit/d37ca485b28ee91e474f85df78239692717a916c)

**Comment by renaud-myatlas** [comment]
Well ... that was quick !
👍
