### ISSUE TITLE
Disable Text Under Icons

### ISSUE THREAD

**Issue by josefkorbel** [roughike/BottomBar#424]
Hello guys, can anyone tell me how to set bottombar to "only icon mode" ? I have the icons moved up, like the text was there, but i want to use only icons, having empty text there is not enought for it apparently, thanks in advance !

**Comment by sayoojvalsan-demandmedia** [comment]
I have the same issue.

**Comment by Mayur-007** [comment]
same problem..

**Comment by alizarei95** [comment]
same for me

**Comment by oradkovsky** [comment]
Actually this library does support icon-only mode, though may be it's not straightforward. If you look into code, you'll notice that TextView's style (your label below icon) is: BB_BottomBarItem_TitleStyle (do not mix with text appearance - that's different). So you can override it like this:

`    <style name="BB_BottomBarItem_TitleStyle" parent="BB_BottomBarItem_TitleStyle">
        <item name="android:visibility">gone</item>
    </style>`

One last bit to do is to change container gravity (container is what hosts tab views like imageview, textview etc)

`        for (int i = 0; i < mBottomBar.getTabCount(); i++) {
            mBottomBar.getTabAtPosition(i).setGravity(Gravity.CENTER_VERTICAL);
        }`

The above works for default BottomBar settings (likely for other settings as well, but I wasn't testing).

**Comment by josefkorbel** [comment]
Wow, it actully work somehow, thanks @oradkovsky

**Comment by akrupych-remit** [comment]
@roughike Please set the gravity to "center" in tab layouts

**Comment by liovincis** [comment]
Ok that seems to work, but the problem is now the icons are too small, is there a way to increase the icon size since there is more space available with the text removed?

**Comment by Shamsul1** [comment]
my issue is total opposite. i don't see any text under icons.

**Comment by sagarc91** [comment]
app:bb_titleTextAppearance="@dimen/bottom_text"

just override this with bottom_text=0dp

**Comment by roughike** [comment]
A duplicate of #373, so closing this one.

Expect to see this with the next release.
