### ISSUE TITLE
Tab Title Text not displaying

### ISSUE THREAD

**Issue by sethlugibihl** [roughike/BottomBar#425]
I followed the guide for version 2.0, and every works besides the text and padding of the icon. The icon for each tab is too large and no title text is being displayed at all. The icons I used followed the standards in the documentation.

**Comment by andreikeda** [comment]
I'm having the same issue.
Logcat shows this message:
requestLayout() improperly called by android.support.v7.widget.AppCompatTextView{ac20783 V.ED..... ......ID 44,138-171,168 #7f0f0086 app:id/bb_bottom_bar_title} during layout: running second layout pass

**Comment by jd-alexander** [comment]
Having this issue also. You guys fixed it?

**Comment by roughike** [comment]
Could you provide some sample code on how you have the tabs and BottomBar setup?

**Comment by gc986** [comment]
I have also not displayed under the buttons.

`<com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_alignParentBottom="true"
        app:bb_tabXmlResource="@xml/bottombar_tabs" />`

`<com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_alignParentBottom="true"
        app:bb_tabXmlResource="@xml/bottombar_tabs" />`

**Comment by wongmingrui** [comment]
any idea when this bug could be fixed?

**Comment by raoravik** [comment]
Facing same issue. The activity layout file is as follows:

```

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context="com.ms.droid.yipyap.activity.MainActivity">
    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    <FrameLayout
        android:id="@+id/frame_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/toolbar"
        android:layout_above="@+id/bottomBar" >
    </FrameLayout>

    <com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_alignParentBottom="true"
        app:bb_tabXmlResource="@xml/bottombar_tabs" />

</RelativeLayout>

```
Tabs XML:
```
<tabs>
    <tab
        id="@+id/tab_home"
        icon="@drawable/ic_home"
        title="Home" />
    <tab
        id="@+id/tab_chat"
        icon="@drawable/ic_chat"
        title="Chats" />
    <tab
        id="@+id/tab_yipyap"
        icon="@drawable/ic_yipyap"
        title="My YipYaps" />
</tabs>
```

BottomBar injected in the view:
```
    @BindView(R.id.bottomBar)
    BottomBar bottomBar;
```

**Comment by raoravik** [comment]
Creating icons through [ Android asset studio generator](https://romannurik.github.io/AndroidAssetStudio/icons-generic.html) solves the issue. Using Android Studio Asset Importer is not working.

**Comment by irshadfadil** [comment]
me too not working with android asset studio generator

**Comment by aya-salama1989** [comment]
confirming the same issue

**Comment by ZXIAOY** [comment]
face the same problem, just use Android Asset Studio and make sure choose two paddings to 0 (there are two paddings to choose,please see it clearly)

**Comment by deepak-karkala** [comment]
@ZXIAOY is right, setting the two paddings to 0 worked for me. The text is now visible.

**Comment by aya-salama1989** [comment]
@ZXIAOY your solution did worked, but still the icons are too small, and i need to enlarge them to match the design, if there's any way to custom the library itself to fit larger icons?

![untitled](https://cloud.githubusercontent.com/assets/8478913/21384211/4120267e-c772-11e6-8ff8-9f801cbf8337.png)

**Comment by AlokCommerce** [comment]
in this condition image height should not be greater than 32dp.
