### ISSUE TITLE
problem displaying the bar

### ISSUE THREAD

**Issue by avivcaspi** [roughike/BottomBar#426]
I`ve follow the instructions about version 2.0 
but when I try to run my app it doesn`t show the bottombar
I`ve tried to check if it shown but it says it doesn`t and when I try to change it`s visibility it does nothing
any suggestions?

**Comment by avivcaspi** [comment]
problem fixed 
it happened beacuse i used linear layout instead of relative one

**Comment by roughike** [comment]
Glad you got it figured out.
