### ISSUE TITLE
How to edit the bar dynamically?

### ISSUE THREAD

**Issue by NickM-27** [roughike/BottomBar#428]
Hello, love the new update! The only issue that I see is that with the last version I had settings that allowed altering of colored items vs same color, shifting of icons, etc. Seeing as these attributes are now defined in xml, there is no way for them to be changed dynamically. Any chance of that change coming / a way to do it that I am missing?

Thanks!

**Comment by roughike** [comment]
Is [this](https://github.com/roughike/BottomBar/commit/44fc8693956e0f032a5df852f44ac34de54ff709) enough for you or do you wish for some more customization? If so, what is that you wish for?

**Comment by NickM-27** [comment]
Was hoping to be able to customize whether the icons shifted or not. Also an option to hide or show the bottom bar would be nice

**Comment by roughike** [comment]
With the latest versions, you're able to customize whether the icons shift or not.

With the versions 2.3.0 and up, in shy mode, you can show / hide the bar as follows:

```java
// Show:
bottomBar.getShySettings().showBar();

// Hide:
bottomBar.getShySettings().hideBar();
```

When not in shifting mode, it's up to you handle showing / hiding the bar, since it's just a regular View.
