### ISSUE TITLE
How about proguard?

### ISSUE THREAD

**Issue by Rainer-Lang** [roughike/BottomBar#43]
Anything known?

**Comment by roughike** [comment]
Do you have any issues?

**Comment by archifishaldev** [comment]
I've just updated to BottomBar 2.0.2, and am now seeing:

Warning: com.roughike.bottombar.BottomNavigationBehavior: can't find referenced class com.roughike.bottombar.VerticalScrollingBehavior$ScrollDirection

Note: the configuration keeps the entry point 'com.roughike.bottombar.BottomBar { void setOnTabSelectListener(com.roughike.bottombar.OnTabSelectListener); }', but not the descriptor class 'com.roughike.bottombar.OnTabSelectListener'
Note: the configuration keeps the entry point 'com.roughike.bottombar.BottomBar { void setOnTabReselectListener(com.roughike.bottombar.OnTabReselectListener); }', but not the descriptor class 'com.roughike.bottombar.OnTabReselectListener'
Note: the configuration keeps the entry point 'com.roughike.bottombar.BottomBarTab { void setConfig(com.roughike.bottombar.BottomBarTab$Config); }', but not the descriptor class 'com.roughike.bottombar.BottomBarTab$Config'
Note: the configuration keeps the entry point 'com.roughike.bottombar.BottomBarTab { void setType(com.roughike.bottombar.BottomBarTab$Type); }', but not the descriptor class 'com.roughike.bottombar.BottomBarTab$Type'

The first of these causes it to fail to build:

Warning: there were 1 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)

I imagine I can fix it up locally, but thought I'd post on here as a relevant issue number :)

**Comment by archifishaldev** [comment]
Actually issue #456 may cover this already (this was the first one that showed up in a Google search).
