### ISSUE TITLE
Latest version 2.+ no longer supports setActiveTabColor

### ISSUE THREAD

**Issue by natemcintyre** [roughike/BottomBar#431]
I have written some wrappers that let me programmatically change colors within my app and part of that process is when the toolbar color changes I also change the active tab color to reflect the new color. It appears in the latest version you just released you no longer support the ability to call setActiveTabColor from code and instead require that the color is set in the xml file. I would MUCH prefer to have setActiveTabColor back please.

**Comment by roughike** [comment]
I added support for that and all other properties for the upcoming version **2.0.2**.

[See the commit here.](https://github.com/roughike/BottomBar/commit/44fc8693956e0f032a5df852f44ac34de54ff709)

I will release the new version during this weekend.
