### ISSUE TITLE
Library does not work correctly in android 7.0

### ISSUE THREAD

**Issue by AdamLuisSean** [roughike/BottomBar#432]
![photo_2016-08-24_10-22-54](https://cloud.githubusercontent.com/assets/10870984/17921866/bd16ee02-69e4-11e6-873f-a64b1f3f46ed.jpg)

**Comment by roughike** [comment]
Hi!

I can't reproduce your problem.

What is the device you're using? And is that the sample app? If not, does the sample app behave that way?

**Comment by tinOfBeans** [comment]
any fixes for this?

**Comment by AdamLuisSean** [comment]
@tinOfBeans What is the device you're using?

**Comment by tinOfBeans** [comment]
@AdamLuisSean nexus 6.  I edited original comment with more info

**Comment by AdamLuisSean** [comment]
@tinOfBeans I have this issue on nexus 5X Android 7.1.1
