### ISSUE TITLE
onTabSelected tabId always return as 1 in Version 2.0

### ISSUE THREAD

**Issue by hencechen** [roughike/BottomBar#435]
when i select the tab found the tab id is always return as 1.

 bottomBar.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelected(@IdRes int tabId) {
                Log.d(LOG_TAG, "tab selected " +tabId);

**Comment by hencechen** [comment]
i found the issue, tab bar should be define as in instead of android:id.

**Comment by percula** [comment]
@hencechen I may be having a similar issue. setOnTabSelectListener is not working for me. What do you mean by "define as in instead of android:id"? Thanks!

**Comment by tysheng** [comment]
@percula write like this way.Don't put "android:" prefix

**Comment by tysheng** [comment]
@percula 
https://github.com/roughike/BottomBar/blob/master/app/src/main/res/xml/bottombar_tabs_three.xml

**Comment by razzerdx** [comment]
I have the same issue as hencechen did, but i can't use "id="@+id/...". It says "Attribute is missing the android namespace prefix".
