### ISSUE TITLE
Non-highlighted title text is cut off

### ISSUE THREAD

**Issue by kevinschlieper** [roughike/BottomBar#436]
Hi,

I have noticed that the bottom part of the title text is cut off. However, for some reason that doesn't seem to be a problem for the first tab, but only for the 2nd and 3rd (only tested with 3 tabs). You can see the problem in the sample app as well.

**Steps to reproduce:**
1. Start BottomBar sample app.
2. Choose "SIMPLE EXAMPLE WITH THREE TABS"
3. Observe the 2nd tab

**Actual behavior:**
The "y" is cut off (but only in the non-highlighted state).

**Expected behavior:**
Text shouldn't be cut off.

![bottombar text cut off](https://cloud.githubusercontent.com/assets/3967453/17936800/4b7664c6-6a20-11e6-8450-6a36b5aa5800.png)

Let me know if you need more input.

Kevin

**Comment by smoothdvd** [comment]
I have same bug, and the cut off value is random.

**Comment by flukeylukey** [comment]
Hi, I'm having the same bug too. I have 4 tabs. The 3rd tab title is "History", and 'y' is cut off when non-highlighted.

**Comment by MilesGoon** [comment]
![image](https://cloud.githubusercontent.com/assets/10042644/17991359/5603d1ac-6b70-11e6-9765-7e1d2d2daf04.png)  

oooooh, My title was hidden too :(

**Comment by roughike** [comment]
It was related to the ```updateTitlePadding()``` method that was merged from someone else's PR.

The fix will be released with the version **2.0.3**.

**Comment by smoothdvd** [comment]
@roughike Thanks

**Comment by Ovadia-B** [comment]
I fixed it with this style: 
`
    <style name="BB_BottomBarItem_TitleStyle">
        <item name="android:maxLines">1</item>
        <item name="android:height">24dp</item>
        <item name="android:gravity">center_horizontal</item>
    </style>`

**Comment by yuriChechetkin** [comment]
@Ovadia-B where should i apply this style?

**Comment by rudakovsky** [comment]
I am facing the same problem but only after I call DialogFragement from Fragment on a tab

**Comment by Ovadia-B** [comment]
@yuriChechetkin
Just copy & paste those lines in your styles.xml file, it will override the style from the library.

**Comment by tomaszczura** [comment]
Same for me, but applying style doesn't work. When do you plan to release 2.0.3 version?

**Comment by daveak01** [comment]
Will keep an eye on this thread and away 2.0.3.

Great work @roughike, keep it up!!

**Comment by mkmckenna** [comment]
@Ovadia-B Thanks, that worked for me.

**Comment by dmitriialeksandrov** [comment]
For guys who have issues with temporary workaround by @Ovadia-B, you can also add <item name="android:includeFontPadding">false</item> into the style above, it did the trick for me.

**Comment by Ovadia-B** [comment]
Google released new API in support library v25 with BottomNavigationView. 

[New APIs](https://developer.android.com/topic/libraries/support-library/revisions.html)
> android.support.design.widget.BottomNavigationView class implements the bottom navigation pattern from the Material Design spec.

**Comment by huttarl** [comment]
Thanks @dmitriialeksandrov, that helped --  it reduced the amount of text cut off, but didn't get rid of it completely. Any other ideas?
