### ISSUE TITLE
Can't change badge color, its RED hardcode :(

### ISSUE THREAD

**Issue by grestuccia1** [roughike/BottomBar#438]

**Comment by roughike** [comment]
Hi!

Actually you can specify custom colors for each tab, but the documentation is incomplete at the moment.

```xml
<tab
    id="@+id/tab_nearby"
    icon="@drawable/ic_nearby"
    title="Nearby"
    badgeBackgroundColor="#00FF00" />
```

I'll add some more customization for the badge backgrounds to the version **2.0.2** and close this issue when I'm done.
