### ISSUE TITLE
Weird navigation behavior

### ISSUE THREAD

**Issue by omeadaen** [roughike/BottomBar#44]
Not sure if it's just me.. but I have 5 menu items.. I can't seem to get back to home (0).

I can click and go through all the others fine but clicking home doesn't work.  except on the one activity which I have: mBottomBar.selectTabAtPosition(2, false); set in the onResume.. and that ONLY works if I go to menu item 2 then 3, hit return, and then click on 0.

If I click on item 2, then back to home it doesn't work.

**Comment by roughike** [comment]
How are you using it? Could you provide some Java and XML code samples?

**Comment by roughike** [comment]
Just updated the library to version _1.1.2._, try and see if this works now.
