### ISSUE TITLE
Can you support icon drawable selector?

### ISSUE THREAD

**Issue by interchen** [roughike/BottomBar#440]
I want to custom icon drawable, not only change color. So can you support selector?

**Comment by Maritt** [comment]
Are there any plans for supporting this? @roughike

**Comment by yombunker** [comment]
this is currently in PR

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
