### ISSUE TITLE
Badgets are cut

### ISSUE THREAD

**Issue by avivcaspi** [roughike/BottomBar#448]
Hello
I`ve noticed that every time i`m on tab which has badge and then I clicked the tab next to it on the right
it makes the badge cut and you can see only half number

**Comment by roughike** [comment]
Can you provide some more info? How many tabs do you have? Does this issue happen on tablet or mobile?

**Comment by avivcaspi** [comment]
The issue happens on mobile, I`ve got 5 tabs
and it happens on the fifth tab
so when the fifth tab is clicked the badge is hidden and if I click the forth tab the badge comes back in the same place it was suppose to be if it was visible when the fifth tab was clicked (I`m using shifting behavior so the selected tab get a bit bigger) so the badge is cut in half

**Comment by roughike** [comment]
You're absolutely right. I have a fix coming up in the next version.

**Comment by ViHtarb** [comment]
Hi, when the version 2.0.3? I`m very needs in this fix :)

**Comment by h0rn3t** [comment]
I also vary need this fix

**Comment by aToO57** [comment]
Same here 👍

**Comment by mbarashkov** [comment]
Manual fix is simple: just comment out updateTitleBottomPadding() in BottomBar.java
It's supposed to add some font padding (10dp) to comply with Material guidelines, but in reality it does nothing but cut textviews.

**Comment by SachinTanpure** [comment]
Hi, when the version 2.0.3 will release? This issue is really bad for UX point of view
