### ISSUE TITLE
How bottomBar 2.0 work with fragments?

### ISSUE THREAD

**Issue by coolmenu** [roughike/BottomBar#465]
Have anyone give a demo bottomBar 2.0 work with fragments? thanks.

**Comment by Boxroma** [comment]
Try this 

*main activity*
`public class MainActivity extends AppCompatActivity {
    /*private TextView messageView;*/

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

       /* messageView = (TextView) findViewById(R.id.messageView);*/

        BottomBar bottomBar = (BottomBar) findViewById(R.id.bottomBar);
        bottomBar.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelected(@IdRes int tabId) {
                FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
                switch (tabId){
                    case R.id.tab_favorites:
                        BlankFragment favoritesFragment = new BlankFragment();
                        fragmentTransaction.replace(R.id.fragment_container,favoritesFragment);
                        fragmentTransaction.commit();
                        break;
                    case R.id.tab_nearby:
                        BlankFragment nearbyFragment = new BlankFragment();
                        fragmentTransaction.replace(R.id.fragment_container,nearbyFragment);
                        fragmentTransaction.commit();
                        break;
                    case R.id.tab_friends:
                        BlankFragment friendsFragment = new BlankFragment();
                        fragmentTransaction.replace(R.id.fragment_container,friendsFragment);
                        fragmentTransaction.commit();
                        break;
                }
                /*messageView.setText(TabMessage.get(tabId, false));*/
            }
        });

        bottomBar.setOnTabReselectListener(new OnTabReselectListener() {
            @Override
            public void onTabReSelected(@IdRes int tabId) {
                Toast.makeText(getApplicationContext(), TabMessage.get(tabId, true), Toast.LENGTH_LONG).show();
            }
        });
    }
}`


Main Activity xml
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />


    <com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_alignParentBottom="true"
        app:bb_tabXmlResource="@xml/bottombar_tabs_three" />

</RelativeLayout>
`


Blank Fragmemt java

`public class BlankFragment extends Fragment {
    private static final String ARG_TEXT = "ARG_TEXT";

    public BlankFragment() {
    }

    public static BlankFragment newInstance(String text) {
        Bundle args = new Bundle();
        args.putString(ARG_TEXT, text);

        BlankFragment sampleFragment = new BlankFragment();
        sampleFragment.setArguments(args);

        return sampleFragment;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        return inflater.inflate(R.layout.fragment_blank,container,false);
    }
}`

Blank Fragment xml
`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.clusterbox.dmiapp.BlankFragment">

    
    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="@string/hello_blank_fragment" />

</FrameLayout>`

**Comment by Boxroma** [comment]
The code doesn't seem to be displayed right but I hope you get a general gist.. if you have looked at any of the other demos this should be pretty clear

**Comment by coolmenu** [comment]
Thanks a lot !!!

**Comment by CoXier** [comment]
You should create `FragmentTransaction` every time user select a tab or you will get 
```java
java.lang.IllegalStateException: commit already called
```
