### ISSUE TITLE
Three icons BottomBar background color

### ISSUE THREAD

**Issue by alorma** [roughike/BottomBar#47]
Hi, that's mentioned earlier in other issues, but i open a new one  just to discuss it.

Material design specs doesn't cover the light with light problem:

It will be great if we can set a color for the BottomBar at anytime,  and also will be cool to have a custom attribute to set it via theme.

If you want i can open a PR for it

**Comment by roughike** [comment]
I'll add this.

**Comment by alorma** [comment]
https://github.com/roughike/BottomBar/pull/48
