### ISSUE TITLE
Bottom bar Icons/textView disappear when pressed multiple times

### ISSUE THREAD

**Issue by firetrap** [roughike/BottomBar#471]
The issue is when the tabs are selected multiple times they start to disappear as you can see here:
![bottombar](https://cloud.githubusercontent.com/assets/655828/18166433/145bfb3a-7043-11e6-820f-211ae2246be4.gif)

I think this problem it's related with this warning:

> requestLayout() improperly called by android.support.v7.widget.AppCompatTextView{d8cc000 V.ED..... ......ID 103,96-257,168 #7f100088 app:id/bb_bottom_bar_title} during layout: running second layout pass

After several "clicks" it will force close with "java.lang.OutOfMemoryError" as you can see:

> java.lang.OutOfMemoryError: Failed to allocate a 2555148 byte allocation with 2261680 free bytes and 2MB until OOM
>                                                                              at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
>                                                                              at android.graphics.Bitmap.nativeCreate(Native Method)
>                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
>                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
>                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
>                                                                              at android.graphics.drawable.VectorDrawable$VectorDrawableState.createCachedBitmapIfNeeded(VectorDrawable.java:834)
>                                                                              at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:318)
>                                                                              at android.widget.ImageView.onDraw(ImageView.java:1244)
>                                                                              at android.view.View.draw(View.java:16178)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15174)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.support.design.widget.CollapsingToolbarLayout.drawChild(CollapsingToolbarLayout.java:302)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.draw(View.java:16181)
>                                                                              at android.support.design.widget.CollapsingToolbarLayout.draw(CollapsingToolbarLayout.java:263)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15174)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.draw(View.java:16181)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15174)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1140)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.draw(View.java:16181)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15174)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1140)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15169)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.draw(View.java:16181)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15174)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15169)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15169)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15169)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15169)
>                                                                              at android.view.View.draw(View.java:15948)
>                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>                                                                              at android.view.View.draw(View.java:16181)
>                                                                              at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
>                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15174)
>                                                                              at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
>                                                                              at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
>                                                                              at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
>                                                                             at android.view.ViewRootImpl.draw(View

**Comment by roughike** [comment]
Will investigate and fix for the version 2.0.3 which will be released during the weekend.

**Comment by mubarak1361** [comment]
@roughike am also having same issue when screen orientation changed.

**Comment by chip2n** [comment]
I encountered this issue when switching between two tabs whose views have different window insets. In my case, I was using CoordinatorLayout.setFitsSystemWindows(true/false) together with CoordinatorLayout.requestApplyInsets() in order to have the system bar overlay one of the tab views but not the other. This seems to be the case in your animation as well.

**Comment by rmeruane** [comment]
Any news about this?

**Comment by eul** [comment]
+1
