### ISSUE TITLE
Unsure how to change colors

### ISSUE THREAD

**Issue by mimoccc** [roughike/BottomBar#472]
Is there any way to change colors? Or all color functions are only for bigger code?
Why there is in every repository another version of ?

Surprised

Milan

**Comment by roughike** [comment]
Do you wish to change the color of the whole BottomBar like in [this gif](https://raw.githubusercontent.com/roughike/BottomBar/master/graphics/shifting-demo.gif) or do you wish to change the icon and title colors of individual tabs?

If the former, the readme is your friend:
[](https://github.com/roughike/BottomBar#those-color-changing-tabs-look-dope-howdoidodat)

If the latter, just add ```activeColor``` to each individual tab and set it to whatever color you like. [See all tab customization options for tabs here](https://github.com/roughike/BottomBar#for-the-tabs)

**Comment by mimoccc** [comment]
Well there almost nothing works. Too many bugs, too many issues.
I will write my own bar.
Wish you success.
Thanx
--
Sent from myMail app for Android štvrtok, 01 septembra 2016, 06:44popoludní +02:00 from Iiro Krankka  notifications@github.com :
