### ISSUE TITLE
Is is possible to change the textsize of the items ?

### ISSUE THREAD

**Issue by laurentmorvillier** [roughike/BottomBar#482]
Thanks a lot for the work!

**Comment by JesseWo** [comment]
`    <style name="CustomTitleTextAppearance">
        <item name="android:textSize">23sp</item>
        <item name="android:textStyle">bold</item>
    </style>`
above setting can not work...

**Comment by laurentmorvillier** [comment]
Found out it is possible!

You have to use setTextAppearance()

in your Activity:

`        mBottomBar.setTextAppearance(R.style.bottomBarTextView);`

then define the corresponding style in styles.xml

```
    <style name="bottomBarTextView" parent="@android:style/TextAppearance.Widget.TextView">
        <item name="android:textSize">10dp</item>
    </style>
```

**Comment by archifishaldev** [comment]
I think you can set it in the XML too if you want - see https://github.com/roughike/BottomBar#for-the-bottombar (the bb_titleTextAppearance).
