### ISSUE TITLE
Display just active tab title not working !!!!

### ISSUE THREAD

**Issue by papmodern** [roughike/BottomBar#487]
As material design principle, If tab counts is more than 4 , title of other tabs except activated one must be disappears. 
Even you illustrated that in gif demo of README!

But there is no options for that .

**Comment by roughike** [comment]
There's options for that, specifically by setting the ```bb_behavior``` to ```shifting```. The BottomBar doesn't automatically force itself to do that, and I think it shouldn't. This was a popular complaint on the first version, as it automatically changed itself to be a shifting one.
