### ISSUE TITLE
setRetainInstance in Fragment don't support?

### ISSUE THREAD

**Issue by lnfn** [roughike/BottomBar#49]
#My Fragment with setRetainInstance = true restore OnCreate() -> OnDestroy() when chanhge orientation

**Comment by roughike** [comment]
I guess you're using the ```bottomBar.setFragmentItems()``` method?

**Comment by lnfn** [comment]
Yes

**Comment by roughike** [comment]
I actually have a pretty good hunch what this is about. I'll fix this for the next version.

**Comment by lnfn** [comment]
Thank you, we will wait. Method clearItems() remove FragmentManager.

**Comment by roughike** [comment]
This proved to be tricky, and couldn't fix it for the newest version. 

For now I recommend you handle updating the fragments by yourself. So instead of using ```setFragmentItems()```, use ```setItems()``` with a listener for tab changes.

**Comment by roughike** [comment]
Updated the library to version _1.1.3._

Should work now.

Thanks for reporting the issue!
