### ISSUE TITLE
Only show titles under active Tab

### ISSUE THREAD

**Issue by Cplantijn** [roughike/BottomBar#493]
Right now I have my bottombar showing icons only by overriding the styles.xml with

``` xml
<style name="BB_BottomBarItem_TitleStyle" parent="BB_BottomBarItem_TitleStyle">
    <item name="android:visibility">gone</item>
</style>
```

I would like the active tab to show it's title. Sort of like this example on the official bottom bar Material Guidelines. 

![screen shot 2016-09-13 at 12 24 23 am](https://cloud.githubusercontent.com/assets/6914382/18461522/78145632-7948-11e6-9145-7363925b46f5.png)

Is this currently possible?

**Comment by rihantvx** [comment]
@Cplantijn yes it is possible , build and run the sample app and you should see the behaviour . Check this class as well https://github.com/roughike/BottomBar/blob/master/app/src/main/java/com/example/bottombar/sample/FiveColorChangingTabsActivity.java

**Comment by Cplantijn** [comment]
Thank you @rihantvx !
