### ISSUE TITLE
Change BottomBar show/hide state?

### ISSUE THREAD

**Issue by dah4oz** [roughike/BottomBar#496]
I am using the latest version of the library (2.0.2). The auto hide bottom bar on scroll works well.
However, in some cases it's required to handle the show/hide state manually. 
Other possible solution would be to change the BottomBar behavior programatically.

**Comment by rabross** [comment]
+1 for this feature

**Comment by stepansanda** [comment]
+1 must have feature

**Comment by jamesbaltar** [comment]
+1

**Comment by Lintom** [comment]
Hi. Use `mBottomBar.setVisibility(View.VISIBLE)` and `mBottomBar.setVisibility(View.GONE)`

**Comment by rabross** [comment]
@Lintom, most people here want the animation that comes along with show/hide

**Comment by dah4oz** [comment]
Indeed! Animation that shows/hides the view on scroll.

**Comment by mStepkowski** [comment]
`mBottomBar.animate().translationY(0); `
-> Show?

**Comment by Sundin** [comment]
+1

**Comment by roughike** [comment]
With the versions 2.3.0 and up, in shy mode, you can show / hide the bar as follows:

```java
// Show:
bottomBar.getShySettings().showBar();

// Hide:
bottomBar.getShySettings().hideBar();
```
