### ISSUE TITLE
How does it work with viewpager?

### ISSUE THREAD

**Issue by tinybright** [roughike/BottomBar#5]

**Comment by roughike** [comment]
It doesn't at this time. I'll look into it and see if it should / can be done.

It seems that this is not meant to be an indicator for ViewPager though:

> Using swipe gestures on the content area does not navigate between views.
- [Bottom Navigation specs](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-behavior)

**Comment by roughike** [comment]
I won't make this a ViewPager indicator for now. 

What you want can easily be implemented by adding OnPageChangeListener to your ViewPager and selecting tabs manually:

```java
ViewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
    @Override
    public void onPageSelected(int position) {
        // select a new tab and animate the selection.
        bottomBar.selectTabAtPosition(position, true);
    }
});
```

**Comment by gvete** [comment]
Avoid recursion by adding condition check.        



mViewer.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                // select a new tab and animate the selection.
                 if(position != mBottomBar.getCurrentTabPosition())
                mBottomBar.selectTabAtPosition(position, true);
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });
