### ISSUE TITLE
How to show all titles visible and set custom position ?

### ISSUE THREAD

**Issue by Neustart** [roughike/BottomBar#50]
Hi. Thank you for your amazing lib!
I have a few questions, answer on which I didn't find at documentation.
1) how can I make title always visible for all tabs? As on your first example animation on the readme.
2) How can I create my activity with BottomBar wich will stay by default on the second position, for example?

**Comment by NickM-27** [comment]
Not the Dev but,
1. You have to have 3 items or less, otherwise it only shows the selected item title (per the material design guidelines)
2. What do you mean by stay at the default second position?

**Comment by roughike** [comment]
Thanks and I'm glad you like the library!

1. As @NickM-27 said, it's  not currently possible for BottomBars that have more than three tabs. This behavior is according to the Material Design Guidelines.
2. Use the ```selectTabAtPosition()``` method for selecting tabs. So something like this:

```java
// Remember to set the items before using this method!
mBottomBar.selectTabAtPosition(2, false);
```
