### ISSUE TITLE
Gradle Issue

### ISSUE THREAD

**Issue by shafaque** [roughike/BottomBar#500]
Error:(73, 0) No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.
<a href="openFile:C:\Users\----\Desktop\BottomBar-master\BottomBar-master\bottom-bar\build.gradle">Open File</a>
 Redirecting to line : 
apply plugin: 'com.github.dcendents.android-maven'

**Comment by makzimi** [comment]
@shafaque I have the same problem. Do u solve this issue?

**Comment by collins001** [comment]
I'm having the same issue, I'm using android studio 2.2, I've downloaded api 23 to match with the bottombar, but its still not working. 
Can someone please help.

**Comment by collins001** [comment]
I'm having the same issue, I'm using android studio 2.2, I've downloaded api 23 to match with the bottombar, but its still not working. 
Can someone please help.

**Comment by collins001** [comment]
If you have found a way around this issue, please share with us. 
Thank you

**Comment by collins001** [comment]
It solved for me when i updated my dependencies
old:
classpath 'com.github.dcendents:android-maven-
gradle-plugin:1.3'
new:
classpath 'com.github.dcendents:android-maven-
gradle-plugin:1.4.1'

https://code.google.com/p/android/issues/detail?id=219692#c4

You need to be online to update maven gradle

**Comment by buildunr** [comment]
@collins001 Thanks alot manh..
