### ISSUE TITLE
How to use a custom drawable？help help help..

### ISSUE THREAD

**Issue by zhangXiaolizi** [roughike/BottomBar#502]
my tabs icon use custom drawable , example:
`<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/tabbar_index_s" android:state_pressed="true"/>
    <item android:drawable="@drawable/tabbar_index_s" android:state_selected="true"/>
    <item android:drawable="@drawable/tabbar_index_n"/>
</selector>`
But it has no effect , Could you tell me how to handle this? thank you

**Comment by yombunker** [comment]
@zhangXiaolizi this is in PR currently, it will only add the selected state, not the press state for now

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
