### ISSUE TITLE
Badge auto hide when tab selected

### ISSUE THREAD

**Issue by jenzoned** [roughike/BottomBar#510]
Badge is auto hide when tab is selected. 
How to make it appear even if the tab is selected?

**Comment by ivandiazmolina** [comment]
Is it fixed already? I have this error with last version (2.0.2)

**Comment by jenzoned** [comment]
No, sadly, you have to edit the source code of the library.

**Comment by ivandiazmolina** [comment]
@jenzoned I guess that I have to create a new class with the same code and edit because gradle library cant edit

**Comment by jenzoned** [comment]
@ivandiazmolina  yep, that's what I did. and it worked. :+1:

**Comment by ivandiazmolina** [comment]
@jenzoned Can you copy me your code?

**Comment by alashow** [comment]
You can use this until @roughike fixes it.

```groovy
compile 'com.github.alashow:BottomBar:v2.0.3-donthidebadge'
```

**Comment by j-garin** [comment]
@alashow thank you for this library

**Comment by ssawchenko** [comment]
I would also like to +1 for this support to be included in the base library. I will have to look into a work around as well until then.

**Comment by narzero** [comment]
Would be great if this could be fixed

**Comment by roughike** [comment]
This is fixed in the version 2.1.1.

For the whole BottomBar:

```
app:bb_badgesHideWhenActive="false"
```

For a single tab:

``` 
badgeHidesWhenActive="false"
```

**Comment by yombunker** [comment]
@roughike is in version 2.1.2 not 2.1.1

**Comment by roughike** [comment]
Good catch, updated the comment.
