### ISSUE TITLE
Remove attributes from manifest's Application

### ISSUE THREAD

**Issue by gowong** [roughike/BottomBar#52]
A library shouldn't declare unnecessary attributes on the `Application` as doing so will automatically merge them into app's manifest. For example, an app that doesn't declare `supportsRtl` will now have it set to true after importing this library, even though the default value should be false.

` BottomBar/bottom-bar/src/main/AndroidManifest.xml`
```xml
<application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true">

</application>
```

**Comment by roughike** [comment]
Fixed in library version _1.1.2._
