### ISSUE TITLE
barColorWhenSelected Programmatically 

### ISSUE THREAD

**Issue by MikelCalvo** [roughike/BottomBar#523]
Is there any way to change the Bottom Bar background color programmatically?
I'm trying to add an option where the user can decide the bar color.
Thanks in advance!

**Comment by JEKos** [comment]
+1

**Comment by nicchong** [comment]
Did you manage to solve the problem? I'm trying to achieve the same goal

**Comment by MikelCalvo** [comment]
I change the color with 
`mBottomBar.setBackgroundColor(ContextCompat.getColor(getApplicationContext(), R.color.primary));`

Also make sure to add this to the xml object:
`app:bb_showShadow="false"`

**Comment by Kiruel** [comment]
Not working for me.

**Comment by roughike** [comment]
[Possible in the upcoming 2.1.0 version](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBarTab.java#L249)

**Comment by wdavies973** [comment]
I figured it out.

Assuming you have two tabs, try this:

`BottomBar bBar = (BottomBar) findViewById(R.id.bottomBar);
bBar.setOnTabSelectListener(this, true); // make sure you have the true arguement

BottomBarTab tab1 = bBar.getTabAtPosition(0);
tab1.setBarColorWhenSelected(Color.WHITE)
BottomBarTab tab2 = bBar.getTabAtPosition(1);
tab2.setBarColorWhenSelected(Color.WHITE)`

It's a bit clumsy, but it works.
