### ISSUE TITLE
how to create fragments in bottombar 2.0?

### ISSUE THREAD

**Issue by jashankc** [roughike/BottomBar#526]
I have seen previous issue but didn't help..

**Comment by sliferdroid** [comment]
Based on the sample, I have mines like this. 
Important: Inside activity_main or whatever layout your BottomBar is, make sure you name the Parent Frame/Linear/Relative/Coordinator layout. I named mines 'layout' as you will see in the 2nd function
`    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        BottomBar bottomBar = (BottomBar) findViewById(R.id.bottomBar);
        bottomBar.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelected(@IdRes int tabId) {
                if (tabId == R.id.btab_left) {
                    commitFragment(new YourFragment());

                }

            }
        });
`

`    private void commitFragment(Fragment fragment){
        android.support.v4.app.FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
        fragmentTransaction.replace(R.id.layout, fragment);
        fragmentTransaction.commit();
    }
`
