### ISSUE TITLE
Not showing titles

### ISSUE THREAD

**Issue by IvanSyabro** [roughike/BottomBar#531]
![9b3c3c0a23](https://cloud.githubusercontent.com/assets/20424848/19121121/f7257cb6-8b2d-11e6-8232-b2ea9d4a715b.jpg)

**Comment by IvanSyabro** [comment]
Device: Nexus 5x, API 24 (Android 7.0)

**Comment by timrijckaert** [comment]
Same problem here. Nexus 6P Android 7.0

**Comment by timrijckaert** [comment]
Possible duplicate of #474

**Comment by elaman16** [comment]
Like rickytribbi,
Works also for me checking out both paddings = 0 in Android asset studio generator!

**Comment by timrijckaert** [comment]
Using the site it indeeds works. But since Android Studio has a drawable importer it would be nice that it would play along with that one.

**Comment by KirillMakarov** [comment]
Same in #530

**Comment by zhaoyou** [comment]
I work for me. use Android asset studio generator

![screen shot 2016-10-19 at 4 45 28 pm](https://cloud.githubusercontent.com/assets/612257/19511816/9290823e-961b-11e6-908c-3a300a1ce4d6.png)

**Comment by silviahisham** [comment]
same problem

**Comment by zbrook** [comment]
This advice worked to allow an image asset created from Android Studio to work:
https://github.com/roughike/BottomBar/issues/474#issuecomment-256051845

> When adding an Image Asset to your Drawable folder, chose Notification Icons instead of the regular Action Bar and Tab Icons - worked fine !

**Comment by roughike** [comment]
Should be fixed in latest versions.
