### ISSUE TITLE
Truncating character "y" in the bottom bar

### ISSUE THREAD

**Issue by MuralikrishnaM** [roughike/BottomBar#538]
One of my bottom bar tab title is "My Home", all the letters are getting displayed properly except "y". The bottom part of y is getting truncated, how can i get rid of it?

**Comment by MuralikrishnaM** [comment]
Can any one suggest me please

**Comment by MuralikrishnaM** [comment]
The problem is with the height of the icons, they shd be 24X24 ideally for mdpi devices.

**Comment by SunilKushwah** [comment]
i also have the same problem, tab title bottom part is getting truncated in kitkat while in marshmallow everything is fine

**Comment by Quix0tic** [comment]
Same problem here

**Comment by Quix0tic** [comment]
I found the solution elsewhere (it works for me)
`    <com.roughike.bottombar.BottomBar
... 
app:bb_titleTextAppearance="@style/BB_BottomBarItem_TitleStyle" />`

In `styles.xml` add
`<style name="BB_BottomBarItem_TitleStyle">
        <item name="android:maxLines">1</item>
        <item name="android:height">24dp</item>
        <item name="android:gravity">center_horizontal</item>
    </style>`

**Comment by roughike** [comment]
This is solved in versions 2.1.0 and up.
