### ISSUE TITLE
selectTabAtPosition(...) should also update the current fragment

### ISSUE THREAD

**Issue by gowong** [roughike/BottomBar#54]
Awesome job with the library!

I was surprised to see that `selectTabAtPosition(...)` only updates the selected tab and not the current fragment. It should update both or there should be a separate method that does it.

**Comment by gowong** [comment]
Also saw in the code that calling `selectTabAtPosition(...)` doesn't update `BottomBar.mCurrentTabPosition`. It probably should so that the right tab index is passed to `OnTabSelectedListener`

**Comment by roughike** [comment]
Just updated the library to version _1.1.2._, try and see if this works now.

**Comment by gowong** [comment]
Awesome, can confirm this is fixed. :+1:

**Comment by roughike** [comment]
Nice!

Thanks for reporting it.
