### ISSUE TITLE
Rendering Problems: The following classes could not be instantiated: - com.roughike.bottombar.BottomBar

### ISSUE THREAD

**Issue by SirRob1997** [roughike/BottomBar#540]
Hey Guys,

so I've compiled: 'com.roughike:bottom-bar:2.0.2'
defined my tabs in the xml file: res/xml/bottombar_tabs.xml with the drawables.
and added the bottom bar to my layout/activity_main.xml and gave it the resource on the tabs.

However when i click on "Design" instead of "Text" I'm getting the Problem:

Rendering Problems: The following classes could not be instantiated: - com.roughike.bottombar.BottomBar

what am i missing or what do i need to do, to solve my problem?
(already tried the exact code as stated in the tutorial)

Greetings
Robin

Edit: also added drawables

**Comment by jcarhuazv** [comment]
Test this solution. This answer helped me. [http://stackoverflow.com/questions/26575815/the-following-classes-could-not-be-instantiated-android-support-v7-widget-too]

**Comment by s-nour** [comment]
Hello there, 
I am having the same problem, tried the solutions in the link @jcarhuazv  provided, but none of them worked for me.

**Comment by aToO57** [comment]
Hello, I am having the same problem.

Someone can give more detail for fix this ?

**Comment by alaershov** [comment]
Same problem here. Invalidate caches does not help.

**Comment by Lucifer-YU** [comment]
I have the same problem...

**Comment by dons20** [comment]
Currently having this problem as well. Unable to preview my layout properly because of it.
