### ISSUE TITLE
If toolbar is gone, blank space remains.

### ISSUE THREAD

**Issue by OzgurGorgulu** [roughike/BottomBar#545]
If toolbar gone, blank space remains. It's only 4 buttons.
I'm adding style.xml that's code:

`<item name="windowActionBar">false</item>`
`<item name="windowNoTitle">true</item>`
### Before Adding ↓ (As you can see, everything is OK.)

![screenshot_20161013-123936](https://cloud.githubusercontent.com/assets/6717356/19344322/674296cc-9142-11e6-969e-f4f80b17cb02.png)
### After Adding ↓ (Problem is here.)

![screenshot_20161013-124054](https://cloud.githubusercontent.com/assets/6717356/19344323/67484176-9142-11e6-93a0-47bf4587e1b9.png)

**Comment by AndroidSources** [comment]
Facing the same problem

**Comment by Ibtihaaj** [comment]
Getting same issue. Any solution?
