### ISSUE TITLE
Tabs text gets cut off for unselected tabs

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [roughike/BottomBar#546]
I have integrated BottomBar. The issue I am having is that the tabs text gets cut off from bottom for unselected tabs.Below is the code I am using.How can i resolve it?

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".activity.HomeActivity">

...
    <com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp70"
        android:layout_alignParentBottom="true"
        app:bb_tabXmlResource="@xml/bottombar_tabs" />
</RelativeLayout>
bottombar_tabs.xml

<?xml version="1.0" encoding="utf-8"?>
<tabs xmlns:android="http://schemas.android.com/apk/res/android">
    <tab
        id="@+id/tab_h"
        icon="@drawable/ic_home"
        title="Hwgaewg" />
    <tab
        id="@+id/tab_r"
        icon="@drawable/ic_recharge"
        title="Rfegerh" />
    <tab
        id="@+id/tab_esh"
        icon="@drawable/ic_esh"
        title="Efdsf vd" />
    <tab
        id="@+id/tab_a"
        icon="@drawable/ic_a"
        title="Adfds" />

</tabs>

**Comment by MuralikrishnaM** [comment]
You have a problem with the dimensions of your image, You need to reduce the icon sizes, For MDPI it shd be 24 X 24. accordingly you can have the sizes of hdpi, mdpi, ldpi xhdpi .....

**Comment by mlake** [comment]
I'm also seeing this...sometimes it happens, sometimes not..

**Comment by csNewscope** [comment]
I've got also issues with that:
screenshot: http://imgur.com/a/HUvPm

The sizes of my icons are okay. mdpi is 24 x 24px

**Comment by TillSimon** [comment]
Can confirm. Get bottom parts of letters p,y,... cut off (at 60dp height)

**Comment by manhhoangxuan** [comment]
Yep, i am facing this problem too
Any solution right now?

Thanks

**Comment by daveak01** [comment]
Also got the same here, just randomly happened about an hour ago when I was amending the navigation drawer color in my style then it just happened. Will keep an eye out if any one has any solutions. Will continue to troubleshoot.

**Comment by daveak01** [comment]
Might be worth checking this note of the bug guys, seems like a known issue. There is a fix in the thread that worked for me but didn't for others. The bug looks like it's going to be addressed in the next release.

https://github.com/roughike/BottomBar/issues/436

**Comment by zhoujunjiang** [comment]
i have the same problem , sometimes have ,sometimes not

**Comment by xizhang** [comment]
Save here. The issue happens after being redirected from a full screen activity.

**Comment by s-nour** [comment]
same problem, is there anyway I can make the text size smaller?

**Comment by s-nour** [comment]
I have managed to make the textsize smaller by adding a new style resource like so:
    <style name="Text" parent="Theme.AppCompat.Light">
        <item name="android:textSize">12sp</item>
    </style>

Then set this style to your BottomBar's xml: 
    <com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="70dp"
        android:layout_gravity="bottom"
        android:background="#00000000"
        app:bb_activeTabColor="#ffffff"
        app:bb_behavior="shy"
        app:bb_inActiveTabAlpha="0.2"
        app:bb_inActiveTabColor="#000000"
        app:bb_showShadow="false"
        app:bb_tabXmlResource="@xml/bottombar_tabs"
        app:bb_titleTextAppearance="@style/Text" />

**Comment by LOG-TAG** [comment]
Thanks it's solved ! https://github.com/roughike/BottomBar/issues/589

**Comment by Quix0tic** [comment]
I actually found a better solution of reducing text size:
`    <com.roughike.bottombar.BottomBar
... 
app:bb_titleTextAppearance="@style/BB_BottomBarItem_TitleStyle" />`

In `styles.xml` add
`<style name="BB_BottomBarItem_TitleStyle">
        <item name="android:maxLines">1</item>
        <item name="android:height">24dp</item>
        <item name="android:gravity">center_horizontal</item>
    </style>`

**Comment by roughike** [comment]
It's indeed solved in versions 2.1.0 and up.
