### ISSUE TITLE
Dark mode doesn't seem to work

### ISSUE THREAD

**Issue by gowong** [roughike/BottomBar#55]
After enabling dark mode with `useDarkTheme(true)`, the bottom bar looks exactly the same as before. Selecting a tab causes it to disappear (I'm guessing because the text is now white):

![screenshot_20160319-202740](https://cloud.githubusercontent.com/assets/7355980/13902708/560f9834-ee11-11e5-9655-3ab4cd5a7d7f.png)

**Comment by roughike** [comment]
I'm guessing you're calling ```useDarkTheme(true)``` after setting the items?

You must call ```useDarkTheme(true)``` before setting any items for the BottomBar, because the tab colors and backgrounds are determined when setting the items.

**Comment by roughike** [comment]
Just updated the library to version _1.1.2._, setting dark theme now works anywhere.

**Comment by gowong** [comment]
Yep, I was calling it before setting items. New version works perfectly, thanks!

**Comment by roughike** [comment]
Nice!

Thanks for reporting.
