### ISSUE TITLE
How to animate when selecting a tab programmatically?

### ISSUE THREAD

**Issue by geft** [roughike/BottomBar#552]
I found this but it's private.

```
private void selectTabAtPosition(int position, boolean animate) {
        BottomBarTab oldTab = getCurrentTab();
        BottomBarTab newTab = getTabAtPosition(position);

        oldTab.deselect(animate);
        newTab.select(animate);

        updateSelectedTab(position);
        shiftingMagic(oldTab, newTab, animate);
        handleBackgroundColorChange(newTab, false);
    }
```

**Comment by Nolanus** [comment]
Prior to version 2 it was public. @roughike, could you change this to be public again? I don't see any critical part to be done in `selectTabAtPosition(int)` that couldn't be moved to `selectTabAtPosition(int, boolean)` instead.

**Comment by vinkrish** [comment]
Any workaround for selecting tab programmatically?

**Comment by Nolanus** [comment]
You may use the `selectTabAtPosition(int)` to select a tab programmatically, but that will happen without animation. The only way I currently see is calling the private `selectTabAtPosition(int, boolean)` via reflection, although that's not a solution

**Comment by ened** [comment]
```
    private void bottomBarSelect(final BottomBar bottomBar, final int position) {
        try {
            Method selectTabAtPosition = bottomBar.getClass().getDeclaredMethod("selectTabAtPosition", int.class, boolean.class);
            selectTabAtPosition.setAccessible(true);
            selectTabAtPosition.invoke(bottomBar, position, true);
        } catch (NoSuchMethodException | InvocationTargetException | IllegalAccessException e) {
            bottomBar.selectTabAtPosition(position);
        }
    }
```

Probably needs pro guard adjustment.

**Comment by roughike** [comment]
[Possible in the upcoming 2.1.0 version.](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L434)
