### ISSUE TITLE
SelectTabAtLocation block change of current tab

### ISSUE THREAD

**Issue by pospile** [roughike/BottomBar#56]
After calling SelectTabAtLocation I am unable to select card manually. However another SelectTabAtLocation change location normally.

**Comment by roughike** [comment]
Just updated the library to version _1.1.2._, try and see if this works now.

**Comment by pospile** [comment]
Yes, this fixed the issue. Thank you.

**Comment by roughike** [comment]
Awesome. Thank you for reporting!
