### ISSUE TITLE
Add a banner imageview on Bottombar which scrolls along with bottombar

### ISSUE THREAD

**Issue by sathi-007** [roughike/BottomBar#563]
Can you please help me how to add Imageview or any other view of height max 50dp to bottombar, which should scroll along with bottombar. Thanks in advance

**Comment by pollax** [comment]
The BottomBar mimics the behavior of the Material Design bottom navigation. What you are asking is not according to these guidelines so I don't think it will ever be implemented.
See https://material.io/guidelines/components/bottom-navigation.html for reference.

**Comment by roughike** [comment]
Yes, like pollax said, this is out of scope with this library. You'll have to build something custom for that.
