### ISSUE TITLE
Not detecting software navbar on CM11

### ISSUE THREAD

**Issue by se-bastiaan** [roughike/BottomBar#57]
I'm running Cyanogenmod 12 (Android 5.1.1) on my OnePlus One and I when I went for a trial run I noticed that the library always detects the software navbar as being active. It's possible to enable it and use it instead of the hardware buttons on the device, but by default it's not active.

It might be worth noting that I have configured my hardware menu button as recent apps but as far as I've noticed no changes when I configure it as menu button.

[screenshot_2016-03-20-15-51-48](https://cloud.githubusercontent.com/assets/1799914/13905036/60b870c8-eeb4-11e5-81bd-6befea5651f7.png)
[screenshot_2016-03-20-15-52-00](https://cloud.githubusercontent.com/assets/1799914/13905037/61a7d474-eeb4-11e5-94f2-a407fe6a4fb3.png)

**Comment by se-bastiaan** [comment]
The `softMenuIdentifier` in `navBarMagic` is non-zero and `res.getBoolean(softMenuIdentifier)` returns false so I guess it must be `hasPermanentMenuKey`

**Comment by se-bastiaan** [comment]
`KeyCharacterMap.deviceHasKey(KeyEvent.KEYCODE_BACK)` returns true. So it might work in combination with `hasPermanentMenuKey`, but the issue I found (below) says that this method isn't really reliable as well.

http://stackoverflow.com/questions/14853039/how-to-tell-whether-an-android-device-has-hard-keys/14871974#14871974

**Comment by roughike** [comment]
What about:

```java
int navBarIdentifier = res.getIdentifier("navigation_bar_height",
                "dimen", "android");
int navBarHeight = navBarIdentifier > 0? res.getDimensionPixelSize(navBarIdentifier) : 0;
```

Can you test what is the navBarHeight after running that code?

**Comment by se-bastiaan** [comment]
`navBarHeight` is 144 (48dp). Thus the resource does exist.

The `hasSoftKeys` from the StackOverflow issue seems to works fine. But I might be a bit hacky to just measure the window.

**Comment by roughike** [comment]
I'll test that code from StackOverflow and if it's good, I'll implement that. If we need to use hacky solutions to work, then so be it.

Thanks for reporting the issue!

**Comment by roughike** [comment]
Just updated the library to version _1.1.2._, try and see if this works now.

**Comment by se-bastiaan** [comment]
I pulled the source to test the sample app. I don't see any other source changes since I did that and the README changes?

**Comment by roughike** [comment]
It should be there now.

**Comment by se-bastiaan** [comment]
Works!

**Comment by roughike** [comment]
Awesome!

Huge thanks for reporting, helping and testing!
