### ISSUE TITLE
Have object aligned above bottombar while hiding shy

### ISSUE THREAD

**Issue by cmendes0101** [roughike/BottomBar#573]
I'm trying to keep an ad above the bottombar but since its in a coordinatedlayout I can't position it above that widget. I could add bottom margin that matches bottombar height but I'm using shy so it hides.

Anyone have suggestions? Was thinking maybe have callback when shy is happening and adjust the ads bottom margin as a hack

**Comment by r91andersson** [comment]
I faced the same problems before. But I solved it as you say by having a framelayout positioned above the bottombar and removed the "shy" option so it stayed static.

**Comment by archifishaldev** [comment]
I did something like this (in the Fragment that I wanted attached to the bottom bar):

    class BottomNavigationBehavior<V extends View> extends CoordinatorLayout.Behavior<V> {
        @Override
        public boolean layoutDependsOn(CoordinatorLayout parent, V child, View dependency) {
            return dependency.equals(mAttachedView);
        }

        public boolean onDependentViewChanged(CoordinatorLayout parent, V child, View dependency) {
            if (dependency.equals(mAttachedView)) {
                mAttachedViewY = dependency.getY();

                int newY = getWantedY();

                child.setTranslationY(newY);

                return true;
            }
            return false;
        }
    }

    public void setAttachedView(View attachedView) {
        this.mAttachedView = attachedView;

        final View view = getView();
        if (view != null) {
            CoordinatorLayout.LayoutParams params = (CoordinatorLayout.LayoutParams) view.getLayoutParams();
            params.setBehavior(new BottomNavigationBehavior());
        }
    }

    private int getWantedY() {
        int toolbarHeight = mToolbar.getHeight(); // or whatever you need it to do

        return (int) (mAttachedViewY - toolbarHeight);
    }

Where mAttachedView is the bottom bar that your view is attached to, and getWantedY() works out the correct translation based on mAttachedViewY and the height of your attached view.

May not entirely fit your scenario, but hopefully the above will give you some idea how to do it.

**Comment by cmendes0101** [comment]
Thanks, that looks like a good way. I ended up doing it a slightly different way:

`recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);

                if (dy > 0) {
                    view.setPadding(0, 0, 0, 0);
                } else {
                    view.setPadding(0, 0, 0, Utilities.convertDPtoPX(getContext(), 60));
                }
            }
        });`

It just pads the recyclerview when at the top of the list. It ends up I'm going to move locations so won't need to stay on top of the bottombar anymore but wanted to paste here incase anyone else finds it useful.

Thanks!
