### ISSUE TITLE
Select tab without actually doing something

### ISSUE THREAD

**Issue by foxapp** [roughike/BottomBar#574]

**Comment by pamgoudarzi** [comment]
Easy Peasy! Simply use setSelection(int) before setting the click listeners on BottomBar.

**Comment by foxapp** [comment]
Hello, BottomBar have only bottomBar.setSelected(true/false), but not have setSelection() method call;

**Comment by pamgoudarzi** [comment]
Sorry! I actually meant selectTabAtPosition(int, boolean)

**Comment by foxapp** [comment]
Ok, but how to stop to be selected tab on start?

**Comment by pamgoudarzi** [comment]
As far as I know, if you don't use selectTabAtPosition(int, boolean) the BottomBar lib will automatically select the index 0.

**Comment by foxapp** [comment]
yes, but i not want to be selected nothing, because i want to initiate select after first click

**Comment by foxapp** [comment]
selectTabAtPosition(int, boolean) boolean is in private i not have posibility to use it only selectTabAtPosition(int), why?

**Comment by roughike** [comment]
Now possible with TabSelectionInterceptor.
