### ISSUE TITLE
Tabbar icon state not changed.

### ISSUE THREAD

**Issue by Slybars** [roughike/BottomBar#579]
BottomBarTab iconView state not changed. Could you set selected for iconViews on select and deselect functions. So we can use a selector drawable for icon.

 void select(boolean animate) {
        isActive = true;
        iconView.setSelected(true);
...
}

 void deselect(boolean animate) {
        isActive = false;
        iconView.setSelected(false);
...
}

**Comment by yombunker** [comment]
this is currently in PR

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
