### ISSUE TITLE
Set barColorWhenSelected programmatically

### ISSUE THREAD

**Issue by vojta-horanek** [roughike/BottomBar#583]
There seems to be no way to select the bar color programmatically.

**Comment by yhaznedar** [comment]
mBottomBar.setActiveTabColor(R.color.yourColor);

You can change like that.

**Comment by vojta-horanek** [comment]
Nope, i need to change it every now and then (every time a webpage is loaded), so it needs to be programmatically.

**Comment by yhaznedar** [comment]
Yes, you are right! I opened issue for that. But I just suggested you temporary solution.

**Comment by roughike** [comment]
Possible in the upcoming 2.1.0.
