### ISSUE TITLE
barColorWhenSelected not work!

### ISSUE THREAD

**Issue by iman2420** [roughike/BottomBar#591]
I use barColorWhenSelected but no change background color of BottomBar!
i use this lib in an fragment : 

        `<com.roughike.bottombar.BottomBar 
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        style="@style/BB_BottomBarItem_TitleStyle"
        android:layout_height="60dp"
        app:bb_behavior="shifting"
        android:layout_alignParentBottom="true"
        app:bb_tabXmlResource="@xml/bottombar_tabs"
        app:bb_inActiveTabAlpha="0.5"
        app:bb_showShadow="true"
        />` 
And this is my `bottombar_tabs.xml`

     `<tabs>
    <tab
        id="@+id/tab_paused"
        icon="@drawable/ic_play_circle"
        barColorWhenSelected="#00FF00"
        activeColor="#00FF00"
        title="در حال اجرا" />
    <tab
        id="@+id/tab_opened"
        icon="@drawable/ic_pause_circle"
        barColorWhenSelected="#FFFF00"
        activeColor="#FFFF00"
        title="در حال تکمیل" />
    <tab
        id="@+id/tab_finished"
        icon="@drawable/ic_stop"
        barColorWhenSelected="#FF0000"
        activeColor="#FF0000"
        title="خاتمه یافته" />
    <tab
        id="@+id/tab_free_level"
        icon="@drawable/ic_money_off"
        barColorWhenSelected="#0000FF"
        activeColor="#0000FF"
        title="مرحله رایگان" />
       </tabs>`
it's background fixed at first item in bottombar_tabs.xml and no change.
any idea?

**Comment by iman2420** [comment]
I found my problem finally:
i use ` bottomBar.setTabTitleTypeface(KoodakFont);` 
after i remove this line every thing work as well.

**Comment by roughike** [comment]
There was a really major fuckup in the logic that updated tab properties when setting attributes programmatically. It basically caused all the attributes reset to default values.

Fixed in [this commit](https://github.com/roughike/BottomBar/commit/d67928c8f5e5092e0d691520c5313ce3a4cdd2f8).
