### ISSUE TITLE
Bottombar cut when  typing in edittext keyboard pop up 

### ISSUE THREAD

**Issue by indiascope** [roughike/BottomBar#592]
Hi,

In normal situation tab is working fine. but when i typing in edittext keyboard popup, at this time bottom bar cut. after typing complete and when we hide keyboard tab is not goes to normal state.tab is cut in all complete app.

Please find below attach image.

1. 1st image  When No keyboard open tab bar is working fine.
2. 2nd image when keyboard open we start typing in edittext tab is cut.
3. 3rd image after hide keyboard tab not goes to normal condition.

![device-2016-12-01-102909](https://cloud.githubusercontent.com/assets/3463588/20782593/38815ad4-b7b3-11e6-888e-80ab1baff591.png)
![device-2016-12-01-104113](https://cloud.githubusercontent.com/assets/3463588/20782594/38896b20-b7b3-11e6-9b01-355adc3f728a.png)
![device-2016-12-01-104133](https://cloud.githubusercontent.com/assets/3463588/20782595/38899988-b7b3-11e6-8128-2a468e9f52cf.png)

**Comment by honjiaxuan** [comment]
same problem here

**Comment by Anupriya25** [comment]
same problem

**Comment by zhzhh7378** [comment]
same problem

**Comment by riadhnet** [comment]
same problem here

**Comment by thespianartist** [comment]
Same issue here, but only by using emulator.

**Comment by pmb516** [comment]
Also got this

**Comment by vinothvino42** [comment]
Even I'm also having this problem

**Comment by vinothvino42** [comment]
Adding this `android:windowSoftInputMode="adjustPan"` into Activity solves my problem.

**Comment by indiascope** [comment]
Thanks vinothvino42. It's working.

**Comment by Leevey** [comment]
Thanks vinothvino42. It's working.
