### ISSUE TITLE
Badge title string value

### ISSUE THREAD

**Issue by Lintom** [roughike/BottomBar#596]
Hi. How to set string value in badge title? For example, if the data loading error, show symbol `!` .

**Comment by pollax** [comment]
You can't.
See here: https://github.com/roughike/BottomBar/blob/3cea29136a246d94465e4eab88e0a0247f30f692/bottom-bar/src/main/java/com/roughike/bottombar/BottomBarBadge.java#L47

I don't think it's a great UX to show anything else but a count in a badge. But if you still want to, it's not too hard to make a fork and build support for it.

**Comment by roughike** [comment]
There's something like this already coming in the upcoming version, and since there's a lot of these issues open, I'll close this one.
