### ISSUE TITLE
bottomBar.selectTabAtPosition not working the first time

### ISSUE THREAD

**Issue by LaurentTreguier** [roughike/BottomBar#60]

**Comment by roughike** [comment]
The listener won't tell you any changes to tab selection the first time. So you could remove the both ```selectTabAtPosition()``` methods you're currently using, and do something like this the first time:

```java
if (savedInstanceState == null) {
    // show fragment number 0 the first time
}
```

**Comment by LaurentTreguier** [comment]
Ok. I just found it weird because it was working fine with version 1.0.8 and couldn't see why it stopped afterwards...

**Comment by roughike** [comment]
I'm sorry for that.

I'll also look into this later and see if there's something I could be doing better.

Thanks for reporting.
