### ISSUE TITLE
Generated tab ids are all set to 1 when running robolectric tests

### ISSUE THREAD

**Issue by nico-gonzalez** [roughike/BottomBar#602]
I am not sure why this is happening, but seems the generated ids for the tabs when running robolectric unit tests are all set to 1, which causes an issue when trying to programmatically interact with the bottombar tabs by id.

This is how my tabs.xml resource file looks like

`<tabs>

    <tab
        id="@+id/bottombar_place"
        icon="@drawable/ic_place"
        title="@string/place" />

    <tab
        id="@+id/bottombar_report"
        icon="@drawable/ic_reporter"
        title="@string/report" />

    <tab
        id="@+id/bottombar_profile"
        icon="@drawable/ic_profile"
        title="@string/profile" />
</tabs>`

and this is how I'm referencing the xml on the layout 
`<com.roughike.bottombar.BottomBar
            android:id="@+id/bottomBar"
            android:layout_width="match_parent"
            android:layout_height="@dimen/bottombar_height"
            app:bb_tabXmlResource="@xml/bottombar_tabs"
            />
`

Any ideas?

**Comment by ShaoYuanCodes** [comment]
i'm having this issue as well!

my XML File:

'<?xml version="1.0" encoding="utf-8"?>
<tabs xmlns:android="http://schemas.android.com/apk/res/android">

    <tab android:id="@+id/tab_graph"
        android:icon="@drawable/ic_graph">
    </tab>

    <tab android:id="@+id/tab_map"
        android:icon="@drawable/ic_place">
    </tab>

    <tab android:id="@+id/tab_notification"
        android:icon="@drawable/ic_notification">
    </tab>
</tabs>`

and how i;m referencing it in activity_main.xml:

'    <com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_alignParentBottom="true"
        android:layout_gravity="bottom"
        app:bb_inActiveTabAlpha="0.6"
        app:bb_activeTabAlpha="1"
        app:bb_inActiveTabColor="#2196F3"
        app:bb_activeTabColor="#2196F3"
        app:bb_tabXmlResource="@xml/bottombar_tabs" />
'

please help!!!

**Comment by Qubed3** [comment]
I had a similar issue. Turns out the problem was the fact I had the 'Android:' prefix before the Attributes.
So instead of 'Android:id' try simply 'id'
It should solve ShaoYuanCodes's problem not sure about nico-gonzalez.

**Comment by yombunker** [comment]
@nico-gonzalez can you tell us more about your problem? does it still repro on the latest version? feel free to re-open once you add more info and the issue is still relevant.
