### ISSUE TITLE
Different icon for selected tab

### ISSUE THREAD

**Issue by tfsjohan** [roughike/BottomBar#603]
It would be useful to be able to have two icons in the <tab> xml. One when the tab is selected and one when it is inactive. This is how the UITabBar works on iOS and it's quite nice to have a filled icon when selected and more of an outline when it's not.

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
