### ISSUE TITLE
Steady bottombar between activities?

### ISSUE THREAD

**Issue by xtien** [roughike/BottomBar#613]
This is a question, more than an issue.
When I have multiple activities using the same bottom bar layout, how do I prevent a flicker of the bottom bar when starting a new activity? I mean, what do most people do? 
I can use fragments so I can have one activity in my app, I can have just one activity period, or I can have a fragment that displays the bottombar that's shared between activities. None of these solutions sound appealing to me. So I'm wondering, what do you guys do?

**Comment by roughike** [comment]
You would have only one Activity that hosts the BottomBar. The activity then switches between different Fragments depending on the selected tab.
