### ISSUE TITLE
Not able to enter a String value in the badge

### ISSUE THREAD

**Issue by rajas47** [roughike/BottomBar#617]
Hello,
I do not want to display the count of the data in the badge but just want to notify user about new data available in the tab, however, with the current methods i can only display the count.

Could you please add the support for entering a String argument to the setBadgeCount method?
Something where like displaying "*" for the new content instead of number

**Comment by Cybrosys** [comment]
I second this.

**Comment by rajas47** [comment]
@Cybrosys 
How do i access the Badge?
I cannot create an object of it......if you do not mind, could show me a sample code.
Thanks in advance. :)

**Comment by Cybrosys** [comment]
@rajas47 
Can't. I'm using an older version of the BottomBar where you manually create the badge with a call. Apparently that's done for you in the latest version? My suggestion would be to downgrade to a earlier version or check the source code for a possible solution.

**Comment by rajas47** [comment]
Ok.
Thank you.
I have currently made work around for it.
I appreciate your help.

**Comment by satti8893** [comment]
@rajas47 Im also having the same issue. Can u help me with the workaround?

**Comment by roughike** [comment]
See #98.

**Comment by rajas47** [comment]
Well #98 says BottomBarBadge no such class is available in the current version of the library, nor can i extend BottomBarBadge
