### ISSUE TITLE
How to reduce method count?

### ISSUE THREAD

**Issue by Ankur008** [roughike/BottomBar#618]
I check the method count for this library is approx 20K using http://www.methodscount.com/

Is there any way so that i can reduce the method count. 

And out of Library dependency list, below libraries other version(i.e.25.1.0) I am using as part of the project.Is there any way so that these library will not add again as a duplicate. 

com.android.support:appcompat-v7:23.3.0
com.android.support:design:23.3.0
com.android.support:recyclerview-v7:23.3.0

**Comment by leonardo2204** [comment]
You can always use Proguard for that matter !

**Comment by Ankur008** [comment]
I have used the Proguard but nothing helps

**Comment by roughike** [comment]
To my understanding, in the case of duplicate dependencies, Gradle will pick the most recent version and include it only once. ProGuard will then strip the code you don't use from your release APK. So this shouldn't be a problem.

Somebody correct me if I'm wrong.
