### ISSUE TITLE
Change tabs with setItem() is broken 

### ISSUE THREAD

**Issue by Singwai** [roughike/BottomBar#619]
When I try to call the method bottomBar.setItem() to reload the tabs, it will not remove the old tabs before inserting the new tabs.

https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L225-L244

I think some where there should add `tabContainer.removeviews();` but the spacing will be broken. when I tried it.

**Comment by Singwai** [comment]
Got it working now.
see this pr https://github.com/roughike/BottomBar/pull/620

**Comment by roughike** [comment]
Copy-pasting the same comment I made on the PR:

In the upcoming version, this is already fixed as the ```updateItems()``` method always removes the old items before doing anything else.

See [here](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L260)
