### ISSUE TITLE
[Question] Is it possible to have fixed size items with 5 badges?

### ISSUE THREAD

**Issue by Dimezis** [roughike/BottomBar#621]
Hi, can you please tell me if it's possible to avoid scaling, shifting and title hiding on item select if there's more than 3 badges? 

So basically I want to have the same behavior as 3 items bar has.

I know that default behavior is following the guidelines, but it's ugly and inconvenient for user in my opinion.

Thank you.

**Comment by roughike** [comment]
Yes.

The newest versions of the library don't force you to user the shifting tabs mode if there's more than three tabs. In fact, it doesn't do that on default either, meaning that you must explicitly say that you want the tabs to shift.
