### ISSUE TITLE
Navigation have a white area

### ISSUE THREAD

**Issue by YangPeiru** [roughike/BottomBar#622]
![8](https://cloud.githubusercontent.com/assets/15328091/21915817/5351dfd8-d977-11e6-8216-1f8fec08a0d3.jpg)
like this,I put the recyclerView background is set to dark green,I don't know what causes.Your demo is also the same.

**Comment by alexakasanjeev** [comment]
I am having the same problem

**Comment by roughike** [comment]
@YangPeiru I can't replicate the problem with the latest demo. This is probably with the version 2.0.2, and fixed in the upcoming newest version.

**Comment by YangPeiru** [comment]
@alexakasanjeev In fact I don't want to make recycler dark_green, just to test out a piece of white area.

**Comment by YangPeiru** [comment]
@roughike 
![image](https://cloud.githubusercontent.com/assets/15328091/21962140/44f03a32-db59-11e6-9559-82d14786759f.png)
![image](https://cloud.githubusercontent.com/assets/15328091/21962146/5ed09406-db59-11e6-9d19-d28d4280917a.png)
In your latest demo,I set a different background  to the RelativeLayout and TextView,you can try,TextView and BottomBar like setting the margin?

**Comment by roughike** [comment]
Yes, that's the shadow. I meant that I've not been able to get such tall gap as in your first screenshot.

To get rid of the shadow, use ```bb_showShadow="false"```, as [described in the README.](https://github.com/roughike/BottomBar#all-customization-options)

**Comment by YangPeiru** [comment]
The first screenshot is my fault,has now been repaired.I use `bb_showShadow="false"` but there are still a white area.
Thank you for your reply to my question every time!

**Comment by YangPeiru** [comment]
Thank you for your answer, use ` bb_showShadow="false"` can solve my problem.
