### ISSUE TITLE
tab title

### ISSUE THREAD

**Issue by alirezanazari** [roughike/BottomBar#623]
how can i show tab title ?
i write your code but i don't see title under of icon.

how can i do it?

**Comment by alexakasanjeev** [comment]
If you want to show title of the active tab only, add this property in your xml layout in  `BottomBar` tag

`app:bb_behavior="shifting"`

**Comment by mazhewei** [comment]
i met the same problem. whatever i set the property of "bb behavior",it doesn't work.i just saw the icons but no titles.version is 2.1.1.maybe, i use the wrong theme or style? 
compileSdkVersion is 25.
buildToolsVersion is 25.0.2. 
minSdkVersion is 14. 
what can i do to show the titles?
thx.

**Comment by mazhewei** [comment]
Sorry, I did not see the instructions.
The problem has been solved.
The icon resource is incorrect.
Use the standard icons provided by https://romannurik.github.io/AndroidAssetStudio/icons-generic.html to display the title properly.
Remember,
The size is 24dp.
The padding is 0dp.
(I'm sorry for my bad English, so this time I'm using Google Translate instead)
