### ISSUE TITLE
Avoid bar being cut at edges

### ISSUE THREAD

**Issue by valenji** [roughike/BottomBar#625]
Hi, I would like to avoid the bottombar to be cut at the left and right edges. I mean to keep every icon completely inside of the screen.
Is it possible? How can be done?
Thanks in advance and sorry for my english.

![image](https://cloud.githubusercontent.com/assets/17174870/21989778/7e077ade-dc0c-11e6-8f7b-d019f684551f.png)

**Comment by roughike** [comment]
How many icons you have, on which device?

I was able to fit 8 items / tabs without any clipping on a Nexus S portrait screen, so I'm not sure how to replicate your problem.

**Comment by roughike** [comment]
If you have some sample code that could replicate your issue, that would help a lot.

**Comment by valenji** [comment]
I have 5 items placed. Now I've tried on a different phone, and it's working fine. This working device is running Android 6.0 (Sony Z3Compact), the other one Android 5.1 (Huawei G8).
I've noticed that it happens with 4 items or more and it also occur with your bottombar application sample: 
![image](https://cloud.githubusercontent.com/assets/17174870/21991324/68d94286-dc12-11e6-9326-2df5f8d31087.png)

**Comment by roughike** [comment]
Must be related to a recent change that changed the tab width calculation reference from screen width to the BottomBar width.

Still can't replicate since I don't have Huawei G8. There must be some device-specific quirk there. I modified the logic just now to have the reference width to be at most the screen width.

Could you test with the newest source for the sample if that fixed it?

**Comment by valenji** [comment]
Now it's working perfect! I tried with another device; Samsung Core Prime with Android 5.1.1 and I had the same issue, but as I said now it's working good on both devices.
Wow, thank you very much for answering this fast. You are awesome dude!!

**Comment by roughike** [comment]
Nice! Glad I could help.

This really isn't the norm by the way, I just had a good hunch ;)

**Comment by roughike** [comment]
I made a completely new release just for this, since it's a pretty major issue for affected devices.

Thanks for reporting this!

**Comment by avivcaspi** [comment]
Had the same problem with my old phone
but now it working fine so I guess what you did fixed it , thank you !
