### ISSUE TITLE
Using 2.1.1 I get a compile error regarding theme

### ISSUE THREAD

**Issue by BlaineOmega** [roughike/BottomBar#631]
When using 2.1.1 I go to build the application and I get a compilation error that looks like this:

<img width="1243" alt="bottombarerror" src="https://cloud.githubusercontent.com/assets/4164126/22178896/aabe6f3e-dff8-11e6-9489-3a686850dec3.png">

If I use version 1.2.1, I don't get the error, and I'm not sure how to fix this. Is this a bug with the project, or am I doing something wrong?

**Comment by s1559168** [comment]
I have the exact same issue. Version 2.0.2 still builds, but when upgrading to version 2.1.0 (or 2.1.1) I also get this problem.

On several platforms I read that it had to do with the buildToolsVersion and TargetSdkVersion of your app build.gradle not matching the versions of your com.android.support libraries. But I was not able to resolve the issue, using the following settings:

compileSdkVersion 23
buildToolsVersion "23.0.3"
minSdkVersion 15
targetSdkVersion 23

compile 'com.android.support:appcompat-v7:23.0.3'
compile 'com.android.support:design:23.0.3'

**Comment by avivcaspi** [comment]
I had the same problem
resolve it by using this in the gradle file

compileSdkVersion 25
buildToolsVersion "25.0.1"
targetSdkVersion 25
compile 'com.android.support:appcompat-v7:25.1.0'
compile 'com.android.support:support-v4:25.1.0'

**Comment by roughike** [comment]
The error can be indeed fixed by the solutions above.
