### ISSUE TITLE
Adding a ImageView on top of BottomBar

### ISSUE THREAD

**Issue by binatra** [roughike/BottomBar#640]
Can i add an imageview or buttonview on top of bottombar so it can look pretty much like this in picture?
![imgview](https://cloud.githubusercontent.com/assets/10198115/22465647/fbe478b0-e7bc-11e6-848b-0507f40daf50.PNG)

**Comment by pollax** [comment]
BottomBar is intended to follow the Material Design guidelines for a bottom navigation. What you are asking for is not according to the guidelines, so I assume that the answer is no at this time.

**Comment by roughike** [comment]
There's no plans for that. You could hack your way through having the BottomBar inside a Framelayout, that image button on top of that and five menu items, the middle one having empty title and empty image.
