### ISSUE TITLE
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

### ISSUE THREAD

**Issue by shemnduati** [roughike/BottomBar#645]

**Comment by grabblesaur** [comment]
I have faced with the same problem: in build.gradle file my compileSdkVersion and targetSdkVersion was 23. And error was about missing resources like Materials.Widget.Button for version 24. So i just upgrade my compileSdkVersion and targetSdkVersion to 25. Hope it helps

**Comment by roughike** [comment]
Try what grabblesaur suggests, as I was able to reproduce and fix this that way. Shout out and I'll reopen if this doesn't fix the issue.
