### ISSUE TITLE
Programatically Change Icon

### ISSUE THREAD

**Issue by MattJakeman** [roughike/BottomBar#649]
Hi,

Thanks for the library. Very nifty.

Is there any way to change the icon programatically? When a user clicks on a tab, I'd like to be able to switch the icon out but can't find anything in the docs about it.

Cheers

**Comment by Gagege** [comment]
There isn't a way to do that with this library. [But you can change it manually.](https://github.com/roughike/BottomBar/issues/615)

**Comment by MattJakeman** [comment]
Thanks for the reply. That should do the trick.

**Comment by roughike** [comment]
It's now possible with version **2.2.0** and up, [see the README](https://github.com/roughike/BottomBar#changing-icons-based-on-selection-state).
