### ISSUE TITLE
BottomBar.attach() not resolved.

### ISSUE THREAD

**Issue by phanuelayuka** [roughike/BottomBar#650]
the code below gives me an error......attach() not resolved.
`bottomBar = BottomBar.attach(this, savedInstanceState);`

which function should i use instead. Kindly help.

**Comment by Binzzzz** [comment]
2nd version is having problems with attach . use the version 1.3.9 instead to access this function. Looking for implementation for the same in 2nd version .

**Comment by phanuelayuka** [comment]
Thanks for your response Binzzzz....I highly appreciate.

**Comment by ozencelik** [comment]
Thanks a lot Binzzzz

**Comment by christiankriz** [comment]
this really helped me as well, thanks Binzzzzz
