### ISSUE TITLE
Lots of white space?

### ISSUE THREAD

**Issue by mailhotz** [roughike/BottomBar#657]
It appears that the bottombar doesn't go all the way to either the left or right edge. And also is hovering a bit above the bottom of the screen display. I have my width as "match_parent" but am unsure if there is something else I need to add to fill in this space or if this is some kind of bug? Any help is appreciated
![screenshot_20170219-175052](https://cloud.githubusercontent.com/assets/5949142/23107505/5222dfb4-f6cc-11e6-891e-380de4eaf23d.png)

**Comment by alouanemed** [comment]
Chech if the parent of bottomview have no padding

**Comment by roughike** [comment]
This definitely looks like your parent view has the default 16dp of padding.
