### ISSUE TITLE
How to prammatically select the bottom bar or TAB

### ISSUE THREAD

**Issue by maheswaranecemohan** [roughike/BottomBar#658]
How to prammatically select the bottom bar or TAB

**Comment by ChaosLeong** [comment]
The following method may help you.

* [selectTabWithId(@IdRes int tabResId)](https://github.com/roughike/BottomBar/blob/338ee864392087f0233ef42765730e00810cd020/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L414)
* [selectTabAtPosition(int position)](https://github.com/roughike/BottomBar/blob/338ee864392087f0233ef42765730e00810cd020/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L424)
* [selectTabAtPosition(int position, boolean animate)](https://github.com/roughike/BottomBar/blob/338ee864392087f0233ef42765730e00810cd020/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L434)
