### ISSUE TITLE
Hope to ability to add badge to bottom bar item

### ISSUE THREAD

**Issue by LiuDeng** [roughike/BottomBar#66]
Hope to ability to add badge to bottom bar item
Thank you very much~
Best Wishes~

**Comment by roughike** [comment]
Badge? Do you mean like an indicator for unread / new content?

If so, that would probably be useful and it's a great idea!

**Comment by LiuDeng** [comment]
@roughike  yes that is~Thank you~ it must likely a red circle with unread/new content number
 http://ww3.sinaimg.cn/bmiddle/005TCWe5jw1f260zir1wvj30fj02gaa6.jpg

**Comment by roughike** [comment]
It's now possible in the version _1.1.8._

[Here's instructions how to do it.](https://github.com/roughike/BottomBar#badges)

**Comment by LiuDeng** [comment]
@roughike  you are amazing

**Comment by roughike** [comment]
https://s-media-cache-ak0.pinimg.com/736x/82/ce/c3/82cec312acd302e15262a99d1b81bfd0.jpg
