### ISSUE TITLE
Colored Single tab Item

### ISSUE THREAD

**Issue by dalwadi2** [roughike/BottomBar#660]
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/16306370/23199586/3a97cce4-f8f5-11e6-92d8-194302f84b96.png)

Can I make selector like this (with colored single tab item)? 
please let me know if anything you have that'll help me 
thanks.

**Comment by ChaosLeong** [comment]
HI @dalwadi2 , you can do it in the tabs.xml by adding this property to the relevant tab item.

`activeColor="@android:color/black"`

The following are all properties of the `<Tab />`.

``` xml
<tab
    id="@+id/nav_home"
    icon="@drawable/ic_home_black_24dp"
    title="@string/nav_home"
    activeColor="@android:color/black"
    inActiveColor="@android:color/white"
    barColorWhenSelected="@color/colorPrimaryDark"
    badgeBackgroundColor="@color/red_dark" />
```

You can also get all properties by reading [the source code](https://github.com/roughike/BottomBar/blob/338ee864392087f0233ef42765730e00810cd020/bottom-bar/src/main/java/com/roughike/bottombar/TabParser.java#L61). : )

**Comment by dalwadi2** [comment]
sure thanks.
