### ISSUE TITLE
onSaveInstanceState changed?

### ISSUE THREAD

**Issue by zhangzhzh** [roughike/BottomBar#661]
With version 1.3.9, in MainActivity, the code is right:
```
@Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        HDApplication.bottomBar.onSaveInstanceState(outState);
    }
```

but change to version 2.1.1, there is an error, as the screenshot below:
<img width="585" alt="2017-02-23 00 18 06" src="https://cloud.githubusercontent.com/assets/1575989/23220853/39bf2ccc-f95e-11e6-80f9-ade2df2486de.png">

**Comment by ChaosLeong** [comment]
@zhangzhzh Does not need to be invoked `onSaveInstanceState` manually in version 2.x. You can remove it.

**Comment by zhangzhzh** [comment]
@ChaosLeong  I guess and do it, and just want to confirm it. thx

**Comment by roughike** [comment]
Yep, the README & the sample app both have instructions to how set it up. It doesn't require that onSaveInstanceState call anymore.
