### ISSUE TITLE
bottombar is covered by nav 

### ISSUE THREAD

**Issue by fightWithFate** [roughike/BottomBar#662]
bottombar is covered by nav

**Comment by fightWithFate** [comment]
I have solved it， thanks，谢谢

**Comment by zhaoyouzhi** [comment]
how to do？

**Comment by Thuantanon** [comment]
There is a attr called bb_behavior,  you can try

**Comment by zhaoyouzhi** [comment]
There be a problem with the method I used, I tried bb_behavior four attributes, have not succeeded, but still thank you.
