### ISSUE TITLE
Programmatically set behaviors

### ISSUE THREAD

**Issue by codedphoenix** [roughike/BottomBar#666]
i have tried to set the behaviors manually without using xml all to no avail

**Comment by ChaosLeong** [comment]
@codedphoenix 

The 'behaviors' are only assigned at [BottomBar.java#L138](https://github.com/roughike/BottomBar/blob/master/bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java#L138). That means you can not set the 'behaviors' without using xml.

**Comment by codedphoenix** [comment]
Thanks but, would that feature be available in a later version?

**Comment by ChaosLeong** [comment]
I don't know, @roughike can this become a new feature?

**Comment by codedphoenix** [comment]
Thanks
