### ISSUE TITLE
Map fragment always reloads when changed item

### ISSUE THREAD

**Issue by viettanbkdn** [roughike/BottomBar#67]
i have created a fragment that contains a map like this:

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <fragment
    android:id="@+id/map"
    android:name="com.google.android.gms.maps.SupportMapFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

</LinearLayout>
```

```
@Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        SupportMapFragment mapFragment = (SupportMapFragment) this.getChildFragmentManager().findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);
    }
```

And everytime i change item, map reload, how can i keep state of fragment.

**Comment by roughike** [comment]
I guess you're using the ```setFragmentItems()``` method. The fragments are always replaced when the tabs are changed, so yes, they're reloaded every time.

If you want the Fragments to hold their state as long as possible, use ```setItems()``` instead of ```setFragmentItems()``` and do your custom implementation with a _ViewPager_ yourself.

**Comment by NickM-27** [comment]
You could also try doing something with a saved instance state to keep it loaded

**Comment by roughike** [comment]
I'm closing this issue, as the setFragmentItems() method is now deprecated. You should be handling your Fragments by yourself.

**Comment by meNESS** [comment]
@viettanbkdn This issue is not related to BottomBar. You have to set `pager.setOffscreenPageLimit(mAdapter.getCount() - 1)` to prevent from recreating fragments by `ViewPager`.
