### ISSUE TITLE
Where can I set setAutoHideOnSelection()?

### ISSUE THREAD

**Issue by jaybuangan** [roughike/BottomBar#672]
I'm trying to prevent the badge from disappearing when selecting a tab with a badge on it.  I know this method exists but I'm not sure how to get a BottomBarBadge from the tab.

**Comment by ChaosLeong** [comment]
Which version of the BottomBar library you are using?

**Comment by jaybuangan** [comment]
the latest i believe 2.1.1

**Comment by ChaosLeong** [comment]
It seems that the `setAutoHideOnSelection` method has been removed from the version `1.4.0.1`.

https://github.com/roughike/BottomBar/commit/6f6a8b32598707aa08c5c29d456548d569cf329b#diff-9be5585e6104867e909c752ab5ca6d21L69

**Comment by roughike** [comment]
This is available again with the version 2.1.2. See the README for instructions.
