### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by bigzhulove** [roughike/BottomBar#676]
![20170306150741](https://cloud.githubusercontent.com/assets/20509302/23599935/f0dc07a8-027e-11e7-9fa3-05ba14c3c8ed.png)
how to eliminate the white line

**Comment by ChaosLeong** [comment]
add this line

``` xml
app:bb_showShadow="false"
```

另外建议你将标题改为 "How to hide the top shadow of BottomBar？"，"Help me" 之类一般没人理你的

**Comment by bigzhulove** [comment]
灰常感谢

**Comment by yombunker** [comment]
The code is in, going out on next release
