### ISSUE TITLE
some advices for Badges

### ISSUE THREAD

**Issue by jason8232590** [roughike/BottomBar#687]
As we all know, we can easily add badges for showing an unread message count or new items / whatever you like. But if the amount of the unread message  above 99 ,we'd better show “99+” instead of showing the real amount , because  there is no enough room to show that  . So the question is now  we can only set a int value rather than a String by setBadgeCount.

**Comment by roughike** [comment]
This is loosely related to #98. There's going to be changes for Badges that allow customization soon.
