### ISSUE TITLE
How to move FAB down when bottom bar is shy?

### ISSUE THREAD

**Issue by louistsaitszho** [roughike/BottomBar#688]
How to move FAB down when bottom bar is shy (and push it back up when it is not shy)?

**Comment by ovitrif** [comment]
+1

**Comment by forcehandler** [comment]
+1

**Comment by yombunker** [comment]
have you guys follow the read me instruction and look at the example in the sample app? just so that i know where to start.

**Comment by gsora** [comment]
I'm in the same situation, where the FAB just sits under the BottomBar.

I've built and tried the sample app but there's no FAB usage in there

**Comment by gsora** [comment]
Ok so, after a little bit of "advanced" tinkering, I've got it working with this custom Behavior:

```java
public class FABBehavior extends CoordinatorLayout.Behavior<FloatingActionButton> {

    public FABBehavior(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean layoutDependsOn(CoordinatorLayout parent, FloatingActionButton child, View dependency) {
        return dependency instanceof BottomBar;
    }

    @Override
    public boolean onDependentViewChanged(CoordinatorLayout parent, FloatingActionButton child, View dependency) {
        float translationY = Math.min(0, dependency.getTranslationY() - dependency.getHeight());
        child.setTranslationY(translationY);
        return true;
    }
}
```

Then in your FAB XML, declare it:

```xml
    <android.support.design.widget.FloatingActionButton
        ...
        app:layout_behavior="<your-package>.FABBehavior"/>
```

Automagically, your FAB will be positioned above the BottomBar, and will move with it's "shy" :+1: 

I could push this as a pull request if it's ok for @roughike :smiley:

**Comment by yombunker** [comment]
@gsora are you sure you need this? doesn't anchoring it to the bottombar will do the same thing? normally we set it to anchor to the BottomBar and we just put it at the top of it, and that's it.

**Comment by gsora** [comment]
I was trying to get it working through CoordinatorLayout's anchor but it doesn't seem to work, the FAB stays under the BottomBar.

**Comment by louistsaitszho** [comment]
it does not work for me either. @gsora can you share more info of how you are using it? (right now i am guessing it's because for me the fab is in a fragment(coordinatorlayout) that is in the activity(another coordinatorlayout) that the bottom bar lives in)

**Comment by gsora** [comment]
I'm still in a prototype stage, but I'm using it in an Activity, where the root layout is a CoordinatorLayout

I'm placing the BottomBar above the FAB.

**Comment by yombunker** [comment]
@gsora @louistsaitszho well i can just say that it does work, because that's what we have in our production app (Microsoft Teams), and is nothing special, just follow CoordinatorLayout tutorials and you will get it :)
