### ISSUE TITLE
How to hide a tab in the code

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [roughike/BottomBar#692]
How to hide a tab in the code, I hope to control the tab in the code show and hidden.

**Comment by FridayShamblen** [comment]
Easy! This is how I do:

BottomBar bottomBar = (BottomBar) findViewById(R.id.bottomBar);
BottomBarTab tab = bottomBar.getTabWithId(R.id.tab_to_hide);
tab.setVisibility(View.INVISIBLE);

**Comment by AndroidJohnsonWang** [comment]
@FridayShamblen Thanks

**Comment by AmandaRiu** [comment]
I've played around with hiding a tab by setting its visibility to GONE, however, this causes the remaining tabs to be spaced awkwardly. Is there any way around this? Awesome library btw.

**Comment by shahzaibmuneeb** [comment]
Weird spacing for me too!

**Comment by AndroidJohnsonWang** [comment]
I've played around with hiding a tab by setting its visibility to GONE.Weird spacing.

**Comment by Va1iant** [comment]
me too.. is there anyway to workaround that issue than reloading different tabs config so the spacing looks better?

**Comment by FridayShamblen** [comment]
View.GONE is working for me --- sorry about View.INVISIBLE, of course that won't work. Wonder if calling requestLayout() on the bottom bar would reset it right for you?

In the end, I just wound up using different .xml files for my needs using setItems, as in `            
if ( x==1 ) {
bottomBar.setItems(R.xml.bottom_tabs_x);
}
`

**Comment by Va1iant** [comment]
Yea... seems to me that would be the only option to get the display right. Thanks!
