### ISSUE TITLE
How to hide bottom bar in code

### ISSUE THREAD

**Issue by DanteAndroid** [roughike/BottomBar#693]
How to hide bottom bar in code, it won't appear until next `show` method is called? (in Shy mode, when I swpie up, the bar shows.)

**Comment by roughike** [comment]
With the versions 2.3.0 and up, in shy mode, you can show / hide the bar as follows:

```java
// Show:
bottomBar.getShySettings().showBar();

// Hide:
bottomBar.getShySettings().hideBar();
```
