### ISSUE TITLE
line/space above bottomBar in com.roughike:bottom-bar:2.1.1

### ISSUE THREAD

**Issue by fetot** [roughike/BottomBar#696]
this is my layout design where i m getting space between fragmentContainer and bottomBar for reference please see the added screenshot.
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
>
    <FrameLayout android:id="@+id/fragmentContainer"
                 android:layout_width="match_parent"
                 android:background="@color/red"
                 android:layout_height="match_parent"
                 android:layout_above="@+id/bottomBar"
    />
    <com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:background="@color/light_gray"
        android:layout_alignParentBottom="true"
        app:bb_activeTabColor="@color/blue"
        app:bb_inActiveTabColor="@color/inactive_tab"
        app:bb_tabXmlResource="@xml/bottombar_tabs"
        app:bb_titleTypeFace="fonts/Roboto-Regular.ttf"/>
</RelativeLayout>

<img width="403" alt="screen shot 2017-03-18 at 6 01 49 pm" src="https://cloud.githubusercontent.com/assets/18626653/24072027/42f82db6-0c05-11e7-92da-5db5096d00df.png">

**Comment by MagicTurtle8** [comment]
Im having the same issue here as well. Let me know if you've worked it out.

**Comment by MagicTurtle8** [comment]
Ok the solution is to set `app:bb_showShadow="true"` as you have set the background of the bar to a different color as opposed to the default white.

**Comment by fetot** [comment]
it worked, Thanks a lot...

**Comment by yombunker** [comment]
We are working on a fix for this issue that should be ready in this days
