### ISSUE TITLE
change 2.0.2 to 2.1.1 BUILD FAILED

### ISSUE THREAD

**Issue by pangli** [roughike/BottomBar#698]
![image](https://cloud.githubusercontent.com/assets/7498978/24087316/5814d830-0d58-11e7-9be8-c364e1a9106b.png)

**Comment by roughike** [comment]
Could you give some steps to reproduce this issue? Is that your regular Android Studio project, or something else?

**Comment by yombunker** [comment]
@pangli could it be because you are compiling with 23 and the library uses 25 as the target and as such it uses the v25 of the support library, while you are using the v23 of all the google things.

**Comment by yombunker** [comment]
before we were using `com.android.support:appcompat-v7:23.2.1` but now we use the version 25, since like 2 months ago.

**Comment by pangli** [comment]
I changed to 
![image](https://cloud.githubusercontent.com/assets/7498978/24277340/75ab3dea-1077-11e7-99bf-abf426ece4b4.png) build success

**Comment by yombunker** [comment]
@pangli nice that you got it working :)

**Comment by pangli** [comment]
@yombunker thank you

**Comment by yombunker** [comment]
@pangli your welcome
