### ISSUE TITLE
Badge - Auto hide issue

### ISSUE THREAD

**Issue by JuxBzh** [roughike/BottomBar#699]
Hi,

I noticed an issue when using the "Badge" feature with my app. If _BottomBarTab.setBadgeCount()_ is called on the active tab then the badge becomes visible.

I fixed the issue by updating the _setBadgeCount()_ method and hiding the badge if the tab is marked as active:
```
    public void setBadgeCount(int count) {
        if (count <= 0) {
            if (badge != null) {
                badge.removeFromTab(this);
                badge = null;
            }

            return;
        }

        if (badge == null) {
            badge = new BottomBarBadge(getContext());
            badge.attachToTab(this, badgeBackgroundColor);
        }

        badge.setCount(count);
        if(isActive) badge.hide();
    }
```

**Comment by roughike** [comment]
Try the newest version, I believe I just fixed that yesterday.
