### ISSUE TITLE
Reset translation programmatically when using with CoordinatorLayout

### ISSUE THREAD

**Issue by zoopolitic** [roughike/BottomBar#70]
I see that all show/hide animations performed via behavior, but we don't have access neither bottom bar button container nor behavior methods (BottomNavigationBehavior.animateOffset(). So how can I reset translation programmatically ? thanks.

**Comment by NickM-27** [comment]
This would be perfect if anyone wanted to listen to swiping programmatically or anything like that

**Comment by zoopolitic** [comment]
@NickM-27 you can achieve this by forwarding scroll direction directly to BottomNavigationBehavior.

 BottomNavigationBehavior bottomBehavior = (BottomNavigationBehavior)
                ((CoordinatorLayout.LayoutParams) bottomBar.getLayoutParams()).getBehavior();
        bottomTabsBehavior.onDirectionNestedPreScroll(coordinatorLayout, bottomBar, null, 0, 0, null, VerticalScrollingBehavior.ScrollDirection.SCROLL_DIRECTION_DOWN);

change to VerticalScrollingBehavior.ScrollDirection.SCROLL_DIRECTION_UP if you want to hide bottomBar. It looks ugly, but I didn't find another way

**Comment by NickM-27** [comment]
@zoopolitic interesting, never knew about that one! I will have to try it to see what I think about it.
