### ISSUE TITLE
How to save the correct tab highlight when navigation across tab items?

### ISSUE THREAD

**Issue by Pantkowsky** [roughike/BottomBar#700]
Hey guys !

My question regards the event when I have for example 5 different tabs, each holding a different fragment. I navigate around the app, and with each click, a new fragment will be created, along with the new screen that will be displayed, and it will reflect the currently highlighted tab in the bottombar. However, when I backpress, I will only go back to the previously shown fragment however it won't affect the highlighted tab in the bottombar >> it will stay in the same position. I would like the bottom bar to *invalidate* the currently displayed tab in a sense that the bottombar icon is also pointing to the currently shown tab.

Any help would be appreciated ! @roughike

**Comment by roughike** [comment]
You can set selected tabs manually by using the ```selectTab...``` methods. There's no other way for that, since the BottomBar doesn't know about your Fragments, and it shouldn't know about them anyways.
