### ISSUE TITLE
Problem with Snackbar

### ISSUE THREAD

**Issue by Cesarsk** [roughike/BottomBar#704]
Guys, your bottombar is amazing! But I'm having a little issue. Basically, when I show my SNACKBAR, it doesn't fit perfectly with the bottombar, there is a little space between them. 

You can see what I mean in the following picture:

![cattura](https://cloud.githubusercontent.com/assets/3224160/24272106/0fd7cd9a-101c-11e7-8255-c132b9018b3d.PNG)

Is there a way to solve it? Thank you.

**Comment by roughike** [comment]
This is because of the shadow thats 4dp of height. I'm currently looking into other ways of showing it.

Temporary fix is "bb_showShadow:false".

**Comment by Cesarsk** [comment]
Thank you, that solved my issue.

Have a nice day.
