### ISSUE TITLE
Problem with Badge Count

### ISSUE THREAD

**Issue by kushmpatel** [roughike/BottomBar#707]
I added badge count on Tabs. And on first Tab (left most) badge count is not displayed properly. Badge count should be display on top right corner of Tab but on first Tab it display on top left corner.
![badge](https://cloud.githubusercontent.com/assets/20456431/24283096/b759c8d0-1089-11e7-9305-eb101ece6394.png)

**Comment by yombunker** [comment]
@kushmpatel can you give more information so that we can know what the issue is:

Is this in the preview or on a device?
how your layout looks like?
are you modifying anything trough code?
are you using the latest version? if not, what version are you using?

**Comment by kushmpatel** [comment]
@yombunker Issue resolved with latest version. Thanks.
