### ISSUE TITLE
The Quick Return sample is broken on API 25

### ISSUE THREAD

**Issue by roughike** [roughike/BottomBar#718]
STR:
- Start the sample app in Pixel emulator with API level 25.
- Open ThreeTabsQRActivity. The BottomBar is way too low behind the navbar.

Strangely, after clicking a tab, the bar jumps to a correct place and then everything works normally.

**Comment by yombunker** [comment]
@roughike i know what it is, i removed a "requestLayout()" that was causing a log message saying that we caused multiple passes of the layout phase, but, this appears to have broken that scenario
