### ISSUE TITLE
show() and hide() method is not available in latest version

### ISSUE THREAD

**Issue by kushmpatel** [roughike/BottomBar#721]
I want **show()** and **hide()** method functionality (_which was available in previous version - 1.4.0_) in latest library. Because I am using shy behavior in my application and want to **show()** and **hide()** bottom bar manually even if user doesn't scroll up or down in CoordinatorLayout.
What happens is like
Suppose now I am in Fragment A having list view in this Fragment. I use shy behavior so when I scroll on screen Bottom Bar hides. Now I click on any item of  list view and open Fragment B. Now Bottom Bar was hidden in Fragment A and when Fragment B opens it remains hidden. I don't want to keep it hide. I want to show bottom bar when any new fragment opens. So how can I achieve this using existing library ?

**Comment by roughike** [comment]
There's a PR for this right now. #722
