### ISSUE TITLE
How to set the width and height of the picture

### ISSUE THREAD

**Issue by sazewdfcvg16** [roughike/BottomBar#723]

**Comment by sazewdfcvg16** [comment]
![2017-03-31_201649](https://cloud.githubusercontent.com/assets/23505072/24550267/da04161c-164f-11e7-89bf-722da1852542.png)

**Comment by yombunker** [comment]
@sazewdfcvg16 can you elaborate more about what you are looking to get?

**Comment by roughike** [comment]
Looks like his pictures are too big, and they are clipped.

Two options:
A. [Follow the instructions on the README] to make correct sized icons.
B. If you want the icons stay that size, increase the height of the BottomBar.
