### ISSUE TITLE
Badge gets cropped when transitioning to the following tab

### ISSUE THREAD

**Issue by eros902002** [roughike/BottomBar#728]
With the badge set to hide on tab selection, when the following tab is tapped (the one on the right of the currently selected one) the badge is cropped. So the view of the next tab is above the bad and you can only see and edge of it.
🙂

**Comment by yombunker** [comment]
@eros902002  this is already been followed in another issue, i'll post this issue here and close this one

**Comment by eros902002** [comment]
Oh ok. I probably missed it. Thanks.

**Comment by yombunker** [comment]
@eros902002 this is being tracked in the issue #708
