### ISSUE TITLE
How can I integrate it in Xamarin.Android

### ISSUE THREAD

**Issue by jamsshhayd** [roughike/BottomBar#729]
I am using Xamarin.Android and I am willing to use it on Xamarin Studio or Visual Studio. How can I have **BottomBar** in Xamarin.Android?
Can you please provide **.aar** file for this project?

**Comment by johnJohnRipper** [comment]
https://github.com/pocheshire/BottomNavigationBar
this project is very similar ;)

**Comment by roughike** [comment]
This issue is not really related to this library. Use some ready made bindings like @johnJohnRipper mentioned, or see [Xamarin instructions on how to bind a Java library to C#](https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/).

**Comment by jamsshhayd** [comment]
Thanks for the help @johnJohnRipper . This library seems ditto copy of the one I am commenting.
@roughike yes you are right sir, but actually I was unable to find java bindings like the **.aar** file that will be converted to a **.dll** file when we parse it.

**Comment by johnJohnRipper** [comment]
For generate .aar file... you try to compile the java source code using android studio + gradle ... or create a new project and insert "compile 'com.roughike:bottom-bar:2.3.0' into build.gradle.
Gradle download .aar into .gradle folder.

**Comment by roughike** [comment]
Starting from 2.3.0, you can actually find the aar files in the [releases page](https://github.com/roughike/BottomBar/releases).

**Comment by johnJohnRipper** [comment]
Thanks roughike!!! nice job!

**Comment by jamsshhayd** [comment]
Thank you both of you. I have implemented the project that @johnJohnRipper  suggested for Xamarin.Android. :)
