### ISSUE TITLE
BottomBar titles gradually cut

### ISSUE THREAD

**Issue by apjx** [roughike/BottomBar#731]
Hi there,

When I open my app, then go back to my phone home screen, then go back to my app and so on, the titles of my bottombar becomes gradually hidden as you can see below. The text for the selected tab is ok, but the others are not correctly written. I have to close the app and reopen it to get "full" titles. Do you see what's wrong ?

![bottombartexthidden](https://cloud.githubusercontent.com/assets/16856843/24712740/f653ea18-1a23-11e7-9710-5512aa7e110f.png)

Thank you,

Alex

**Comment by roughike** [comment]
What version are you using? This used happen in the v1, but should not be happening in the newest version.

**Comment by apjx** [comment]
I had v2.0.2, I've just replaced it by v2.2.0 and it works now. Thank you!

**Comment by roughike** [comment]
Yes, seems like it was actually fixed in 2.1.0!
