### ISSUE TITLE
Can i have more than 5 tabs (8 tabs for example ) ?

### ISSUE THREAD

**Issue by slim0993** [roughike/BottomBar#739]
I need to have more than 5 tabs (items) ,what should i do ?

**Comment by yombunker** [comment]
@slim0993 don't see a restriction in our code about the number of tabs, your biggest problem will be that based on the material design guidelines that we follow, the size of each tab internal components can possibly be bigger than what can it be if you want 8 tabs. Other question, are we talking about phone or tablet? you can aslo try the tablet mode, that one can fit more tabs

**Comment by slim0993** [comment]
I am talking about a phone. In fact. I want to navigate between 8 tabs via an horizontal scrolling bar.
Can i do it ?

**Comment by yombunker** [comment]
@slim0993 well that goes against most of the material design guidelines, and while guidelines are not a must, they do represent the majority and that's what this library tries to achieve, we are working on custom tabs for a future release (some days from now) and maybe when that feature comes out would be easier to achieve this, by extending from the base BottomBar and having your own layout that has a scroll in it, and refactoring how the width of a tab is calculated and things like that that would need to be modified. But, don't expect this behavior to come for free. It will require some re-work from your side, that depending on how much do you really need from this library, it might be less work just to have your own bottombar that does what you need and only that.

**Comment by slim0993** [comment]
why tabs allow to have more than 8 items but bottom tabs don't ?

**Comment by yombunker** [comment]
don't ask me, check the guidelines, and the problem is not the amount, is the scrolling part, currently what we do is split the width into the number of tabs. So, if you want to deviate from that, you need to extend and customize, or just build your own.
