### ISSUE TITLE
RecyclerView messed-up after adding bottombar to the gradle

### ISSUE THREAD

**Issue by ajdeguzman** [roughike/BottomBar#74]
After adding `compile 'com.roughike:bottom-bar:1.1.8'` to the `build.gradle` file, it add some big whitespace below of each row item in a recyclerview. I know it's not related to the library but is there something added to the library that is conflict to my current files. I mean what are the requirements. Thanks!

**Comment by roughike** [comment]
Are you absolutely sure the whitespace is because of this library? If you remove it from the build.gradle and don't change nothing else, does it go away?

**Comment by NickM-27** [comment]
No issues with my recyclerview on 1.1.8

**Comment by seanbrodie** [comment]
I'm experiencing the same whitespace issue on 1.3.3
I'll update if I find a fix

**Comment by ajdeguzman** [comment]
Hi @seanbrodie I already spotted the problem here. I just updated my recyclerview library in the 'build.gradle' file. I think it's not compatible with the new update 
that's why.

**Comment by seanbrodie** [comment]
Updated my recyclerview library to v7:23.3.0 – still broken. 

I think this library might be conflicting with another one of my dependencies... I'll investigate further and see if I can find a workaround.
