### ISSUE TITLE
 Gap Between

### ISSUE THREAD

**Issue by yusuf77kenan** [roughike/BottomBar#740]
Hi I could not remove the gap in between ? Rejoice if you help me.
Thanks.

![adsiz](https://cloud.githubusercontent.com/assets/16848490/24830466/3fc02744-1c8f-11e7-9267-32becc58ad92.png)

`<com.roughike.bottombar.BottomBar
        app:bb_activeTabColor="@color/colorAccent"
        app:bb_inActiveTabColor="@color/colorAccent"
        android:background="@color/bottomBar"
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_alignParentBottom="true"
        app:bb_tabXmlResource="@xml/bottombar_tabs"
        android:foregroundGravity="center_vertical"
        app:bb_titleTextAppearance="@style/Base.TextAppearance.AppCompat.Small"
        />`

**Comment by yombunker** [comment]
@yusuf77kenan are you using the latest version? That was fix on that release.

**Comment by yusuf77kenan** [comment]
Very Thanks have a good day 👍

**Comment by yombunker** [comment]
@yusuf77kenan your welcome :)
