### ISSUE TITLE
Gray line above bottomBar Android 4

### ISSUE THREAD

**Issue by SergeyAppDroid** [roughike/BottomBar#746]
I tried to apply:
` app:bb_showShadow="false"`
But this method did not help to solve my problem. What to do?
![device-2017-04-11-212306](https://cloud.githubusercontent.com/assets/26580188/24921886/673440ce-1efd-11e7-8083-9463e4ea1637.png)

**Comment by roughike** [comment]
What version are you using?

**Comment by SergeyAppDroid** [comment]
my gradle file:
`compile 'com.roughike:bottom-bar:2.3.0'`

**Comment by yombunker** [comment]
@SergeyAppDroid @roughike i found the issue, i'm not using the flag for api21 and above, let me send a quick PR for that :)

**Comment by yombunker** [comment]
@SergeyAppDroid wait, you said for android 4? like API 19~ or is this on API 21+
cause the issue i had was on API 21+, but, on API 20- it should work as expected

**Comment by yombunker** [comment]
#749 this is the PR

**Comment by SergeyAppDroid** [comment]
I want to solve this problem more quickly. Should I wait for the updated version of the project? ((

**Comment by yombunker** [comment]
Code is in. This is going out in the next release
