### ISSUE TITLE
showShadow is not working!

### ISSUE THREAD

**Issue by a-bahmani** [roughike/BottomBar#748]
When I set app:bb_showShadow="false", the shadow is visible! and it's not hidden. Please fix it. Thanks

**Comment by yombunker** [comment]
@a-bahmani are you using the latest version?

**Comment by yombunker** [comment]
@a-bahmani forget it i found the issue :)

**Comment by yombunker** [comment]
#749 this is the PR

**Comment by a-bahmani** [comment]
Thanks. Yes, I am using version '2.3.0' and  Android Api 19, Does this problem have fixed in this version?

**Comment by yombunker** [comment]
I just sent a PR today

**Comment by yombunker** [comment]
The PR is in, it will go out on the next release

**Comment by SergeyAppDroid** [comment]
When will the next release?

**Comment by yombunker** [comment]
@SergeyAppDroid @a-bahmani from what @roughike told me, the release will be today, and from his time zone i'm guessing it will be in a couple of hours after he is out of work.

**Comment by yombunker** [comment]
the latest version is out, has some fixes for shadows

**Comment by a-bahmani** [comment]
It's OK, I tested. ،Thanks for caring about this details. Good luck.

**Comment by yombunker** [comment]
@SergeyAppDroid  i don't think we have a method exposed for that, but if you change the elevation to 0 i think that hides the shadow post-lollipop, but pre-lollipop will still show it cause is done differently

**Comment by SergeyAppDroid** [comment]
But when I use  `app:bb_showShadow="true"`  the shadow does not appear. Android 5.0 
![device-2017-04-14-210208](https://cloud.githubusercontent.com/assets/26580188/25050057/176a9ae2-2156-11e7-81f3-069d8062cbb5.png)
