### ISSUE TITLE
Bottom bar take extra space at below

### ISSUE THREAD

**Issue by vishalhalani** [roughike/BottomBar#750]
I have No actionbar theme to my application when i am use your bottom bar at below its show like below:
![device-2017-04-13-181313](https://cloud.githubusercontent.com/assets/11471570/25005322/126a315a-2076-11e7-9b78-a367832fe2c9.png)

Its take extra space dont know why?? 

My activity xml layout file like below:

`<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="com.a4cinfoengg.jewelleryapp.activity.HomeActivity">

    <RelativeLayout
        android:layout_width="match_parent"
        android:fitsSystemWindows="true"
        android:layout_height="match_parent">

        <FrameLayout
            android:id="@+id/frame_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:layout_above="@+id/bottomBar"

            android:animateLayoutChanges="true"/>

        

        <com.roughike.bottombar.BottomBar
            android:id="@+id/bottomBar"
            android:layout_width="match_parent"
            android:layout_height="@dimen/_64sdp"
            android:layout_alignParentBottom="true"
            app:bb_tabXmlResource="@xml/bottombar_tabs_color_changing"
            app:bb_behavior="shifting|underNavbar" />

    </RelativeLayout>

</android.support.design.widget.CoordinatorLayout>
`

**Comment by yombunker** [comment]
@vishalhalani you are using the undernavbar behavior and the shy behavior, the shy behavior is to hide the bottombar when you scroll in the content, and the undernavbar what it does is increase the height of the bottombar to look the same as if it wasn't under the navbar, BUT, you need to do a little more steps than just setting the behavior, follow the readme to find all the steps to allow drawing under navbar (cause the library can't do those for you)
