### ISSUE TITLE
SnackBar overlaps BottomBar

### ISSUE THREAD

**Issue by SergeyAppDroid** [roughike/BottomBar#754]
I use a snackbar in my project. But its height is 2 times greater. Another problem is that the snackbar overrides the bottomBar.

Normal:
![device-2017-04-17-222031](https://cloud.githubusercontent.com/assets/26580188/25099277/a1e37b0e-23bc-11e7-8e99-5a9cfaf2eec8.png)

After using snackbar:
![device-2017-04-17-222019](https://cloud.githubusercontent.com/assets/26580188/25099287/ac35c030-23bc-11e7-9a4c-6935c1df00a7.png)

**Comment by yombunker** [comment]
@SergeyAppDroid are you sure you are using the CoordinatorLayout correctly, i really don't think this has anything to do with this library, i would recommend go and surf some StackOverflow or some tutorials for a while to get a good grasp of CoordinatorLayout and then, if you still have issues with the BottomBar let us know and we can help you, but, by the looks of your result most likely you are not anchoring it to the top of the bottom bar and you are doing something different.

**Comment by SergeyAppDroid** [comment]
```
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorBackground">
```


    <com.roughike.bottombar.BottomBar
            android:id="@+id/bottomBar"
            android:layout_width="match_parent"
            android:layout_height="@dimen/bottomBarSize"
            android:layout_alignParentBottom="true"
            android:layout_gravity="bottom"
            android:background="@color/colorPrimary"
            app:bb_behavior="shy|underNavbar"
            app:bb_tabXmlResource="@xml/bottombar_tabs"
            app:bb_inActiveTabAlpha="0.6"
            app:bb_activeTabAlpha="1"
            app:bb_activeTabColor="@color/icons"
            app:bb_showShadow="false"
            app:bb_inActiveTabColor="@color/colorInActive"
            app:bb_badgesHideWhenActive="true"/>`

android:layout_gravity="bottom". Its right?

**Comment by yombunker** [comment]
@SergeyAppDroid sorry man, you have to look for tutorials or stackoverflow, cause this is not a library problem, you are using the coordinatorlayout in a wrong way, make sure you are anchoring to the correct views and so forth, but, thanks for using the library, if you have any trouble with it let us know.
