### ISSUE TITLE
Activate shy behavior in a concrete TAB

### ISSUE THREAD

**Issue by ilopezsmx2011** [roughike/BottomBar#763]
I would like to know if there is any way to activate and deactivate shy behavior between the different TAB.

**Comment by yombunker** [comment]
yes, look at the readme, there is something about getting the shy settings and modify them

**Comment by ilopezsmx2011** [comment]
Surely I am blind but I only see how to apply this functionality in the .xml and what you apply goes to all TABs.

I would like to know how to edit it from the .java.

Could you indicate which section of the README is what I am looking for?

Thank you very much in advance.

**Comment by yombunker** [comment]
@ilopezsmx2011 this is not in xml, this is trough code, when you want to enable it you enable it, when you want to hide it you hide it. for the case you are telling me, i would say that you need the tab selected listener and depending on the tab selected then you will have to set the hide or show property.
