### ISSUE TITLE
Can not programmatically change BottomBar background color!

### ISSUE THREAD

**Issue by TThana** [roughike/BottomBar#764]
bottomBar.setBackgroundColor(ResourcesCompat.getColor(getResources(),theme.colorPrimary,null)); 
nothing happen!

**Comment by TThana** [comment]
the background is still white

**Comment by TThana** [comment]
but it works in xml 

android:background="@color/blue"

**Comment by yombunker** [comment]
@TThana well there is a quick explanation why that doesn't work while the other one does, if you go and look at the code inside BottomBar you will see that there is a "fake" view behind the tabs and that view is the one that has the back ground color, so you can change the BottomBar color as many times as you want, but it will always be behind the "fake" view, so there are only 2 ways of doing this:

1. do a findViewById and search for the "fake" view and modify it
2. you can set the color from xml to be something like 00FFFFFF which is white transparent and then you will be able to see the color of the BottomBar

Maybe this functionality will come in the next release but there is no promise

**Comment by TThana** [comment]
thank you

**Comment by yombunker** [comment]
@TThana your welcome
