### ISSUE TITLE
Readme bottombar bb_behavior

### ISSUE THREAD

**Issue by jlilja** [roughike/BottomBar#767]
The newly added iconsOnly and its other options on the bb_behavior is not listed and described in the readme file.

I've been going through the files trying to find the iconsOnly and was thinking that, to save other devs time, that option should be described in the readme.

**Comment by robiin** [comment]
I agree.

**Comment by yombunker** [comment]
@jlilja @robiin thanks for the feedback, i thought it was. i'll updated when i get the chance or if @roughike has time he would do it.
