### ISSUE TITLE
bottomBar.setDefaultTab(this.tabId) triggers setOnTabSelectListener

### ISSUE THREAD

**Issue by JimClermonts** [roughike/BottomBar#769]
bottomBar.setDefaultTab(this.tabId) triggers setOnTabSelectListener. It gets into a loop. I'm on version 2.0.2, not sure if this was an issue and has been solved or that I'm using it wrong.

**Comment by yombunker** [comment]
if you are doing something that changes the tab on the tab select listener it will get into a loop, other thing you can do, is don't set the listener until after you call set default tab,.

**Comment by JimClermonts** [comment]
Like below? It still gets triggered....

```
getBottomBar().setDefaultTab(this.tabId);
getBottomBar().setOnTabSelectListener(tabId -> {
                MainActivity.start(this, tabId);
                finish();
        });
```

**Comment by JimClermonts** [comment]
This is how I have it, which works kinda hacky because I need to finish my Activity every time.

```
    private boolean firstTimeTab = true; //member var

        bottomBarHandler.getBottomBar().setOnTabSelectListener(tabId -> {
            // A bug in the BottomBar triggers setOnTabSelectListener as soon as
            // setTab is set. So firstTimeTab avoids this "first time" behaviour
            if (firstTimeTab) {
                bottomBarHandler.setTab(this.tabId);
                firstTimeTab = false;
            } else {
                MainActivity.start(this, tabId);
                finish();
            }
        });
```

**Comment by yombunker** [comment]
@JimClermonts why don't you do what i told you of flipping the order?

getBottomBar().setOnTabSelectListener(tabId -> {
                MainActivity.start(this, tabId);
                finish();
        });
getBottomBar().setDefaultTab(this.tabId);

**Comment by JimClermonts** [comment]
@yombunker thanks for your reply. This doesn't work. In 2 activities I have this code. And in the second it triggers the MainActivity again. So a loop ...

**Comment by mradzinski** [comment]
```
getBottomBar().setDefaultTab(this.tabId);
getBottomBar().setOnTabSelectListener(tabId -> {
                MainActivity.start(this, tabId);
                finish();
        });
```

Calling `setDefaultTab` in this way CAN'T trigger `setOnTabSelectListener`, the listener simply doesn't exist at the moment of the invocation. `setDefaultTab` is totally synchronic and avoid notifying any listener if the same is `null`, so I can assure you that `setOnTabSelectListener` can't be called beforehand. Post your full code here, there must be a bug somewhere.

**Comment by yombunker** [comment]
@JimClermonts sorry don't know why i posted that code, that was tottaly wrong :P i was at work and just quickly replied, @mradzinski is right, there is no way to have the listener get invoked.
