### ISSUE TITLE
bottom bar slider

### ISSUE THREAD

**Issue by xtien** [roughike/BottomBar#775]
This is a protest more than an issue.

I use your bottombar in a project for my client. I have added a few features. One is a slider. Today I'm looking into merging these features back into your code and creating a pull request. To my surprise, I see someone else has already uploaded a movie of my bottombar slider here:
https://github.com/roughike/BottomBar/issues/773

Jim Clermonts joined our project as a contractor two weeks ago, two months after I finished the orange slider in the bottom bar. Jim now offers to contribute my code to your project. He has upload a movie without the consent of the company I made it for, and without telling me.
Please note Jim Clermonts is not the person who created the example he sent you, nor does he have the legal right to show you. The app is in development and will be publish in one or two months. I have notified the owner of the app.

If you need proof for what I write, I can send you screenshots of our github repo showing the roughike bottombar and the slider,  in January. I can also provide proof that Mr Clermonts only joined my project on May 1st. 

Please contact me via my github account, or via christine@christine.nl

kind regards
Christine

**Comment by xtien** [comment]
Just to be clear, the .mov is not an animation, it's a video screenshot of the app I made.

**Comment by yombunker** [comment]
@xtien sorry i don't understand what you want us to do. can you explain what is the final goal?
And i'm sorry if he exposed internal information to this repo without your consent that sucks.

**Comment by xtien** [comment]
Nothing. Do nothing. I was just pissed that a coworker is offering to contribute my code to roughike.
