### ISSUE TITLE
BottomBar doesn't show on a Galaxy S8

### ISSUE THREAD

**Issue by jaybuangan** [roughike/BottomBar#791]
I'm having a strange bug where the bottom bar shows up for all other phones but the Galaxy S8.  I'm not sure if it has anything to do with the higher height resolution.  I've been able to recreate it using the Android Emulator (since I don't actually have a physical device but know it does happen from other users who do).  Any help would be great.  This is my activity_main.xml if it helps.. (sorry for the markdown formatting.  )

`<?xml version="1.0" encoding="utf-8"?>

<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="com.asystiv.asystivmobileordering.MainActivity">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingTop="@dimen/nomargin"
        android:theme="@style/AppTheme.AppBarOverlay"
        >

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:layout_scrollFlags="scroll|enterAlways"
            app:popupTheme="@style/AppTheme.PopupOverlay"
            app:titleTextAppearance="@style/Toolbar.TitleText"

            >
            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:textColor="#ffffff"
                android:id="@+id/currentLocationName"
                android:textSize="13dp"
                android:gravity="center_vertical"
                android:maxLines="2"
                android:ellipsize="end"
                android:text="Asystiv Mobile Ordering Applications"
                />

        </android.support.v7.widget.Toolbar>

        <me.zhanghai.android.materialprogressbar.MaterialProgressBar
            android:id="@+id/progress_bar"
            android:layout_width="match_parent"
            android:layout_height="8dp"
            android:indeterminate="true"
            app:mpb_progressStyle="horizontal"
            app:mpb_useIntrinsicPadding="false"
            style="@style/Widget.MaterialProgressBar.ProgressBar.Horizontal" />

    </android.support.design.widget.AppBarLayout>

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="?attr/actionBarSize"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        >

        <FrameLayout
            android:id="@+id/contentContainer"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/white"
            android:paddingTop="8dp"
            android:layout_above="@+id/bottomBar"
            />

        <com.roughike.bottombar.BottomBar

            android:id="@+id/bottomBar"
            android:layout_width="match_parent"
            android:layout_height="55dp"
            app:bb_tabXmlResource="@xml/bottombar_tabs"
            app:bb_titleTextAppearance="@style/tabStyle"
            app:bb_badgesHideWhenActive="false"
            />

    </RelativeLayout>

</android.support.design.widget.CoordinatorLayout>`

**Comment by angstream** [comment]
Did you solve this issue?

**Comment by jaybuangan** [comment]
sorry this was a non-issue.  it was all on my end.
