### ISSUE TITLE
Can it works on Tablets?

### ISSUE THREAD

**Issue by jp1017** [roughike/BottomBar#8]
Hi, guys.

Can this library used on the `left` of the Tablets?

**Comment by roughike** [comment]
@jp1017 
Not yet. In the future, yes.

**Comment by jp1017** [comment]
cool, thanks.

**Comment by roughike** [comment]
I'm keeping this opened until I fix it.

**Comment by roughike** [comment]
Aaand it's done.

Update your depency to ```compile 'com.roughike:bottom-bar:1.0.1'``` for tablet-supported goodness.
