### ISSUE TITLE
Tabs with different behaviours

### ISSUE THREAD

**Issue by ateodor1** [roughike/BottomBar#80]
Hello, first tks for the lib.

I have a fragment that I put the BottomBar with 3 tabs, each has different behaviours. The first open a popup to choose between some options and then open an activity, the second opens an activity and the third opens a fragment. I created like this:

xml:

<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/myCoordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/myScrollingContent"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <it.gmariotti.cardslib.library.view.CardViewNative
                android:id="@+id/cardResumo"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="12dp"
                android:layout_marginRight="12dp"
                android:layout_marginTop="12dp"/>

        </LinearLayout>

    </android.support.v4.widget.NestedScrollView>

</android.support.design.widget.CoordinatorLayout>

And java:

mBottomBar = BottomBar.attachShy((CoordinatorLayout) rootView.findViewById(R.id.myCoordinator), rootView, savedInstanceState);
        mBottomBar.noTabletGoodness();
        mBottomBar.setItems(
                new BottomBarTab(R.mipmap.approval, "Approval"),
                new BottomBarTab(R.mipmap.register, "Register"),
                new BottomBarTab(R.mipmap.search, "Search")
        );

        mBottomBar.noTopOffset();
        mBottomBar.setSelected(false);
....

// Listen for tab changes
        mBottomBar.setOnItemSelectedListener(new OnTabSelectedListener() {
            @Override
            public void onItemSelected(int position) {
                if (position == 0) {
                    openOptionsToSelect();
                }
                if (position == 1) {
                    Intent i = new Intent(getActivity(), RegisterActivity.class);
                    getActivity().startActivity(i);
                }
                if (position == 2) {
                    BaseFragment f = br.com.gteo.cnb.fragment.porteiro.MyFragment.newInstance();
                    FragmentTransaction transaction = getActivity().getSupportFragmentManager().beginTransaction();
                    transaction.replace(R.id.fragment_container, f, f.getName());
                    transaction.addToBackStack(f.getName());
                    transaction.commit();
                }
            }
        });

I tried to attach using all the options but I always get the same behaviour:
1) Sometimes the first tab does not work, sometimes it works.
2) The second tab works fine, it opens the activity and when I close it is still selected
3) The third tab replaces the fragment but if I press the back button, the first tab is selected instead of the third.

Can you please check if I'm not using correctly ? Tks.

**Comment by roughike** [comment]
Update to the version _1.2.4._, use the new listeners and check if this problem still exists.

**Comment by ateodor1** [comment]
Hi, it fixes the problem of reselecting. I want the same behaviour for select or reselect, so in both I call the same handler. Now the issue is that if I click on one option and open a fragment, if I press the back button, the reselect is executed automatically and perform an action without the user clicking...

**Comment by roughike** [comment]
You shouldn't be adding the Fragments to the backstack if the user switches between them using BottomBar tabs. It could be really frustrating / confusing to the user.

However, you can of course do as you please. But I'm sorry, I'm not changing the behavior of the listeners to take your use case into account, so I'm closing this issue.
