### ISSUE TITLE
Changelog with point releases

### ISSUE THREAD

**Issue by ncapdevi** [roughike/BottomBar#81]
A posted changelog with each release would be very helpful for keeping up with all oft he rapid development and changes/fixes.  Thanks so much for all of the great work

**Comment by roughike** [comment]
I will probably start doing one, once the updates are not daily.

I'm already having a rough time with managing all the issues and testing for bugs, let alone making a changelog with every feature in the newest release, as there's going to be a metric fuckton of them. This first week (give or take a couple days) is just crazy, as there's shitloads of code made in a relatively small timeframe.

I understand your point though, and will start posting changelogs at some point when the dust settles and I'm not releasing 2-3 versions every day.

**Comment by ncapdevi** [comment]
Totally understand.  Again, very much appreciated.
