### ISSUE TITLE
bottombar overlapping navigation drawer

### ISSUE THREAD

**Issue by b2cbd** [roughike/BottomBar#810]
I was trying to implement `bottombar` with android default `navigation drawer`. It's working nice but left navigation drawer is going under bottombar on slide,  I can't figure out what is the problem, how to fix it?

**Comment by azeemchaudhrry** [comment]
@b2cbd are you able to resolve this overlapping issue?

**Comment by b2cbd** [comment]
@azeemchaudhrry Yes, you need to put bottom bar layout as a first child of drawer layout in your xml file.

**Comment by Zukune** [comment]
@b2cbd Hi, would you please share your xml code? I'm still having that same problem. Thank you so much.

**Comment by azeemchaudhrry** [comment]
@Zukune this might help you.

xml:
  <DrawerLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
      android:id="@+id/drawer_layout"
      android:fitsSystemWindows="false">
    <LinearLayout
              android:id="@+id/content_layout"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">
      
      <include layout="@layout/toolbar" />
      
      <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
    </LinearLayout>

</DrawerLayout>

C#:
_bottomBar = BottomBar.Attach(content_layout, savedInstanceState);

**Comment by Zukune** [comment]
@azeemchaudhrry  Thank you for your reply but cannot resolve method Attach. Do u have any idea of this? Thank you

**Comment by azeemchaudhrry** [comment]
if you are using in native android then go attach().
above code is for xamarin I am using this library in xamarin.

**Comment by b2cbd** [comment]
@Zukune 

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/nav"
        android:orientation="vertical"

        <include layout="@layout/toolbar"
            android:id="@+id/toolbar"/>

    </LinearLayout>

    <android.support.v4.widget.DrawerLayout
        android:id="@+id/drawer_layout"
        android:layout_below="@+id/nav"
        android:layout_width="match_parent"
        android:layout_height="match_parent" >

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="1dp">

            <com.roughike.bottombar.BottomBar
                android:id="@+id/bottomBar"
                android:layout_width="match_parent"
                android:layout_height="55dp"
                android:layout_alignParentBottom="true"
                android:background="@color/main_color_500"
                app:bb_activeTabAlpha="1"
                app:bb_inActiveTabAlpha="0.6"
                app:bb_activeTabColor="@android:color/white"
                app:bb_inActiveTabColor="@android:color/white"
                app:bb_titleTextAppearance="@style/TextAppearance.AppCompat.Caption"
                app:bb_showShadow="false"
                app:bb_tabXmlResource="@xml/menu_bottombar" />

            <FrameLayout
                android:id="@+id/container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_above="@id/bottomBar"/>

        </RelativeLayout>

        <FrameLayout
            android:id="@+id/content_frame"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <include
            android:layout_width="@dimen/drawer_width"
            android:layout_height="match_parent"
            layout="@layout/list_view"
            android:layout_gravity="start"/>
    </android.support.v4.widget.DrawerLayout>

</RelativeLayout>`

**Comment by Zukune** [comment]
@azeemchaudhrry @b2cbd Thank you guys for your help, it's working now.
