### ISSUE TITLE
Custom elevation for BottomBar

### ISSUE THREAD

**Issue by TemMax** [roughike/BottomBar#83]
Can you add this method? This will be very useful.

**Comment by roughike** [comment]
By elevation, do you mean a larger shadow or controlling the z-index?

**Comment by TemMax** [comment]
Yes. Controlling z-index may be very useful.

**Comment by NikolaDespotoski** [comment]
@TemMax According to MD specs Bottom navigation component should have 8dp elevation to be between navigation drawer and snackbar. :)

**Comment by roughike** [comment]
@NikolaDespotoski is right.

Controlling z-index / elevation would possibly break some behavior with snackbars.

I'm closing this one.
