### ISSUE TITLE
Listener for selected, but not necessarily switched

### ISSUE THREAD

**Issue by ncapdevi** [roughike/BottomBar#84]
There are cases when you want to perform an action when the user presses a tab that they're already on. For example if the user presses on the currently selected tab, you can clear that fragment stack.  The current onTabSelectedListener is only called down on tab switches, but it would be nice to pass down the selection regardless, possibly with a boolean to indicate that it has or hasn't switched.

**Comment by roughike** [comment]
That's actually a feature that's going to be in the next version. I have an open pull request for it, and I'll just have to review it, so it's gonna be soon!

**Comment by ncapdevi** [comment]
Great! I'll mark it as closed for now. If the pull request doesn't work out, let me know and I'll write one up.
