### ISSUE TITLE
update supportLibraryVersion to 25.3.1

### ISSUE THREAD

**Issue by valuppo** [roughike/BottomBar#855]
Hello,
Can you update the supportLibraryVersion in Gradle to 25.3.1
Thank you

**Comment by agarcialeon** [comment]
You can download the project as a Zip file and update the version in the build.gradle file inside the app folder of the project. Then use 'Make project' under Build menu and copy the bottom-bar-release.aar that has been generated in the build folder of the bottom-bar folder (module) in your project.

You can import the aar file inside your project like this (third answer):
[How to manually include external aar package in Android Studio](https://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst)

Then you only need to update the build.gradle file with the design library.
Hope that this helps.

**Comment by valuppo** [comment]
Okay, thanks a lot dude
