### ISSUE TITLE
How to change BottomBar background,

### ISSUE THREAD

**Issue by timmy6** [roughike/BottomBar#86]
1,I want to change BottomBar background,I try to use BottomBar.setBackgroundColor(),but it invalid.;

2.I want to set select status,if is state_selected,I set background for tab,else I set other background。
Is there any way？？

**Comment by roughike** [comment]
1. It's explained in the readme.

```java
// Setting colors for different tabs when there's more than three of them.
// You can set colors for tabs in three different ways as shown below.
mBottomBar.mapColorForTab(0, "#7B1FA2");
...
```

2. You mean changing the active tab background, but not the entire BottomBar background? That's not currently possible.
