### ISSUE TITLE
Why setActiveTabColor works on at most three tabs?

### ISSUE THREAD

**Issue by HighFlyer13** [roughike/BottomBar#87]
Hello!

Could you explain this limitation?

**Comment by roughike** [comment]
Because when using more than three tabs, the entire BottomBar background is non-white, so the all tabs icon and text colors are white.

**Comment by HighFlyer13** [comment]
Why BottonBar background can't be white with four tabs? Can't find this restriction on bottom navigation spec page.

**Comment by roughike** [comment]
I re-read the spec, seems you're right.

I'll make the limitation optional in the next versions.

**Comment by grocaDW** [comment]
Yep, This hasn't been changed as of yet and I looking forward to be able to have white background with four tabs as well. Or be able to choose when to activate the color change.

Thanks! Keep up the good work! :)

**Comment by roughike** [comment]
Now _partially_ (you lose the shifting mode benefits) possible in version _1.3.2._ 

```java
// Show all titles all the time.
mBottomBar.useFixedMode();
mBottomBar.setActiveTabColor("#FF0000");
```

**Comment by roughike** [comment]
This and much more customization options are now possible in the newest version (2.0 and up)!
