### ISSUE TITLE
Can add method to change the MAX_FIXED_TAB_COUNT?

### ISSUE THREAD

**Issue by kmwyeung** [roughike/BottomBar#88]
public class BottomBar extends FrameLayout implements View.OnClickListener, View.OnLongClickListener {
    private static final long ANIMATION_DURATION = 150;
    private static final int MAX_FIXED_TAB_COUNT = 3;
 ....

I want to change MAX_FIXED_TAB_COUNT to 4.
Can add new method, please?
Thank you!

**Comment by roughike** [comment]
Could be done in the future. I'm first focusing on implementing the Material Design spec correctly.

**Comment by roughike** [comment]
Already done, will be in tomorrow's version.

**Comment by ngoa** [comment]
Thanks.

**Comment by ngoa** [comment]
@roughike How do I get the latest version through gradle?  Do I need to update version number?

**Comment by roughike** [comment]
Yes, update the version number to _1.3.2._

```java
mBottomBar.setMaxFixedTabs(3);
```
