### ISSUE TITLE
No selected colors

### ISSUE THREAD

**Issue by Albiwalbi** [roughike/BottomBar#90]
Is there a possibility to disable the selected color manually or just to turn it off?
Because I can't click a item when it is highlighted and that is necessary in my app.
Thank you!

I was thinking on some code like this:

> mBottomBar.makeSelectable(false);

**Comment by roughike** [comment]
What do you mean by not being able to click an active item?

**Comment by Albiwalbi** [comment]
I'm creating a appliction based on a webview. Now I want the user to explore my website with the app. They can click for example on the game tab and the url loads in the webview. Then they click on a game to get more details about it and that loads in the webview. Then they want to go back and they tap again on the gaming icon. But, because it is still marked as active, the user can't tap on it again to go to the main page of apps.

So my request is to make an option to disable that higlight and not-clickable functions.
Thank you!

**Comment by roughike** [comment]
There's now new listeners for detecting tab reselection.

```java
mBottomBar.setItemsFromMenu(R.menu.bottombar_menu, new OnMenuTabClickListener() {
    @Override
    public void onMenuTabSelected(@IdRes int menuItemId) {
        if (resId == R.id.bottomBarItemOne) {
            // The user selected item number one.
        }
    }

    @Override
    public void onMenuTabReSelected(@IdRes int menuItemId) {
        if (resId == R.id.bottomBarItemOne) {
            // The user reselected item number one, update your content.
        }
     }
 });
```

Try the sample app.

**Comment by Albiwalbi** [comment]
Is it also possible to disable the highlight function?

**Comment by roughike** [comment]
Not right now.

**Comment by Albiwalbi** [comment]
Okay, thank you!
