### ISSUE TITLE
Bug when initializing the bar with the screen off (as in running debug from Android Studio)

### ISSUE THREAD

**Issue by ncapdevi** [roughike/BottomBar#92]
When you have your phone screen off, and the app is launched (through ADB, which will happen if you launch through debugging in Android Studio), The bottombar isn't correctly placed, and the offeset of the top is off as well. My guess is that it's relying on measurement's that havent been performed yet. Here's an image

https://lh3.googleusercontent.com/Wp50se-iJFXUzmTwQrHp3qHGRzXgsw0oKj-iA7wD4WZkb2Hy8hW9F4faCitDoCUwasRidnQo-4y1mQ=w514-h913-no

**Comment by roughike** [comment]
This has been fixed at least in the newest versions, if not before!
