### ISSUE TITLE
when I use cold start, the BottomBar only display part

### ISSUE THREAD

**Issue by DaidongStudio** [roughike/BottomBar#93]
![img][1]

  [1]: https://ooo.0o0.ooo/2016/03/25/56f4fe3162c05.jpg

it`s my code: 

    onCreate(Bundle savedInstanceState){   
        super.onCreate(savedInstanceState)
        new Handler().postDelayed({
            setTheme(R.style.AppTheme_NoActionBar)
            setContentView(R.layout.activity_main)
            setSupportActionBar(toolbar)
            mBottomBar = BottomBar.attachShy(cdl, savedInstanceState)
           mBottomBar.setItemsFromMenu(R.menu.bottombar_menu, new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId) {
                if (resId == R.id.bottomBarItemOne) {
                    // The user selected item number one.
                }
            }

            @Override
            public void onMenuTabReSelected(@IdRes int menuItemId) {
                if (resId == R.id.bottomBarItemOne) {
                    // The user reselected item number one, scroll your content to top.
                }
            }
      
        }, 500)
    }

the style:
  
        <style name="AppTheme.Launcher" parent="AppTheme.NoActionBar">
            <item name="android:windowBackground">@drawable/launch_screen</item>
        </style>

how to fix it?

**Comment by DaidongStudio** [comment]
I found that if the `Handler.postDelayed` does not apply  there is no problem.

**Comment by roughike** [comment]
So without the handler there's no problem? Is there a reason you're using that? Seems kinda off.

Are you trying to display a splash screen or something?

**Comment by ncapdevi** [comment]
This is the same issue as #92

**Comment by DaidongStudio** [comment]
yes, without handler there`s no problem. I just set a theme for Activity
