### ISSUE TITLE
Using my Fragment 

### ISSUE THREAD

**Issue by RobFTW** [roughike/BottomBar#95]
` @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar.setFragmentItems(getSupportFragmentManager(), R.id.fragmentContainer,
 new BottomBarFragment(SampleFragment.newInstance("Content for me."), R.drawable.ic_me, "Me"),
                new BottomBarFragment(SampleFragment.newInstance("Content for contact."), R.drawable.ic_contact, "Contact"),
                new BottomBarFragment(SampleFragment.newInstance("Content for chat."), R.drawable.ic_chat, "Chats"),
                new BottomBarFragment(SampleFragment.newInstance("Content for store."), R.drawable.ic_store, "Store"),
                new BottomBarFragment(SampleFragment.newInstance("Content for settings."), R.drawable.ic_settings, "Settings")

                );
`

How do I change the code above to link to my own fragment. New to java.

**Comment by roughike** [comment]
[Read about Fragments here.](http://developer.android.com/guide/components/fragments.html)

Also note that the ```setFragmentItems()``` is deprecated.
