### ISSUE TITLE
Change the colors of text and icons of active and non-active tabs

### ISSUE THREAD

**Issue by lnfn** [roughike/BottomBar#96]
Will the added ability to change the colors of text and icons of active and non-active tabs?

**Comment by Albiwalbi** [comment]
Please make this possible, I think there are a lot of reasons to implement this kind of feature!

**Comment by roughike** [comment]
You've been able to customize the active tab color for a while now.

```java
mBottomBar.setActiveTabColor("#FF0000");
```

**Comment by glalwani2** [comment]
For me SetActiveTabColor is not working in Xamarin Android. Any idea why this is happening with me? Do I need to do anything before setting the color.
