### ISSUE TITLE
Possible Bug BottomBar plus Firebase

### ISSUE THREAD

**Issue by alfox10** [roughike/BottomBar#97]
I has created this simple project to test BottomBar and Firebase. And MAYBE there is a bug with this database. I paste my code here so you can help to understand if I made any mistakes or there is a real bug.

MAIN ACTIVITY XML

`    <?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"

    tools:context="it.unisa.alfonso.myfragmenttest1.MainActivity">

    <FrameLayout
        android:id="@+id/frame_layout_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent"></FrameLayout>
    </RelativeLayout>`

ITEM XML

`    <?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:text="ITEMS"
        android:id="@+id/text_chat_item"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    </RelativeLayout>`

LISTVIEW XML

`    <?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ListView
        android:id="@+id/mylist"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"></ListView>

    </RelativeLayout>`

SIMPLE ADAPTER

`    public class MyAdapter extends BaseAdapter {
    Context context;
    ArrayList<String> data;
    LayoutInflater inflater;
    public MyAdapter(Context context, ArrayList<String> data) {
        this.context = context;
        this.data = data;
        inflater = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    }

    @Override
    public int getCount() {
        // TODO Auto-generated method stub
        return data.size();
    }

    @Override
    public Object getItem(int position) {
        // TODO Auto-generated method stub
        return data.get(position);
    }

    @Override
    public long getItemId(int position) {
        // TODO Auto-generated method stub
        return position;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {

        View vi = convertView;
        if (vi == null)
            vi = inflater.inflate(R.layout.chat_items, null);
        TextView text = (TextView) vi.findViewById(R.id.text_chat_item);
        text.setText(data.get(position));
        return vi;
    }
    }`

SIMPLE FRAGMENT

`    public class MyFragment extends ListFragment {

    private View v;
    ListView usr_chats;
    ArrayList<String> arrayList;
    MyAdapter myAdapter;

    public MyFragment(){}

    public static MyFragment newInstance(){
        MyFragment f = new MyFragment();
        return f;
    }
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        v = inflater.inflate(R.layout.list_layout, container, false);
        usr_chats =  (ListView) v.findViewById(R.id.list_view_container);
        //-------------------------------
        return v;
    }
    
    @Override
    public void onViewCreated (final View view, Bundle savedInstanceState) {
        Log.d("Test", "OnViewCreated");
        arrayList =new ArrayList<>();
        myAdapter = new MyAdapter(getContext(),arrayList);
        Firebase.setAndroidContext(getContext());
        Firebase firebase = new Firebase("https://fiery-fire-7347.firebaseio.com/polls");
        usr_chats.setAdapter(myAdapter);

        firebase.addChildEventListener(new ChildEventListener() {
            @Override
            public void onChildAdded(DataSnapshot dataSnapshot, String s) {
                if (s != null) {
                    Log.d("Test", s);
                    arrayList.add(s);
                    myAdapter.notifyDataSetChanged();
                }
            }

            @Override
            public void onChildChanged(DataSnapshot dataSnapshot, String s) {

            }

            @Override
            public void onChildRemoved(DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(DataSnapshot dataSnapshot, String s) {

            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {

            }
        });

    }

}
`

ACTIVITY MAIN NO BOTTOMBAR

`    public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        MyFragment itemFragment = MyFragment.newInstance();
        android.support.v4.app.FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
        fragmentTransaction.add(R.id.frame_layout_main,itemFragment);
        fragmentTransaction.commit();
}
    }`

ACTIVITY MAIN WITH BOTTOMBAR

`    public class MainActivity extends AppCompatActivity {
BottomBar mBottomBar;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // mBottomBar = BottomBar.attach(this, savedInstanceState);
        mBottomBar = BottomBar.attach(MainActivity.this,savedInstanceState);
        mBottomBar.setFragmentItems(getSupportFragmentManager(), R.id.frame_layout_main,
                new BottomBarFragment(MyFragment.newInstance(),android.R.drawable.ic_dialog_alert, "Chat")
        );

        mBottomBar.setActiveTabColor("#C83F09");

    }
    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);

        // Necessary to restore the BottomBar's state, otherwise we would
        // lose the current tab on orientation change.
        mBottomBar.onSaveInstanceState(outState);
    }
    }`

If I use the ACTIVITY MAIN NO BOTTOMBAR the content is downloaded from my firebase and applied to the ListView, but if I use the ACTIVITY MAIN WITH BOTTOM BAR the content is downloaded from my firebase (I can see it in the Android Monitor) but the ListView show me nothing

**Comment by ViliusKraujutis** [comment]
Just a note: could you please copy your code to gist.github.com, so it would be easier to read? And I suppose, screenshot might be helpful here.

Best regards.

PS.: I'm just looking for another issue. Sorry for not being helpful just now.

**Comment by roughike** [comment]
The ```setFragmentItems()``` has been deprecated a while ago, and you should be handling your Fragments by yourself now.
